wvlet/airframe

- src/main/scala/wvlet/airframe/AirframeMacros.scala
- src/test/scala/wvlet/airframe/AirframeMacrosTest.scala
- src/test/scala/wvlet/airframe/LifeCycleManagerTest.scala
This PR translates bind[X]:
```
val x = bind[X] 
```
into the following code **if X is non abstract type** and has the default constructor:
```
val x = new X { protected[this] __current_session = (session) }
```
This is much faster than using runtime reflection to instantiate trait.
> Improve injection performance with compile-time code generation

- scalastyle-config.xml
There is no reason for us to restrict the line width to 100 (though this is used in Databricks). line width 100 tends to introduce unnecessary line wraps and breaks the code flow. 
And also we need to allow using 4 and 5 ass non magic number for writing provider codes.
> Fix scalastyle

- src/main/scala/wvlet/airframe/AirframeMacros.scala
- src/main/scala/wvlet/airframe/Binder.scala
- src/main/scala/wvlet/airframe/LazyF0.scala
- src/main/scala/wvlet/airframe/Session.scala
- src/main/scala/wvlet/airframe/SessionImpl.scala
- src/main/scala/wvlet/airframe/package.scala
- src/test/scala/example/BindSingleton.scala
- src/test/scala/wvlet/airframe/AirframeTest.scala
- src/test/scala/wvlet/airframe/ProviderTest.scala
- src/test/scala/wvlet/airframe/SingletonTest.scala
When application developer already knows some object needs to be a singleton, `bindSingleton[X]` can enforce using singleton even if the design doesn't have toSingleton binding.
> Add bindSingleton[X]

- airframe-macros/src/main/scala/wvlet/airframe/AirframeMacros.scala
- build.sbt
whitebox macros will be deprecated in future Scala versions. For details, see: http://docs.scala-lang.org/overviews/macros/blackbox-whitebox.html
> Use blackbox macros

- airframe-config/src/main/scala/wvlet/config/Config.scala
- airframe-config/src/main/scala/wvlet/config/YamlReader.scala
- airframe-config/src/test/resources/classes.yml
- airframe-config/src/test/scala/wvlet/config/ConfigTest.scala
- airframe-config/src/test/scala/wvlet/config/YamlReaderTest.scala
- surface/jvm/src/main/scala/wvlet/surface/reflect/ObjectBuilder.scala
- surface/jvm/src/main/scala/wvlet/surface/reflect/ReflectTypeUtil.scala
- surface/jvm/src/main/scala/wvlet/surface/reflect/TypeConverter.scala
Objects which can be build from Buffer is constructed with one element type like Array type. It is necessary to convert each element to Tuple2 type in case of Map type.
>  Use RuntimeSurface to convert Map type element

- docs/src/main/tut/docs/airframe-opts.md
When trying example code, I found class name typo.
> Fix airframe-opts doc typo Launguer to Launcher.

- airframe/shared/src/main/scala/wvlet/airframe/AirframeException.scala
- airframe/shared/src/main/scala/wvlet/airframe/AirframeSession.scala
- airframe/shared/src/test/scala/wvlet/airframe/DependencyTest.scala
Add a warning when some dependency cannot be instantiated. This often happens when the missing dependency (e.g., say `D`) is a pure trait (= no default constructor).
If you use `bind[D].toSingleton`, Airframe can generate code for instantiating `D`:
```scala
// Good
trait C {
val d = bind[D]   //  Macro generates session.getOrElse(surface.of[D], new D {})
}
trait D
```
But constructor injection has nowhere to use Scala macros to generate `new D{}`, so MISSING_DEPENDENCY error will be thrown:
```scala
// NG
// There is no chance to use Scala macros for generating new D {} 
case class C(d:D) {
}
newDesign.newSession.build[C] // <-- MISSING_DEPENDENCY for D <- C
```
So in this case `design.bind[D].toXXX` should be used to generate code `new D{}`
> Show the chain of missing dependencies upon MISSING_DEPENDENCY error

- airframe-jmx/README.md
- airframe-log/RELEASE_NOTES.md
- airframe-log/jvm/src/test/scala/wvlet/log/AsyncHandlerTest.scala
- airframe-msgpack/src/main/scala/wvlet/airframe/msgpack/spi/Buffer.scala
- airframe-msgpack/src/main/scala/wvlet/airframe/msgpack/spi/Code.scala
- airframe-opts/src/test/scala/wvlet/airframe/opts/LauncherTest.scala
- airframe-surface/jvm/src/main/scala/wvlet/surface/reflect/CName.scala
- build.sbt
- docs/src/main/tut/docs/airframe-config.md
- docs/src/main/tut/docs/airframe-jmx.md
- docs/src/main/tut/docs/comparison.md
- docs/src/main/tut/docs/internals.md
- docs/src/main/tut/docs/release-notes.md
This pull request fixes the typos in this repository. Although I am not a native English speaker, [misspell](https://github.com/client9/misspell) detected obvious mistakes for us. I've fixed them except for false positives.
```
$ misspell .
airframe-jmx/README.md:55:30: "adn" is a misspelling of "and"
airframe-log/RELEASE_NOTES.md:24:59: "avilable" is a misspelling of "available"
airframe-log/jvm/src/test/scala/wvlet/log/AsyncHandlerTest.scala:55:15: "Temporarly" is a misspelling of "Temporary"
airframe-msgpack/src/main/scala/wvlet/airframe/msgpack/spi/Code.scala:58:17: "extention" is a misspelling of "extension"
airframe-msgpack/src/main/scala/wvlet/airframe/msgpack/spi/Buffer.scala:70:67: "lenght" is a misspelling of "length"
airframe-opts/src/test/scala/wvlet/airframe/opts/LauncherTest. …
```
> Fix the several typos detected by github.com/client9/misspell

- airframe-json/.jvm/src/test/scala/wvlet/airframe/json/JSONScannerBenchmark.scala
- airframe-json/src/main/scala/wvlet/airframe/json/JSON.scala
- airframe-json/src/main/scala/wvlet/airframe/json/JSONParser.scala
- airframe-json/src/main/scala/wvlet/airframe/json/JSONScanner.scala
- airframe-json/src/main/scala/wvlet/airframe/json/JSONSource.scala
- airframe-json/src/main/scala/wvlet/airframe/json/JSONTraverser.scala
- airframe-json/src/test/scala/wvlet/airframe/json/SimpleJSONEventHandler.scala
- build.sbt
- Use tableswitch: https://www.scala-lang.org/api/2.12.1/scala/annotation/switch.html
- Suppress TypeProfile generation in JSONSource by supporting only Array buffer
- Use recursive parser (with tailrec optimization) 
- Faster parsing for simple strings which has no escape characters.
> airframe-json optimization

- airframe-metrics/jvm/src/test/scala/wvlet/airframe/metrics/TimeWindowTest.scala
- docs/src/main/tut/docs/airframe-metrics.md
Time window representation examples in airframe-metrics's documentation are wrong about 0 duration. I fixed documentation and added test to confirm the difference of 0[hdM] and 1[hdM].
> Update airframe-metrics document and test for 0 duration

- airframe-metrics/jvm/src/main/scala/wvlet/airframe/metrics/TimeUnit.scala
- airframe-metrics/jvm/src/main/scala/wvlet/airframe/metrics/TimeVector.scala
- airframe-metrics/jvm/src/main/scala/wvlet/airframe/metrics/TimeWindow.scala
- airframe-metrics/jvm/src/main/scala/wvlet/airframe/metrics/TimeWindowUnit.scala
- airframe-metrics/jvm/src/test/scala/wvlet/airframe/metrics/TimeWindowTest.scala
- docs/src/main/tut/docs/airframe-metrics.md
- There is no ChronoUnit.Quarter in JDK, so created ~TimeUnit~ TimeWindowUnit classes to use Quarter unit.
- The beginning of the quarter is January. But note that the definition of a quarter can be different depending on company culture.
> Support quarter (q) duration

- airframe-surface/jvm/src/main/scala/wvlet/surface/reflect/MethodCallBuilder.scala
`MethodCallBuilder` fail to use default value if argument name includes
capital letter. Therefore, airframe-opts's sub-command don't use default value
for such argument as follows.
```
scala> class SampleCommand() {
|   @command()
|   def sample(@option(prefix = "-a") aB: Int = 1) = {
|     println(aB)
|   }
| }
defined class SampleCommand
scala> val l = Launcher.of[SampleCommand]
l: wvlet.airframe.opts.Launcher = wvlet.airframe.opts.Launcher@544a71e6
scala> l.execute(Array("sample"))
0
```
It is because `ObjectBuilder` tries to find arguments with canonical name.
https://github.com/yajirobee/airframe/blob/305e71afb5bda93a961d75d93a035c90e8b13905/airframe-surface/jvm/src/main/scala/wvlet/surface/reflect/ObjectBuilder.scala#L201
> use canonical name for arguments of method surface on MethodCallBuilder

- .travis.yml
- airframe-jmx/src/main/scala/wvlet/airframe/jmx/JMXMBean.scala
- airframe-log/shared/src/main/scala/wvlet/log/Logger.scala
- airframe/.jvm/src/test/scala/wvlet/airframe/DesignSerializationTest.scala
- airframe/.jvm/src/test/scala/wvlet/airframe/ProviderSerializationTest.scala
- airframe/.jvm/src/test/scala/wvlet/airframe/SerializationTest.scala
- build.sbt
- docs/src/main/tut/docs/release-notes.md
Need to wait the updates of the following libraries:
-  scala.collection.generic.DefaultSerializationProxy https://travis-ci.org/wvlet/airframe/jobs/439978533
```
[error] /home/travis/build/wvlet/airframe/airframe-jmx/src/main/scala/wvlet/airframe/jmx/JMXMBean.scala:79:26: inferred type arguments [javax.management.JMX] do not conform to method getAnnotation's type parameter bounds [A <: java.lang.annotation.Annotation]
[error]     val description = cl.getAnnotation(classOf[JMX]) match {
```
> Upgrade to Scala 2.13.0-M5

- docs/src/main/tut/docs/index.md
In-train injection example at the web site doesn't work because `name` isn't given to `Database`.
> Fix in-trait injection example

- airframe-surface/js/src/main/scala/wvlet/airframe/surface/package.scala
- airframe-surface/jvm/src/main/scala/wvlet/airframe/surface/package.scala
- airframe-surface/shared/src/main/scala/wvlet/airframe/surface/CName.scala
- airframe-surface/shared/src/test/scala/wvlet/airframe/surface/CNameTest.scala
- Refactored existing code
- Not use `return`
- Avoid cast in `CName#equals()`
- Use `HashMap` instead of `WeakHashMap` in Scala.js
- Added name conversions from natural name
- `snakeCase`
- `dashCase`
- `upperCamelCase`
- `lowerCamelCase`
> Add name conversion functionallity to CName

- .codecov.yml
Having strict coverage check is good in general, but time-consuming at the same time. 
This PR will use 80% code coverage as a guideline of maintaining the code health.
> Set the code coverage test threshold to 80% overall, 5% diff coverage

- airframe-config/src/main/scala/wvlet/airframe/config/package.scala
- airframe-config/src/test/scala/wvlet/airframe/config/AirframeBootstrapTest.scala
Every time ConfigHolder is needed, it's necessary to initialize the session from the design for now. 
ConfigHolder can be obtained directly from the design without additional overhead.
> Get ConfigHolders directly from Design

- airframe-tablet/src/main/scala/wvlet/airframe/tablet/text/ArrayJSONCodec.scala
- airframe-tablet/src/test/scala/wvlet/airframe/tablet/text/ArrayJSONCodecTest.scala
JSON string can have array string [in the root level](https://www.json.org/). I added `ArrayJSONCodec` in order to provide the similar usability as `ObjectJSONCodec` for array JSON string.
```scala
val codec = ArrayJSONCodec.of[String]
val a = Array("a", "b")
// Encode
val json = codec.toJSON(a) // -> '["a", "b"]'
// Decode
val v = new MessageHolder
codec.fromJSON(json, v)
```
Supported primitive types
- `Short`
- `Int`
- `Long`
- `Char`
- `Float`
- `Double`
- `Boolean`
- `String`
> Add ArrayJSONCodec to parse JSON array string

- airframe-macros/src/main/scala/wvlet/airframe/AirframeMacros.scala
- airframe/src/test/scala/wvlet/airframe/DesignBuildTest.scala
It seems closure handling has changed after Scala 2.12 and local variables cannot be found inside the passed closure. #373
In Scala 2.11 there is no problem.
> #373: design.build[X] { ... } closure scope

- airframe-http/src/main/scala/wvlet/airframe/http/Router.scala
- airframe-http/src/test/scala/wvlet/airframe/http/ControllerExample.scala
- airframe-http/src/test/scala/wvlet/airframe/http/RouterTest.scala
The current implementation of airframe-http's router allows to define the parameter only at the last component of the path. This pull request allows more flexible http path routing like:
- `/:param/hoge`
- `/:param1/hoge/:param2`
See also #417
> airframe-http: Allow more flexible http path routing

- airframe-json/src/main/scala/wvlet/airframe/json/JSONScanner.scala
- airframe-json/src/test/scala/wvlet/airframe/json/JSONParserTest.scala
Parsing objects in array looks recursive and stack consuming.
```
[error]         at wvlet.airframe.json.JSONScanner.rscan(JSONScanner.scala:237)
[error]         at wvlet.airframe.json.JSONScanner.scanArray(JSONScanner.scala:190)
[error]         at wvlet.airframe.json.JSONScanner.rscan(JSONScanner.scala:235)
[error]         at wvlet.airframe.json.JSONScanner.scanObject(JSONScanner.scala:186)
[error]         at wvlet.airframe.json.JSONScanner.rscan(JSONScanner.scala:237)
```
> airframe-json: Parsing large array of objects throws StackOverflowError

- .travis.yml
- airframe-codec/.jvm/src/test/scala/wvlet/airframe/codec/JDBCCodecTest.scala
- sbt
It seems the community build is failing because of Serialization bug of Scala 2.13 collection library. 
- Vector is not serializable
This PR is for reproducing that bug, and finding a workaround.
> Use Scala 2.13.x + JDK11

- airframe-codec/.jvm/src/test/scala/wvlet/airframe/codec/JSONCodecTest.scala
- airframe-codec/src/main/scala/wvlet/airframe/codec/JSONCodec.scala
- airframe-json/src/main/scala/wvlet/airframe/json/JSON.scala
- airframe-json/src/main/scala/wvlet/airframe/json/JSONEventHandler.scala
- airframe-json/src/main/scala/wvlet/airframe/json/JSONScanner.scala
- airframe-json/src/test/scala/wvlet/airframe/json/JSONParserTest.scala
- airframe-json/src/test/scala/wvlet/airframe/json/JSONScannerTest.scala
Problem:
- Option[X] can be MessagePack Nil value. 
- Nil value can be represented as `null` in JSON
- Trying to parse this value causes a JSON parsing exception, because `null` is not JSON object nor JSON array.
- airframe-http should support returning Option[X] value
- Option[X] is difficult to represent in JSONObject because it's not clear whether the empty JSON object `{}` can be `Some(X(no parameter))` or `None`. 
- So returning JSON `null` should be acceptable for Option[X] type
- MessageCodec should be able to parse null JSON string as Option[X]
Solution:
- Add JSON.parseAny(json value string): JSONValue
> Add JSON.parseAny(json)

- build.sbt
Sonatype releases repo will redirect the access to Maven central, so we no longer need to use it
> Remove Sonatype releases resolver

- build.sbt
airframe-http doesn't need to depend on finatra-http. We can use finagle-http instead to avoid Guice 4.2.2 version conflict: 
https://github.com/twitter/finatra/pull/491
> Remove finatra dependency

- airframe-jmx/src/main/scala/wvlet/airframe/jmx/JMXMBean.scala
Currently, only first method of methods annotated with `@JMX` is registered as JMX attribute.
> Fix JMX methods extraction

- airframe-control/README.md
- airframe-control/src/main/scala/wvlet/airframe/control/Parallel.scala
- airframe-control/src/test/scala/wvlet/airframe/control/ParallelTest.scala
- build.sbt
Even though #473 has been reported, I haven't find any problems in `Parallel` implementation yet. To find problem easily I would like to add trace log and JMX monitoring to `Parallel`.
> Add trace logs and JMX monitoring to Parallel

- .travis.yml
- build.sbt
The only reason Airframe supports Scala 2.11 was Spark. Since Spark 2.4.2, it is built against Scala 2.12 by default, so we no longer need to maintain Scala 2.11 build.
> Remove Scala 2.11 support

- .travis.yml
- build.sbt
Spark 2.4.x is rolled back to Scala 2.11 because there are many Spark users who still need time to migrate to Scala 2.12. 
This PR will recover Scala 2.11 build only for master branch commits.
> Build for Scala 2.11 only at mater branch commits

- .travis.yml
An attempt to reduce the number of Travis builds
> Remove Scala 2.12 + openjdk11 build from Travis

- .travis.yml
- airframe-canvas/src/test/scala/wvlet/airframe/canvas/CanvasTest.scala
- airframe-codec/.jvm/src/test/scala/wvlet/airframe/codec/PrimitiveCodecTest.scala
- airframe-msgpack/src/test/scala/wvlet/airframe/msgpack/spi/RoundTripTest.scala
- airframe-msgpack/src/test/scala/wvlet/airframe/msgpack/spi/ValueTest.scala
- build.sbt
> Upgrade to Scala 2.13.0-RC2

- airframe-control/README.md
- airframe-control/src/main/scala/wvlet/airframe/control/ResultClass.scala
- airframe-control/src/main/scala/wvlet/airframe/control/Retry.scala
- examples/src/main/scala/wvlet/airframe/examples/control/Control_02_Jitter.scala
- examples/src/main/scala/wvlet/airframe/examples/control/Control_03_CustomRetry.scala
Add convenient methods to Retry, instead of moving to ResultClass.retryableFailure method
#522
> control: Add Retry.retryable/nonRetryableFailure method

- airframe-config/src/test/scala/wvlet/airframe/config/ConfigTest.scala
- airframe-log/jvm/src/test/scala/wvlet/log/io/IOUtilTest.scala
#517 
Fix symbol `'xxx` to `Symbol("xxx")`.
> Fix usage of symbol

- airframe-codec/src/main/scala/wvlet/airframe/codec/JSONCodec.scala
- airframe-fluentd/src/main/scala/wvlet/airframe/fluentd/FluentdLogger.scala
- airframe-fluentd/src/main/scala/wvlet/airframe/fluentd/MetricLogger.scala
- airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/FinagleClientTest.scala
- airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRecorder.scala
- airframe-http/src/test/scala/wvlet/airframe/http/RouterTest.scala
- airframe-jmx/src/main/scala/wvlet/airframe/jmx/JMXMBean.scala
- airframe-json/src/test/scala/wvlet/airframe/json/JSONScannerTest.scala
- airframe-launcher/src/test/scala/wvlet/airframe/launcher/LauncherTest.scala
- airframe-log/shared/src/test/scala/wvlet/log/WvletLog.scala
- airframe-msgpack-benchmark/src/main/scala/wvlet/airframe/benchmark/msgpack/MsgpackBenchmarkMain.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/SQLAnonymizer.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/parser/SQLInterpreter.scala
- airframe/src/main/scala/wvlet/airframe/LifeCycleManager.scala
- airframe/src/test/scala/wvlet/airframe/AirframeTest.scala
- examples/src/main/scala/wvlet/airframe/examples/di/DI_07_JSR250Annotation.scala
- examples/src/main/scala/wvlet/airframe/examples/di/DI_11_ProductionMode.scala
- examples/src/main/scala/wvlet/airframe/examples/di/DI_12_ReusingService.scala
- examples/src/main/scala/wvlet/airframe/examples/di/DI_20_BindSession.scala
- Master Branch v19.6 (https://github.com/wvlet/airframe/commit/61a0316e9d3bf07d3d71bc36fbd1ec70332d1fb1) 
```
grep -r "(s\"" * .scala |  grep -v "\$."  
grep: .scala: No such file or directory
airframe/src/test/scala/wvlet/airframe/AirframeTest.scala:    info(s"This should be built")
airframe/src/test/scala/wvlet/airframe/AirframeTest.scala:      warn(s"Running cyclic dependency check test")
airframe/src/test/scala/wvlet/airframe/AirframeTest.scala://      warn(s"Running cyclic dependency test: A->B->A")
airframe/src/test/scala/wvlet/airframe/AirframeTest.scala:      warn(s"Running missing dependency check")
airframe/src/main/scala/wvlet/airframe/LifeCycleManager.scala:      throw new IllegalStateException(s"LifeCycle is already starting") …
```
> remove unused string interpolations

- airframe-json/src/main/scala/wvlet/airframe/json/package.scala
- airframe-json/src/test/scala/wvlet/airframe/json/JSONTest.scala
Another `.value` method for JSON DSL added in #538 that allows getting a value of the first element of `Seq[JSONValue]`.
This is useful when we know that the json value has a single child element.
```scala
// before
val id = (jsonValue / "user" / "id")(0).value
// after
val id = (jsonValue / "user" / "id").value
```
> Seq[JSONValue].value

- airframe-codec/.jvm/src/test/scala/wvlet/airframe/codec/ObjectCodecTest.scala
- airframe-codec/src/main/scala/wvlet/airframe/codec/MessageCodec.scala
- airframe-fluentd/src/main/scala/wvlet/airframe/fluentd/MetricLogger.scala
Currently, MessageCodec serializes the value as array type as default even for ObjectCodec which is supporting `PackAsMapSupport`. It can cause a problem of the cooperability between td-agent and airframe-fluentd because td-agent expects the input record to be map type MessagePack. 
Since `TypedMetricLogger` in airframe-fluentd calls `toMsgPack`, the data is flushed as array type. But it cannot be read by td-agent or fluentd. 
```scala
class TypedMetricLogger[T <: TaggedMetric](fluentdClient: MetricLogger, codec: MessageCodec[T]) {
def emit(event: T): Unit = {
fluentdClient.emitMsgPack(event.metricTag, codec.toMsgPack(event))
}
}
```
As we do for `toJson`, `toMsgPack` can write the value as map type if the codec is `PackAsMapSupport`. 
Additionally, using object map type codec in …
> Use map type MessagePack for ObjectCodec

- airframe-json-benchmark/src/test/scala/wvlet/airframe/json/JSONBenchmark.scala
- airframe-json/src/main/scala/wvlet/airframe/json/JSONScanner.scala
Fix for uses same StringBuilder instances. It looks like the performance has improved slightly.
```
2019-07-13 22:24:11.843+0900  info [JSONBenchmark] -twitter.json        total:8.057 sec. , count:   10, avg:0.806 sec. , min:0.346 sec. , median:0.397 sec. , max:3.688 sec. 
-airframe             total:1.122 sec. , count:  100, avg:0.011 sec. , min:3.811 msec., median:5.813 msec., max:0.094 sec. 
-airframe scan        total:0.908 sec. , count:  100, avg:9.081 msec., min:2.160 msec., median:3.868 msec., max:0.066 sec. 
-circe                total:0.926 sec. , count:  100, avg:9.256 msec., min:1.600 msec., median:2.459 msec., max:0.416 sec. 
-jawn                 total:0.610 sec. , count:  100, avg:6.098 msec., min:1.596 msec., median:2.314 msec., max:0.109 sec. 
-json4s-jackson rk / …
```
> json performance tuning

- airframe-http/src/main/scala/wvlet/airframe/http/RouteMatcher.scala
- airframe-http/src/test/scala/wvlet/airframe/http/RouterTest.scala
Though the following requests are routed to the same action even if only `/v1/config/info` is available, the second request should be 404.
- http://localhost:8080/v1/config/info
- http://localhost:8080/v1/config/xxx/info
> Fix over routing in airframe-http

- airframe-log/jvm/src/main/scala/wvlet/log/LogEnv.scala
This is a switch to enable using airframe-log on GraalVM.
> fix: GraalVM support

- airframe-codec/src/main/scala/wvlet/airframe/codec/MessageCodec.scala
- airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleClient.scala
- airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/FinagleClientTest.scala
- airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/FinagleRouterTest.scala
- airframe-http/src/main/scala/wvlet/airframe/http/HttpClient.scala
- airframe-http/src/main/scala/wvlet/airframe/http/Route.scala
For passing GET request objects as URL query strings.
This will add two more convenient mappings:
- binding URL query strings (?p1=v1&p2=v2& ...) as method arguments
- binding URL query strings to a method object (ResourceRequest(p1, p2, ...))
> airframe-http-client: Add getResource for GET with query strings

- airframe-http-recorder/README.md
- airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRecordStore.scala
- airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRecorder.scala
- airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRecorderServer.scala
- airframe-http-recorder/src/test/scala/wvlet/airframe/http/recorder/HttpRecorderTest.scala
Added a new filter for replaying for known requests or recording for unknown requests.
> airframe-http-recorder: Add createRecorderProxy

- airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/HttpFilterTest.scala
- airframe-http/src/main/scala/wvlet/airframe/http/HttpFilter.scala
- airframe-http/src/main/scala/wvlet/airframe/http/Router.scala
- airframe-http/src/main/scala/wvlet/airframe/http/RouterMacros.scala
- Use a consistent syntax for Router.add[X] for both controller and filter
- Deprecate Router.filter[Filter] 
- Support chaining filters with Router.andThen[Filter]
> airframe-http: Support Router.add[Filter], andThen[Filter]

- airframe-http-recorder/README.md
- airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRecordStore.scala
- airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRecorder.scala
- airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRecorderServer.scala
- airframe-http-recorder/src/test/scala/wvlet/airframe/http/recorder/HttpRecorderTest.scala
@takezoe This PR enables combining real server responses + programmed responses, which will be useful for simulating server failures.
> airframe-http-recorder: Support custom recording 

- airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRecord.scala
- airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRecordStore.scala
- airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRecorder.scala
- airframe-http-recorder/src/test/scala/wvlet/airframe/http/recorder/HttpRecorderTest.scala
@takezoe This will be useful to record binary responses (e.g., from S3)
> airframe-http-recorder: Support binary requests and responses

- airspec/src/main/scala/wvlet/airframe/spec/runner/AirSpecLogger.scala
This PR improves the log display of AirSpec:
Using sbt's logger add `[info]` header for each line and wastes the space. And also it is not synchronized with other airframe-log messages, so it makes difficult to debug test cases.
> Use airframe-log for AirSpec logging

- airframe-log/jvm/src/main/scala/wvlet/log/LogEnv.scala
- airframe-log/jvm/src/test/scala/wvlet/log/LoggerJMXTest.scala
- build.sbt
- Avoid publishing airspec dependencies: airspec-log, core, deps.
> Make airspec an all-in-jar

- airspec/README.md
- airspec/src/main/scala/wvlet/airframe/spec/AirSpec.scala
- airspec/src/main/scala/wvlet/airframe/spec/runner/AirSpecLogger.scala
- airspec/src/main/scala/wvlet/airframe/spec/spi/AirSpecContext.scala
- examples/src/test/scala/wvlet/airframe/examples/airspec/AIrSpec_01_Basic.scala
- examples/src/test/scala/wvlet/airframe/examples/airspec/AirSpec_02_ReuseTests.scala
- examples/src/test/scala/wvlet/airframe/examples/airspec/AirSpec_03_DI.scala
- Fixing a bug that beforeAll can be called multiple times in forked tests.
- Add more examples
> airspec: Properly filter test methods of sub specs

- airframe/src/main/scala/wvlet/airframe/SessionBuilder.scala
- airspec/src/main/scala/wvlet/airspec/runner/AirSpecTaskRunner.scala
> airspec: #610: Avoid registering JVM shutdown hooks in airspec sessions

- airspec/src/main/scala/wvlet/airspec/AirSpec.scala
- airspec/src/main/scala/wvlet/airspec/package.scala
- airspec/src/main/scala/wvlet/airspec/runner/AirSpecLogger.scala
- airspec/src/main/scala/wvlet/airspec/runner/AirSpecRunner.scala
sbt detaches the classloader early while lazy initialization of AirSpecLogger is running
> airspec: #612: Fixes java.lang.ClassNotFoundException: scala.reflect.api.Trees

- .gitignore
- airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRecordStore.scala
- airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRecorder.scala
- airframe-http-recorder/src/test/scala/wvlet/airframe/http/recorder/HttpRecorderTest.scala
- And allow configuring in-memory recorders
- Use 1M default expiration range
This change is for not creating too many database files.
> airframe-http-recorder: Store records to .airframe/http folder

- airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleClient.scala
nginx proxy requires HOST header
> airframe-http-client: Add HOST header if missing

- airframe-codec/.jvm/src/test/scala/wvlet/airframe/codec/InnerClassCodecTest.scala
- airframe-codec/.jvm/src/test/scala/wvlet/airframe/codec/InnerClassFactoryTest.scala
- airframe-surface/js/src/main/scala/wvlet/airframe/surface/SurfaceFactory.scala
- airframe-surface/jvm/src/main/scala/wvlet/airframe/surface/SurfaceFactory.scala
- airframe-surface/jvm/src/main/scala/wvlet/airframe/surface/reflect/ReflectSurfaceFactory.scala
- airframe-surface/jvm/src/test/scala/wvlet/airframe/surface/InnerClassTest.scala
- airframe-surface/shared/src/main/scala/wvlet/airframe/surface/SurfaceMacros.scala
- airframe-tablet/src/main/scala/wvlet/airframe/tablet/obj/MapConverter.scala
- airframe-tablet/src/test/scala/wvlet/airframe/tablet/obj/MapConverterTest.scala
- airframe/src/test/scala/wvlet/airframe/PathDependentTypeTest.scala
This PR will support creating Surface.of[X] for inner classes by providing the context class instance when creating a surface. 
It would be possible to support Scala.js, but I didn't add this as we will not use this in Scala.js.
@takezoe, @smdmts
> airframe-surface: Support inner classes

- airframe/.jvm/src/main/scala/wvlet/airframe/JSR250LifeCycleExecutor.scala
- airframe/.jvm/src/test/scala/wvlet/airframe/CloseableHookPrecedenceTest.scala
- airframe/README.md
- airframe/src/main/scala/wvlet/airframe/AirframeSession.scala
- airframe/src/main/scala/wvlet/airframe/LifeCycleManager.scala
- airframe/src/test/scala/wvlet/airframe/CloseableShutdownHookTest.scala
- airspec/README.md
#644 
@takezoe @Lewuathe 
What I'm expecting for this review is getting questions around how Airframe DI's lifecycle hooks work in general, rather than checking the details of this PR. 
Related code:
- default life cycle handler chain: https://github.com/wvlet/airframe/blob/b20fd4e98ea51817477b2d49319d4922472b26e1/airframe/src/main/scala/wvlet/airframe/LifeCycleManager.scala#L181
- init life cycle hook is called when a new instance is injected:  https://github.com/wvlet/airframe/blob/b20fd4e98ea51817477b2d49319d4922472b26e1/airframe/src/main/scala/wvlet/airframe/AirframeSession.scala#L197
> airframe-di: Automatically register shutdown hooks for Closeable resources

- .travis.yml
- project/plugin.sbt
- scripts/publish.sh
Recently uploading artifacts to sonatype is significantly slower than before. To mitigate the issue, I've released sbt-sonatype 3.0 so that we can support parallel artifact upload:
https://github.com/xerial/sbt-sonatype#uploading-artifacts-in-parallel
And also sbt-sonatype 3.0 supports idempotent release by cleaning up previously uploaded artifacts. So if CI builds for tagged revisions fail, we can restart the failed jobs from the scratch. 
cc: @takezoe @Lewuathe @shimamoto
> Upgrade to sbt-sonatype 3.0

- airframe-control/src/main/scala/wvlet/airframe/control/MultipleExceptions.scala
- airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleServer.scala
- airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/FinagleServerFactoryTest.scala
- airframe-log/jvm/src/main/scala/wvlet/log/LogEnv.scala
- airframe-log/shared/src/main/scala/wvlet/log/Handler.scala
- airframe/src/main/scala/wvlet/airframe/AirframeSession.scala
- airspec/src/main/scala/wvlet/airspec/runner/AirSpecLogger.scala
- build.sbt
Change to automatically start FinagleServer when FinagleServerFactory is used.
And also, stopped using Session.register[FinagleServer] because if FinagleServer has an alias type, it will not be registered properly to the Session.
> airframe-http-finagle: Fix FinagleServer lifecycle

- airframe/src/main/scala/wvlet/airframe/AirframeSession.scala
- airframe/src/main/scala/wvlet/airframe/lifecycle/LifeCycleManager.scala
- airframe/src/test/scala/wvlet/airframe/lifecycle/ExtendedCloseableTest.scala
```scala
trait A extends Closeable
trait B 
bind[A].to[B]  // This registers two CoseHooks for A and B, but we need to register it only once for A (to call B.close())
```
> airframe-di: Fix duplicated Closeable hook registration

- airframe/src/main/scala/wvlet/airframe/Design.scala
Since `DesignOptions` is case class, the refactored code using  `copy` method is more concise.
> Refactor DesignOptions using copy method

- build.sbt
I got the following error when I tried to upgrade Airframe in my application.
```
java.lang.UnsupportedClassVersionError: wvlet/airframe/launcher/option has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```
Java code in the latest version of Airframe seems to have been compiled for Java11, but it would be better to keep Java8 compatibility.
> Add javacOptions to generate Java8 compatible binary

- airframe-jdbc/src/main/scala/wvlet/airframe/jdbc/ConnectionPool.scala
Because `ConnectionPoolFactory` is `AutoCloseable`.
> No need to shutdown ConnectionPoolFactory explicitly

- airframe-config/README.md
I think that `*default` should need an anchor in the example(`server.yaml)`.
> Fix airframe-config README

- airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/Finagle.scala
- airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleClient.scala
- airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRecordStore.scala
- airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRecorder.scala
- airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRecorderServer.scala
- airframe-http-recorder/src/test/scala/wvlet/airframe/http/recorder/HttpRecorderTest.scala
Resolves #772 
This PR also includes refactoring of builder patterns
After this PR, we should add a trigger to force expire http records (e.g., presto version string change) automatically or embed such version string to sessionName (as a best practice for creating a new session for each Presto version, etc.)
> airframe-http: Use no record expiration

- airframe/src/main/scala/wvlet/airframe/package.scala
Though this is just my opinion, runtime binding definition is confusing. For example, imagine that we have following in-trait injections,
```scala
val conn = bind[Connection]{ config: DatabaseConfig1 =>
config.newConnection()
}
val conn = bind[Connection]{ config: DatabaseConfig2 =>
config.newConnection()
}
```
Although both initializers take a different type of argument, only either one is actually called because `Connection` instance is created by the one called first and that instance is reused in other places.
Certainly, we can avoid this situation by giving another type to the component using tagged type or type alias. However, it's hard if we haven't grasped the entire codebase. Unintentional reusing an instance created by other binding definition can happen.
In order to avoid this …
> Deprecate runtime provider binding definitions

- airframe-codec/.jvm/src/test/scala/wvlet/airframe/codec/ValueCodecTest.scala
- airframe-codec/src/main/scala/wvlet/airframe/codec/PrimitiveCodec.scala
- airframe-codec/src/test/scala/wvlet/airframe/codec/PrimitiveCodecTest.scala
- airframe-msgpack/src/main/scala/wvlet/airframe/msgpack/spi/Value.scala
- airframe-msgpack/src/test/scala/wvlet/airframe/msgpack/spi/ValueTest.scala
This will close #634 
Previously airframe-codec encodes binary values as UTF-8 strings, but it may have caused data loss. This PR will use Base64 for representing binary values when generating JSON data. 
Similarly, when reading string values to Array[Byte], try decoding the strings as Base64 binaries. If it fails, it will fall back to using the raw string byte arrays of the string.   
This encoding is also used in Open API https://swagger.io/docs/specification/data-models/data-types/#string
cc: @takezoe @shimamoto
> airframe-codec: Support Base64 encoded binary

- airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleClient.scala
- airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleFilter.scala
- airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleResponseHandler.scala
- airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleServer.scala
- airframe-http/src/main/scala/wvlet/airframe/http/Router.scala
- airframe-http/src/main/scala/wvlet/airframe/http/router/Automaton.scala
- airframe-http/src/main/scala/wvlet/airframe/http/router/ControllerProvider.scala
- airframe-http/src/main/scala/wvlet/airframe/http/router/HttpRequestDispatcher.scala
- airframe-http/src/main/scala/wvlet/airframe/http/router/HttpRequestMapper.scala
- airframe-http/src/main/scala/wvlet/airframe/http/router/HttpResponseCodec.scala
- airframe-http/src/main/scala/wvlet/airframe/http/router/ResponseHandler.scala
- airframe-http/src/main/scala/wvlet/airframe/http/router/Route.scala
- airframe-http/src/main/scala/wvlet/airframe/http/router/RouteMatcher.scala
- airframe-http/src/main/scala/wvlet/airframe/http/router/RouterMacros.scala
- airframe-http/src/test/scala/wvlet/airframe/http/RouterTest.scala
This PR is just for moving internal code to router package. Router object, which is used for defining HTTP endpoints will remain in http package, so it should have no user-facing change.
> Move the internal routing code to wvlet.airframe.http.router package

- airframe-codec/.jvm/src/main/scala/wvlet/airframe/codec/JDBCCodec.scala
- airframe-codec/.jvm/src/main/scala/wvlet/airframe/codec/JavaStandardCodec.scala
- airframe-codec/.jvm/src/main/scala/wvlet/airframe/codec/JavaTimeCodec.scala
- airframe-codec/.jvm/src/main/scala/wvlet/airframe/codec/StringUnapplyCodec.scala
- airframe-codec/README.md
- airframe-codec/src/main/scala/wvlet/airframe/codec/CollectionCodec.scala
- airframe-codec/src/main/scala/wvlet/airframe/codec/JSONCodec.scala
- airframe-codec/src/main/scala/wvlet/airframe/codec/MessageCodec.scala
- airframe-codec/src/main/scala/wvlet/airframe/codec/MessageContext.scala
- airframe-codec/src/main/scala/wvlet/airframe/codec/MetricsCodec.scala
- airframe-codec/src/main/scala/wvlet/airframe/codec/ObjectCodec.scala
- airframe-codec/src/main/scala/wvlet/airframe/codec/PrimitiveCodec.scala
- airframe-codec/src/main/scala/wvlet/airframe/codec/ScalaStandardCodec.scala
- airframe-codec/src/main/scala/wvlet/airframe/codec/StandardCodec.scala
- airframe-codec/src/test/scala/wvlet/airframe/codec/CodecSpec.scala
- airframe-codec/src/test/scala/wvlet/airframe/codec/ObjectCodecTest.scala
- airframe-http/src/main/scala/wvlet/airframe/http/router/HttpResponseCodec.scala
- airframe-launcher/src/main/scala/wvlet/airframe/launcher/Launcher.scala
- airframe-launcher/src/main/scala/wvlet/airframe/launcher/StringTreeCodec.scala
This is a preparation for future extensibility (e.g., configuring codec behavior)
> airframe-codec: Rename MessageHolder -> MessageContext

- airframe/src/main/scala/wvlet/airframe/AirframeSession.scala
- airframe/src/main/scala/wvlet/airframe/Design.scala
- airframe/src/test/scala/wvlet/airframe/DisableImplicitInstanceCreationTest.scala
- airframe/src/test/scala/wvlet/airframe/DisableNoDefaultInstanceCreationTest.scala
Add a new option that disables implicit instance creation.
```scala
val d = Design.newDesign
.bind[Component].toSingleton
.noDefaultInstanceInjection
```
This allows us to prevent unexpected side effect caused by unintentional instance creation. Also, it helps us to remove unused components with confidence.
> Add option to disable implicit instance creation

- airframe-control/src/main/scala/wvlet/airframe/control/CircuitBreaker.scala
I forgot to add a setter method for `recoveryPolicy` in https://github.com/wvlet/airframe/pull/894.
> Add CircuitBreaker.withRecoveryPolicy()

- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/ApiRouterTest.scala
- airframe-http/src/main/scala/wvlet/airframe/http/Endpoint.java
- airframe-surface/jvm/src/main/scala/wvlet/airframe/surface/reflect/package.scala
- sbt-airframe/src/main/scala/wvlet/airframe/sbt/http/AirframeHttpPlugin.scala
- sbt-airframe/src/sbt-test/sbt-airframe/generate-client/server/src/main/scala/myapp/server/MyServer.scala
Follow-up of #878 to fill the case when the leaf class is a concrete class.
> airframe-http: Find Endpoint annotations in parent interfaces

- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/HttpClientGenerator.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/HttpClientIR.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/client/ScalaHttpClient.scala
- airframe-http/.jvm/src/test/scala/example/api/MyService.scala
- airframe-http/.jvm/src/test/scala/example/generic/GenericService.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/codegen/GenericServiceTest.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/codegen/HttpClientGeneratorTest.scala
- airframe-surface/jvm/src/main/scala/wvlet/airframe/surface/reflect/ReflectSurfaceFactory.scala
- airframe-surface/jvm/src/test/scala/wvlet/airframe/surface/reflect/NamedParameterTest.scala
- airframe-surface/shared/src/main/scala/wvlet/airframe/surface/SurfaceMacros.scala
- airframe-surface/shared/src/main/scala/wvlet/airframe/surface/Surfaces.scala
- airframe-surface/shared/src/test/scala/wvlet/airframe/surface/RecursiveHigherKindTypeTest.scala
- airframe-surface/shared/src/test/scala/wvlet/airframe/surface/SurfaceSpec.scala
- airframe-surface/shared/src/test/scala/wvlet/airframe/surface/SurfaceTest.scala
- airframe/src/test/scala/wvlet/airframe/BindLocalTest.scala
- sbt-airframe/src/test/scala/example/MyService.scala
This resolves #999 
- airframe-surface: support named parameters like F[_] named
> airframe-http: Support Future[_], F[_] return types in IDL

- airframe-http-okhttp/src/main/scala/wvlet/airframe/http/okhttp/OkHttpRetryInterceptor.scala
- build.sbt
I tried to upgrade Airframe version in td-scala-util and found airframe-http-okhttp was not available in Maven. So I tried to publish this module individually, and found this Scala 2.11 incompatibility issue.
> airframe-okhttp: Fix for Scala 2.11 and release process in build.sbt

- airframe/.jvm/src/test/scala/wvlet/airframe/BuildInFutureTest.scala
- docs/airframe.md
This test fails as follows. I believe that it had been working at some points of the previous versions of Airframe.
```
BuildInFutureTest:
2020-02-01 14:18:55.355+0900  info [LifeCycleManager] [session:43ed165b] Starting a new lifecycle ...  - (LifeCycleManager.scala:260)
2020-02-01 14:18:55.361+0900  info [LifeCycleManager] [session:43ed165b] ======== STARTED ========  - (LifeCycleManager.scala:264)
2020-02-01 14:18:55.402+0900  info [LifeCycleManager] [session:43ed165b] Stopping the lifecycle ...  - (LifeCycleManager.scala:268)
2020-02-01 14:18:55.406+0900  info [LifeCycleManager] [session:43ed165b] The lifecycle has stopped.  - (LifeCycleManager.scala:272)
- Building in Future causes MISSING_DEPENDENCY 61.89ms << error: [MISSING_DEPENDENCY] Binding for Int at BuildInFutureTest.scala:29 …
```
> Building components in Future causes strange errors

- airframe-control/.jvm/src/main/scala/wvlet/airframe/control/Parallel.scala
- airframe-control/.jvm/src/test/scala/wvlet/airframe/control/ParallelTest.scala
Allow to break execution in Parallel as follows:
```scala
val result = Parallel.run(Seq(1, 2, 3), parallelism = 1) { i =>
if (i == 2) {
Parallel.break
}
i
}
```
> Break execution in Parallel

- airframe-jdbc/src/main/scala/wvlet/airframe/jdbc/DbConfig.scala
- airframe-jdbc/src/test/scala/wvlet/airframe/jdbc/DbConfigTest.scala
The current `DBConfig` generates invalid jdbcUrl if the port number is specified, like `jdbc:presto://localhost:Some(8080)/public`.
> Fix port in jdbcUrl

- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/HttpClientGenerator.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/RouteScanner.scala
- airframe-http/.jvm/src/test/scala/example/rpc/RPCTestService.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/codegen/RPCClientGeneratorTest.scala
- airframe-surface/jvm/src/main/scala/wvlet/airframe/surface/reflect/ReflectSurfaceFactory.scala
- airframe-surface/jvm/src/main/scala/wvlet/airframe/surface/reflect/package.scala
- sbt-airframe/src/sbt-test/sbt-airframe/generate-client/build.sbt
- sbt-airframe/src/sbt-test/sbt-airframe/generate-client/server/src/main/scala/myapp/server/MyServer.scala
- sbt-airframe/src/sbt-test/sbt-airframe/generate-client/spi/src/main/scala/myapp/spi/MyRPC.scala
Do not scan classes and their companion objects when building Router
> sbt-airframe: Fixes #1034

- .github/workflows/release-js.yml
- .github/workflows/test.yml
- project/plugin.sbt
Now that Scala.js 1.0.x is widely available, and we already have migrated our internal projects to Scala.js 1.0.x, we no longer need to support Scala.js 0.6.x for future versions.
> Drop Scala.js 0.6.x support

- docs/airframe-jdbc.md
Use `newConnectionPool` instead of `apply`.
https://github.com/wvlet/airframe/blob/d2e9e05e8caf0bb07f7ef1120b6846691577b44e/airframe-jdbc/src/main/scala/wvlet/airframe/jdbc/ConnectionPoolFactory.scala#L42-L44
> Fix the document about airframe-jdbc

- airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/package.scala
- airframe-http-okhttp/src/main/scala/wvlet/airframe/http/okhttp/package.scala
- airframe-http/src/main/scala/wvlet/airframe/http/HttpMessage.scala
Add LazyByteArrayMessage so that we don't need to actually materialize HTTP request/response objects unless necessary. For example, okhttp, finagle response body is unnecessary to materialize to classify its request success or failure.
> airframe-http: Evaluate request/response body lazily

- airframe-http-rx/.js/src/main/scala/wvlet/airframe/http/rx/html/DOMRenderer.scala
- airframe-http-rx/.js/src/test/scala/wvlet/airframe/http/rx/html/HtmlRenderingTest.scala
This fixes an issue that entity refs (e.g., "&amp;", "&pm;") become invisible if they are inserted in the middle of text contents.
For example, with this fix, `&plusmn;` EntityRef("plusmn") can be shown properly:
> airframe-http-rx: Fix EntityRef rendering

- .github/workflows/release-js.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
actions/checkout@v2 does not pull tags, so sbt-dynver creates weird version numbers like `airframe-control_2.12-0.0.0-1-119ada28-SNAPSHOT.pom` https://github.com/wvlet/airframe/runs/674989481
Ref: https://github.com/actions/checkout#Fetch-all-tags
> Fetch all git tags for sbt-dynver

- airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleServer.scala
- airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/filter/HttpAccessLogFilter.scala
- airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/HttpAccessLogTest.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/router/Route.scala
- airframe-http/src/main/scala/wvlet/airframe/http/Http.scala
- airframe-http/src/main/scala/wvlet/airframe/http/HttpBackend.scala
- airframe-log/shared/src/main/scala/wvlet/log/LogFormat.scala
- airframe-log/shared/src/main/scala/wvlet/log/Logger.scala
- airframe-log/shared/src/test/scala/wvlet/log/LoggerTest.scala
This PR is for logging exceptions that happened inside airframe-http server implementation by using HttpAccessLogging feature added in #1073 
- airframe-http: Record exception and exception_message 
- airframe-log: Fix error log when the exception argument is null
- airframe-log: Add Logger.suppressWarnings(...)
> airframe-http: Report exception traces inside RPC/Endpoint methods

- airframe-http/src/main/scala/wvlet/airframe/http/HttpClientException.scala
When a server is not yet ready, FinagleClient will throw ChannelClosedException. This happens, for example, when launching Nginx inside a test suite, and trying to connect it using FinagleClient before Nginx is not yet started inside the container. We can wait until a docker container starts, but waiting the service startup inside the container needs extra wait. 
By adding this retry pattern, we can retry http requests to a docker container until the application inside the container actually starts.
> airframe-http: Retry on Finagle's ChannelClosedException

- airframe-codec/.jvm/src/main/scala/wvlet/airframe/codec/Compat.scala
- airframe-codec/.jvm/src/main/scala/wvlet/airframe/codec/JavaStandardCodec.scala
- airframe-codec/src/main/scala/wvlet/airframe/codec/EnumCodec.scala
- airframe-codec/src/main/scala/wvlet/airframe/codec/MessageCodecFinder.scala
- airframe-codec/src/test/scala/wvlet/airframe/codec/EnumCodecTest.scala
- airframe-surface/jvm/src/main/scala/wvlet/airframe/surface/reflect/ReflectSurfaceFactory.scala
- airframe-surface/jvm/src/main/scala/wvlet/airframe/surface/reflect/TypeConverter.scala
- airframe-surface/shared/src/main/scala/wvlet/airframe/surface/SurfaceMacros.scala
- airframe-surface/shared/src/main/scala/wvlet/airframe/surface/Surfaces.scala
- airframe-surface/shared/src/test/scala/wvlet/airframe/surface/EnumTest.scala
Support enum like classes with Surface and codec. This PR closes #1092
This support will be useful for defining RPC/Endpoint model classes with Enum-like case objects that can be shared between Scala JVM and Scala.js. 
cc: @takezoe @shimamoto
> airframe-surface, codec: #1092 Support Enum-like classes in Scala.js

- airframe-control/src/main/scala/wvlet/airframe/control/IO.scala
- airframe-http/.js/src/main/scala/wvlet/airframe/http/Compat.scala
- airframe-http/.js/src/main/scala/wvlet/airframe/http/js/JSHttpClient.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/Compat.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/client/DefaultHttpClientBackend.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/client/URLConnectionClient.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/client/URLConnectionClientBackend.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/client/URLConnectionClientTest.scala
- airframe-http/src/main/scala/wvlet/airframe/http/CompatApi.scala
- airframe-http/src/main/scala/wvlet/airframe/http/Http.scala
- airframe-http/src/main/scala/wvlet/airframe/http/HttpClientBackend.scala
- airframe-http/src/main/scala/wvlet/airframe/http/HttpClientConfig.scala
- airframe-http/src/main/scala/wvlet/airframe/http/HttpMessage.scala
- airframe-http/src/main/scala/wvlet/airframe/http/HttpMultiMap.scala
- docs/airframe-http.md
This PR is for adding a handy http client implementation based on java.net.URLConnection, which doesn't require extra dependencies.
If we can use jdk11, https://openjdk.java.net/groups/net/httpclient/intro.html seems better.
> airframe-http: #1131 Add a sync client using URLConnection 

- airframe-codec/src/main/scala/wvlet/airframe/codec/CollectionCodec.scala
- airframe-codec/src/main/scala/wvlet/airframe/codec/ScalaStandardCodec.scala
- airframe-codec/src/test/scala/wvlet/airframe/codec/CollectionCodecTest.scala
- airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/FinagleRouterTest.scala
- airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/HttpAccessLogTest.scala
- airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/HttpParamTest.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/HttpClientIR.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/client/ScalaHttpClient.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/router/HttpRequestDispatcher.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/router/HttpRequestMapper.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/router/Route.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/HttpRequestMapperTest.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/RouterTest.scala
- airframe-http/src/main/scala/wvlet/airframe/http/HttpClient.scala
- airframe-http/src/main/scala/wvlet/airframe/http/HttpContext.scala
- airframe-http/src/main/scala/wvlet/airframe/http/RPC.java
- airframe-msgpack/.jvm/src/main/scala/wvlet/airframe/msgpack/spi/Compat.scala
- airframe-msgpack/src/main/scala/wvlet/airframe/msgpack/spi/Value.scala
- airframe-msgpack/src/test/scala/wvlet/airframe/msgpack/spi/ValueTest.scala
- airframe-surface/shared/src/main/scala/wvlet/airframe/surface/Surface.scala
- sbt-airframe/src/sbt-test/sbt-airframe/generate-client/server/src/main/scala/myapp/server/MyServer.scala
- sbt-airframe/src/sbt-test/sbt-airframe/generate-client/spi/src/main/scala/myapp/spi/MyRPC.scala
- sbt-airframe/src/sbt-test/sbt-airframe/js-client/build.sbt
- sbt-airframe/src/sbt-test/sbt-airframe/js-client/spi/src/main/scala/myspp/spi/MyService.scala
> airframe-http: #1100 Support unary and n-ary functions in RPC 

- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/Router.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/RouteScanner.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/RPCTest.scala
Because of the complexity of mapping RPC functions to HTTP endpoints, we should avoid using method overload (e.g., def m(p1), def m(p1, p2,...)). The current behavior is IllegalArgumentException is thrown when Router is used for building HTTP filters.
This PR adds Router.verifyRoutes so that we can manually find the presence of method overload early.
> airframe-http: #1128 Add Router.verifyRoutes to check duplicated endpoints

- airframe-http-rx/src/main/scala/wvlet/airframe/http/rx/Rx.scala
- airframe-http-rx/src/test/scala/wvlet/airframe/http/rx/RxTest.scala
This is useful when we need to force rewrite RxElement even when there is no data change.
> airframe-http-rx: #1117 Add RxVar.forceSet and forceUpdate

- airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleClient.scala
- airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/FinagleClientTest.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/router/HttpResponseCodec.scala
- airframe-surface/jvm/src/main/scala/wvlet/airframe/surface/reflect/ReflectSurfaceFactory.scala
- examples/src/main/scala/wvlet/airframe/examples/http/Http_02_ObjectMapping.scala
- examples/src/main/scala/wvlet/airframe/examples/http/Http_03_Client.scala
> airframe-http: Various client fixes

- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/Router.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/HttpClientIR.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/router/HttpRequestMapper.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/router/Route.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/HttpRequestMapperTest.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/RPCTest.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/RouterTest.scala
This PR will force using parameter names as keys of RPC call request body. 
For example, if the rpc method is `def f(p1:Int, p2:ComplexObj)`, the request body always needs to have param name -> param value structure:
```
{"p1":1, "p2":{..}}
```
- This will fix unexpected RPC mapping reported in #1129 and will make the request body generation protocol more consistent. 
- sbt-airframe automatically generates such request body, so no client code change will be required. Just need to regenerate RPC ServiceClient with `airframeHttpReload` command. 
- This PR indicates that if you modify RPC method argument names, it will change the RPC request body structure too. So when designing public APIs with airframe-rpc, you need to be careful about the parameter names and their changes. This will be a …
> airframe-http: #1129 Deprecate no-key unary mapping for RPC

- scripts/release.rb
This PR is for creating a link to the release note page for each git tag commit, instead of copying the detailed release descriptions 
Currently, git tag page is a bit messy because Markdown format is not recognized by GitHub https://github.com/wvlet/airframe/releases/tag/v20.6.1
> Use a link to the release note URL for git tag annotaiton

- airframe-codec/.jvm/src/test/scala/wvlet/airframe/codec/MessageCodecTest.scala
- airframe-codec/src/main/scala/wvlet/airframe/codec/LazyCodec.scala
- airframe-codec/src/main/scala/wvlet/airframe/codec/MessageCodec.scala
- airframe-codec/src/main/scala/wvlet/airframe/codec/MessageCodecException.scala
- airframe-codec/src/main/scala/wvlet/airframe/codec/MessageCodecFactory.scala
- airframe-codec/src/main/scala/wvlet/airframe/codec/MessageCodecFinder.scala
- airframe-codec/src/main/scala/wvlet/airframe/codec/PrimitiveCodec.scala
- airframe-codec/src/main/scala/wvlet/airframe/codec/ScalaStandardCodec.scala
- airframe-codec/src/main/scala/wvlet/airframe/codec/StandardCodec.scala
- airframe-codec/src/main/scala/wvlet/airframe/codec/ThrowableCodec.scala
- airframe-codec/src/test/scala/wvlet/airframe/codec/ObjectCodecTest.scala
- airframe-codec/src/test/scala/wvlet/airframe/codec/PrimitiveCodecTest.scala
- airframe-codec/src/test/scala/wvlet/airframe/codec/ScalaStandardCodecTest.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/router/Route.scala
- airframe-msgpack/src/main/scala/wvlet/airframe/msgpack/spi/Unpacker.scala
- Support Either[Left, Right] type in airframe-codec. It uses Array(left, right) representation. This will support returning Either[Throwable, A] type in airframe-http RPC interfaces. If we use a special exception class like Either[CustomException, A], we can inject a custom exception codec to MessageCodecFactory. 
- For encoding/decoding Either[Throwable, A], added GenericException class, which can report exception class name, message, stack traces, and the cause in details. 
- This will produce well-formatted JSON output when recording Exception class. The previous version was using a special array encoding, which might be difficult to parse. 
- A reason we do not deserialize the original Exception type is for avoiding Gadget attack (see an example in jackson …
> airframe-codec: Support Either and Throwable class serde 

- airframe-http-okhttp/src/test/scala/wvlet/airframe/http/okhttp/OkHttpClientTest.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/HttpClientTest.scala
- airframe-http/src/main/scala/wvlet/airframe/http/HttpClientException.scala
Closes #1168 
Add the following exceptions as retryable failures.
- java.net.SocketTimeoutException
- java.net.SocketException and the message is "Socket closed"
> Add SocketTimeoutException as a retryable failure

- airframe-http-okhttp/src/main/scala/wvlet/airframe/http/okhttp/OkHttpClient.scala
According to OkHttp document, we don't need to shutdown OkHttp explicitly.
https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/#shutdown-isnt-necessary
However, particularly, in CLI applications, because OkHttp threads remain (during max-idle period?) the process doesn't exit even after execution without explicit `System.exit(0)` call. It would better to shutdown explicitly in lifecycle hook.
> Shutdown OkHttpClient explicitly

- .github/workflows/test.yml
- build.sbt
- https://github.com/scala/scala/releases/tag/v2.12.12
- https://github.com/scala/scala/releases/tag/v2.13.3
These Scala versions added `-Xasync` option, so that scala-async can be efficiently implemented by using the compile-time information. The previous version of scala-async was a macro-based implementation, which was slow and incomplete. 
Related:
- scala-async 1.0.0-M1 https://github.com/scala/scala-async/releases/tag/v1.0.0-M1, which requires -Xasync option. 1.0.0 will be released soon
scala-async will support Scala.js too. This would be useful for writing Future-based async code instead of writing chains of Futures (e.g., Conductor's Future-based operation code will benefit from scala-async). I think reading this SIP https://docs.scala-lang.org/sips/async.html is good enough to …
> Upgrade to Scala 2.12.12, 2.13.3

- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/HttpClientIR.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/client/GrpcClient.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/client/ScalaHttpClient.scala
- airframe-http/.jvm/src/test/scala/example/grpc/Greeter.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/codegen/GrpcClientGeneratorTest.scala
- docs/airframe-rpc.md
- sbt-airframe/src/sbt-test/sbt-airframe/grpc/build.sbt
- sbt-airframe/src/sbt-test/sbt-airframe/grpc/server/src/test/scala/example/api/GreeterApiTest.scala
Reorganized the generated gRPC client code to have a room for adding both sync and async client within the same class.
From this RPC interface definition:
```scala
package example.grpc
import wvlet.airframe.http.RPC
@RPC
trait Greeter {
def sayHello(message: String): String
}
```
This PR generates the following code:
```scala
/**
* === DO NOT EDIT THIS FILE ===
* This code is generated by sbt-airframe plugin.
*/
package example.grpc
import wvlet.airframe.http._
import scala.collection.immutable.Map
object ServiceGrpcClient {
import wvlet.airframe.msgpack.spi.MsgPack
import wvlet.airframe.codec.{MessageCodec, MessageCodecFactory}
import wvlet.airframe.http.grpc.GrpcServiceBuilder.{RPCRequestMarshaller, RPCResponseMarshaller}
private def newDescriptorBuilder(fullMethodName:String) : …
```
> airframe-grpc: Generate both sync and async clients inside the same class

- airframe-http-rx/src/main/scala/wvlet/airframe/http/rx/Rx.scala
- airframe-http-rx/src/main/scala/wvlet/airframe/http/rx/RxOption.scala
- airframe-http-rx/src/main/scala/wvlet/airframe/http/rx/RxVar.scala
- airframe-http-rx/src/test/scala/wvlet/airframe/http/rx/RxOptionTest.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/codegen/GrpcClientGeneratorTest.scala
This is for simplifying Rx[Option[A]] handling. Currently, we need to nest multiple map calls:
```scala
val a = Rx.variable(Some("hello")) 
a.map { opt =>
opt.map { x => div(s"message: ${x}") }
} // Rx[Option[RxElement]]
```
This code will be simpler like:
```scala
val a: RxOptionVar[A] = Rx.optionVariable(Some("hello"))
a.map { x => div(s" message: ${x}") } // Rx[Option[RxElement]]
a := Some("new value")
```
This PR also supports Rx[A].toOption if A is Option[_] type 
This also closes #1200
> airframe-rx: Add RxOption[A] 

- airframe-http-okhttp/src/main/scala/wvlet/airframe/http/okhttp/OkHttpRetryInterceptor.scala
okhttp has modeled responses to be one-shot. They expect us to stream the response, decode it from JSON or another format, and use the result as a model object. This PR is to replace the streaming one with the in-memory one so that we can pass the response along, which is one of the options.
How about this solution?
Closes #1212
> Replace a body's source with a byte array in memory

- airframe-http-rx/.js/src/main/scala/wvlet/airframe/http/rx/html/DOMRenderer.scala
- airframe-http/src/main/scala/wvlet/airframe/http/rx/Rx.scala
- airframe-http/src/main/scala/wvlet/airframe/http/rx/RxEvent.scala
- airframe-http/src/main/scala/wvlet/airframe/http/rx/RxRunner.scala
- airframe-http/src/test/scala/wvlet/airframe/http/rx/BackPropagationTest.scala
- airframe-http/src/test/scala/wvlet/airframe/http/rx/RxTest.scala
This change will be necessary for supporting gRPC streaming #1234 
In this PR, Rx values will be represented with three states: OnNext(v), OnError(Throwable), and OnCompletion. Especially OnCompletion event is important to implement Rx.lastOption, Rx.concat, Rx.sequence. Without OnCompletion event, we don't know the end of stream (lastOption), so we can't concatenate two or more streams. 
With this change, Rx can be used as a reactive programming interface http://reactivex.io/
> airframe-http-rx: Represent Rx values with OnNext, OnError, and OnCompletion

- airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/GrpcClientCalls.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/client/GrpcClient.scala
- docs/airframe-rpc.md
- sbt-airframe/src/sbt-test/sbt-airframe/grpc/server/src/test/scala/example/api/GreeterApiTest.scala
While grpc sync client uses Rx[X], async client supports StreamObserver based streaming
> airframe-grpc: Add async grpc client for streaming

- .gitignore
- airframe-benchmark/src/main/scala/wvlet/airframe/benchmark/http/Greeter.scala
- airframe-benchmark/src/main/scala/wvlet/airframe/benchmark/http/HttpBenchmark.scala
- airframe-benchmark/src/main/scala/wvlet/airframe/benchmark/http/ServiceAsyncClient.scala
- airframe-benchmark/src/main/scala/wvlet/airframe/benchmark/http/ServiceGrpc.scala
- airframe-benchmark/src/main/scala/wvlet/airframe/benchmark/http/ServiceSyncClient.scala
- airframe-benchmark/src/test/scala/wvlet/airframe/benchmark/BenchmarkMainTest.scala
- build.sbt
Added a simple benchmark to see the performance of gRPC compared to Finagle:
```
> benchmark/pack
$ ./airframe-benchmark/target/pack/bin/airframe-benchmark bench -mt 5s http
Benchmark              Mode  Cnt     Score      Error  Units
FinagleBenchmark.rpc  thrpt   10  3780.651 ± 2274.439  ops/s
GrpcBenchmark.rpc     thrpt   10  6665.655 ± 2034.274  ops/s
```
Generally, gRPC seems 1.5 ~ 2x faster than Finagle. 
Added async RPC call results as well:
```
Benchmark                   Mode  Cnt      Score      Error  Units
FinagleBenchmark.rpcAsync  thrpt   10  12540.307 ± 3885.182  ops/s
FinagleBenchmark.rpcSync   thrpt   10   4378.924 ± 1238.384  ops/s
GrpcBenchmark.rpcAsync     thrpt   10  35829.839 ± 3067.464  ops/s
GrpcBenchmark.rpcSync      thrpt   10   6355.409 ± 1586.169  ops/s
```` …
> Add a simple finagle/grpc benchmark

- .github/workflows/package-test.yml
- build.sbt
- To resolve protobuf scaladoc generation errors
> internal: Exclude airframe-benchmark from artifacts

- build.sbt
- examples/rpc-examples/hello-rpc/build.sbt
- examples/rpc-examples/hello-rpc/project/build.properties
- project/build.properties
- project/plugin.sbt
- sbt
- Upgrade to sbt 1.4.0
- Enable the build-in dependency tree plugin (We can use dependencyTree command)
- Tested build pipelining https://github.com/sbt/sbt/pull/5703 
, but observed many compilation failures especially around macro / JVM projects. Disabled this feature for now (this behavior is the default anyway)
> internal: Upgrade to sbt 1.4.0

- airframe-json/src/main/scala/wvlet/airframe/json/JSON.scala
- airframe-json/src/test/scala/wvlet/airframe/json/JSONTest.scala
Before:
```json
"empty_array": [
],
"empty_object": {
}
```
After:
```json
"empty_array": [],
"empty_object": {}
```
> Improve empty JSON array and object formatting

- .github/workflows/release-js.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlan.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/parser/SQLInterpreter.scala
- build.sbt
- We no longer need to maintain Spark 2.4.x with Scala 2.11 as Spark 3.0.x is stable to use
- This PR drops Scala 2.11 configurations and merges project settings for Scala 2.12 and Scala 2.13 for simplicity
- Added minor fixes for passing compilation with Scala 2.13
> Scala 2.11 deprecation

- airframe-http/src/main/scala/wvlet/airframe/http/HttpBackend.scala
Like FinagleServer.defaultErrorFilter, I sometimes want to rescue specific exceptions in an own Filter but to record them in an access log. The exceptions rescued convert into a new Future.value, meaning no exceptions are recorded by HttpAccessLogFilter. To record them, this PR is to add a method to set an exception.
> Add setThreadLocal method for the pre-defined key TLS_KEY_SERVER_EXCEPTION

- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/HttpClientIR.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/client/GrpcClientGenerator.scala
Map.empty cannot be casted to Map[String, Any] in Scala 2.13
```
[error]  found   : scala.collection.immutable.Map[Nothing,Nothing]
[error]  required: scala.collection.immutable.Map[String,Any]
[error] Note: Nothing <: String, but trait Map is invariant in type K.
[error] You may wish to investigate a wildcard type such as `_ <: String`. (SLS 3.2.10)
[error]              codec.toMsgPack(__m),
```
> sbt-airframe: Fix code gRPC client generator for Scala 2.13

- .github/workflows/codecov.yml
- .github/workflows/doc.yml
- .github/workflows/package-test.yml
- .github/workflows/release-js.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- .github/workflows/test.yml
- build.sbt
Without using cache, the performance of GitHub Actions is reasonably fast. We can remove cache configuration to simplify the CI scripts.
> Remove cache from CI

- airframe/src/main/scala/wvlet/airframe/AirframeSession.scala
- airframe/src/test/scala/wvlet/airframe/ConstructorInjectionTest.scala
- airframe/src/test/scala/wvlet/airframe/DefaultValueTest.scala
This is a corner case bug fix when no default value is present for the constructor parameters.
> airframe-di: #586 Fixes constructor injection to use Singleton 

- build.sbt
javax-annotation (PreDetroy, PostConstruct) is unneceassary for airframe-surface. Moved its dependency to airframe-di.
> Cleanup unnecessary dependencies

- airframe-rx/src/main/scala/wvlet/airframe/rx/Rx.scala
- airframe-rx/src/test/scala/wvlet/airframe/rx/RxTest.scala
This PR adds a handy method for calling RPC that returns Future respones while rendering RxElements. cc: @shimamoto @takezoe
> airframe-rx: #1505 Add Rx.andThen(Future[X]) and Rx.future[X]

- airframe-rx/src/main/scala/wvlet/airframe/rx/Rx.scala
- airframe-rx/src/main/scala/wvlet/airframe/rx/RxRunner.scala
- airframe-rx/src/test/scala/wvlet/airframe/rx/RxTest.scala
This PR will add a handy method for caching the last event. 
This will simplify the code that needs to read RPC results periodically while reusing the last result when re-rendering the page. For example, we can write a page listing the remote worker nodes like this: 
```scala
private val nodeList = Rx.intervalMillis(1000).andThen(i => (rpc call to get a node list)).cache
def render = nodeList.map { list =>
... // If the cached data is available, it will be rendered quickly
}
// Rx.intervalMillis(1000) will stop properly when this DOM is unmounted
// via Rx operator update (e.g., Rx.variable.update ...)
```
@shimamoto Could your review this new operator? cc: @takezoe
> airframe-rx: Add Rx.cache

- airframe-codec/src/main/scala/wvlet/airframe/codec/MessageCodecFactory.scala
- airframe-control/src/main/scala/wvlet/airframe/control/CircuitBreaker.scala
- airframe-control/src/main/scala/wvlet/airframe/control/HealthCheckPolicy.scala
- airframe-control/src/test/scala/wvlet/airframe/control/CircuitBreakerTest.scala
- airframe-http/.js/src/main/scala/wvlet/airframe/http/js/JSHttpClient.scala
This is for #874. Web browsers can be often disconnected from the server. Having a circuit breaker should be the default behavior to avoid accumulating too many error logs in the browser.
> airframe-http: Add a default CircuitBreaker for js HTTP client

- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/openapi/OpenAPIGenerator.scala
- airframe-http/.jvm/src/test/scala/example/openapi/OpenAPIExample.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/openapi/OpenAPITest.scala
- build.sbt
Currently,  airframe-http doesn't properly generate an openapi document for endpoints supporting multiple methods.
> Properly generate an openapi document for endpoints supporting multiple methods

- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/router/Automaton.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/router/RouteMatcher.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/RouterTest.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/example/ControllerExample.scala
The problem was intermediate nodes were wrongly merged when building Automaton 
```
[OK]
v1 -> hello -> world (match)
v2 -> hello -> world (match) 
[Bug] 
v1 -> hello -> world (match)
v2 -/       \- world (match)
```
To solve this, added path prefixes to automaton nodes so that nodes belonging to different path prefixes will not be merged:
```
[With this PR]
v1 -> v1/hello -> v1/hello/world (match)
v2 -> v2/hello -> v2/hello/world (match)
```
> airframe-http: Fixes #1546 by adding path prefixes to disambiguate NFA nodes

- docs/airframe-codec.md
- docs/index.md
- add missing args to  MessageCodec#toJson and MessageCodec#toMsgPack methods in doc.
> Add missing args in airframe-codec docs

- airframe-http/.js/src/main/scala/wvlet/airframe/http/js/JSHttpClient.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/client/ScalaHttpClientGenerator.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/codegen/HttpClientGeneratorTest.scala
- airframe-rx/src/main/scala/wvlet/airframe/rx/Rx.scala
- docs/airframe-rpc.md
- sbt-airframe/src/sbt-test/sbt-airframe/js-client/client/src/main/scala/myspp/client/Main.scala
With this PR, sbt-airframe will generate an RPC client (ServcieJSClientRx) for Scala.js that returns Rx[X] return type, instead of Future[X].
This client will simplify RPC calls from Scala.js like this:
```scala
val rpcClient = bind[ServiceJSClientRx]
rpcClient.ServiceApi.apiMethod(...).map { x =>
div(s"result: ${x}")
}
```
Previously, we always needed to wrap Future with Rx:
```scala
val jsClient = bind[ServiceJSClient]
// We always need to import ExecutionContext for Scala.js
implicit val queue = scala.scalajs.concurrent.JSExecutionContext.queue
Rx.future(jsClient.ServiceApi.apiMethod(...)).map { x =>
div(s"result: ${x}")
}
```
cc: @shimamoto @takezoe
> sbt-airframe: Generate ServiceJSClientRx for Scala.js + RPC + Rx

- airframe-rx/src/main/scala/wvlet/airframe/rx/Rx.scala
- airframe-rx/src/test/scala/wvlet/airframe/rx/RxTest.scala
http://reactivex.io/documentation/operators/startwith.html
We can use this operator to render the loading state while waiting for RPC responses:
```scala
rpcCall.map( x => div(...))
.startWith(div("loading ..."))
// This is equivalent to
Rx.concat(Rx.single(div("loading ...")), rpcCall.map(x => div(...)) 
```
> airframe-rx: Add Rx.startWith

- airframe-rx/src/main/scala/wvlet/airframe/rx/Rx.scala
- airframe-rx/src/main/scala/wvlet/airframe/rx/RxOption.scala
- airframe-rx/src/test/scala/wvlet/airframe/rx/RxCacheTest.scala
I've found it's necessary to implement components that have some public methods referencing Rx data:
```scala
class Selector extends RxElement { 
private val list = getList.map(x => ...).cache 
def selected = list.getCurrent.map(lst => lst(selectedIndex))
}
```
> airframe-rx: Add Rx.cache.getCurrent

- airframe-benchmark/src/main/scala/wvlet/airframe/benchmark/ulid/ULIDBenchmark.scala
- airframe-benchmark/src/test/scala/wvlet/airframe/benchmark/BenchmarkMainTest.scala
- airframe-ulid/.js/src/main/scala/wvlet/airframe/ulid/compat.scala
- airframe-ulid/.jvm/src/main/scala/wvlet/airframe/ulid/compat.scala
- airframe-ulid/.jvm/src/test/scala/wvlet/airframe/ulid/ULIDCalendarTest.scala
- airframe-ulid/src/main/scala/wvlet/airframe/ulid/CrockfordBase32.scala
- airframe-ulid/src/main/scala/wvlet/airframe/ulid/ULID.scala
- airframe-ulid/src/test/scala/wvlet/airframe/ulid/CrockfordBase32Test.scala
- airframe-ulid/src/test/scala/wvlet/airframe/ulid/ULIDTest.scala
- build.sbt
- airframe-ulid is now a single module without any dependency #1585 
- Split CrockfordBase32 encoder as a class
- Optimize Base32 encoding/decoding with bit-shift operations
- Add various ULID factories
- Use SecureRandom by default. Use standard Random for Scala.js
- Generate 80-bit random values with Array[Byte] for improving the performance
- Support generating monotonically increasing ULID by default. This has accelerated the performance 2x ~ 3x by eliminating random value generation within the same millisecond
Benchmark results:
```
$ ./sbt
> benchmark/run bench ulid
Benchmark                    Mode  Cnt        Score        Error  Units
Airframe.generateMonotonic  thrpt   10  5514410.915 ± 534378.141  ops/s
Chatwork.generate           thrpt   10  2063919.975 ±  62641.190  ops/s …
```
> airframe-ulid: Performance optimization

- airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRecordStore.scala
- airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRecorderServer.scala
- airframe-http-recorder/src/test/scala/wvlet/airframe/http/recorder/HttpRecorderTest.scala
Add methods to dump `HttpRecordStore` as JSON and YAML. These methods will offer the visibility of recorded data and will help to debug test cases that use http-recorder.
> http-recorder: Add methods to dump HttpRecordStore as JSON and YAML

- airframe-surface/.jvm/src/main/scala-2/wvlet/airframe/surface/reflect/ReflectSurfaceFactory.scala
- airframe-surface/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/EnumTest.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/RecursiveSurfaceTest.scala
Resolve Surface for enum-like classes that have unapply(s:String): Option[A] method
> airframe-surface: Support EnumSurface for Scala 3

- airframe-ulid/src/main/scala/wvlet/airframe/ulid/ULID.scala
We've noticed the ULID generation taking up to 10s due to threading issues on the default `SecureRandom` instance. 
When using a non-secure `Random` instance, it works fine. 
As far as I understand, as long as we simply use the generated ULIDs as an internal id that is only used for uniqueness and sorting, it is fine to use the non-secure `Random`
> Make ULIDGenerator class public allowing Random injection

- airframe-benchmark/README.md
- airframe-benchmark/src/main/scala/wvlet/airframe/benchmark/ulid/ULIDBenchmark.scala
- airframe-ulid/src/main/scala/wvlet/airframe/ulid/ULID.scala
- airframe-ulid/src/test/scala/wvlet/airframe/ulid/ULIDTest.scala
Add non-secure Random-based ULID generator. 
Although, it's slightly faster than the default one, the overhead of generating monotonically increasing ULIDs, which uses the synchronization block, seems the bottleneck because using a single thread for generating ULID was much faster (12M ULIDs/sec.)
JMH Benchamark with 4 threads (with M1 Mac mini):
```
sbt> benchmark/run  bench ulid
Benchmark                             Mode  Cnt        Score        Error  Units
Airframe.generateMonotonic           thrpt   10  7456080.727 ±  64518.094  ops/s
AirframeNonSecure.generateMonotonic  thrpt   10  7544899.339 ±  26569.171  ops/s
Chatwork.generate                    thrpt   10  2685346.054 ±   9523.277  ops/s
Chatwork.generateMonotonic           thrpt   10  6409200.174 ± 156695.839  ops/s …
```
> airframe-ulid: Support non-secure random ULID generator

- .github/workflows/sbt-integration.yml
- scripts/dynver.sh
sbt-airframe is now a separate project https://github.com/wvlet/sbt-airframe. This PR will check generated RPC clients with this version of Airframe will work as expected.
> Add sbt-airframe integration test

- airframe-log/.jvm/src/main/scala/wvlet/log/LogEnv.scala
This is for compatibility with Trino. Adding an option to redirect log messages to the current logger can be another option.
> airframe-log: Create stderr explicitly

- airframe-http-codegen/src/main/scala/wvlet/airframe/http/codegen/ClassScanner.scala
- airframe-http-codegen/src/test/scala/wvlet/airframe/http/codegen/ClassScannerTest.scala
> airframe-http: Properly decode URL-encoded paths in ClassScanner

- airframe-control/.jvm/src/main/scala/wvlet/airframe/control/CommandLineTokenizer.scala
- build.sbt
Implementing the tokenizer without using scala-parser-combinator.
> airframe-control: Remove scala-parser-combinators dependency

- airframe-ulid/src/test/scala/wvlet/airframe/ulid/ULIDTest.scala
This is a workaround for the case that System.currentTimeMillis() is rollebacked
> airframel-ulid: Remove unstable ULID tests

- build.sbt
Scala.js 1.8.0 deprecates `ExecutionContext.global` https://www.scala-js.org/news/2021/12/10/announcing-scalajs-1.8.0/
> airframe-rx: Add MacroTask Executor as a dependency

- .github/workflows/release-airspec.yml
- .github/workflows/sbt-integration.yml
- .github/workflows/snapshot.yml
- .github/workflows/test.yml
- .scala-steward.conf
- airspec/.scalafmt.conf
- airspec/README.md
- airspec/build.sbt
- airspec/project/build.properties
- airspec/project/plugin.sbt
- airspec/src/main/scala-3/wvlet/airspec/AirSpecSpiCompat.scala
- airspec/src/test/scala/examples/F0Spec.scala
- build.sbt
This is for simplifying build configuration as IntelliJ IDEA cannot properly scan source code files referenced multiple times in the same projects. 
```scala
cd airspec
sbt +airspecJVM/publishLocal
```
> Build AirSpec using a sub project

- airframe-rx-html/.js/src/main/scala/wvlet/airframe/rx/html/compat.scala
- airframe-rx-html/.jvm/src/main/scala/wvlet/airframe/rx/html/compat.scala
- airframe-rx-html/src/main/scala/wvlet/airframe/rx/html/Attrs.scala
- airframe-rx-html/src/main/scala/wvlet/airframe/rx/html/package.scala
Closes #1599 
Handlers are tested in https://github.com/wvlet/airframe/blob/master/airframe-rx-html/.js/src/test/scala/wvlet/airframe/http/rx/html/HtmlRenderingTest.scala
> [airframe-rx-html] Make event handlers type-safe

- .scalafmt.conf
- airspec/.scalafmt.conf
- airspec/build.sbt
- airspec/src/main/scala/wvlet/airspec/spi/AirSpecContext.scala
Supersedes #2042 
I think this makes easy to version up scalafmt
> Share same scalafmt config between airframe and airspec

- airframe-surface/.js/src/test/scala/wvlet/airframe/surface/AirSpecBridgeCompat.scala
- airframe-surface/.jvm/src/test/scala-3/wvlet/airframe/surface/reflect/TastySurfaceFactoryTest.scala
- airframe-surface/.jvm/src/test/scala/wvlet/airframe/surface/AbstractTypeTest.scala
- airframe-surface/.jvm/src/test/scala/wvlet/airframe/surface/AirSpecBridgeCompat.scala
- airframe-surface/.jvm/src/test/scala/wvlet/airframe/surface/InnerClassTest.scala
- airframe-surface/.jvm/src/test/scala/wvlet/airframe/surface/reflect/NamedParameterTest.scala
- airframe-surface/.jvm/src/test/scala/wvlet/airframe/surface/reflect/RuntimeSurfaceTest.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/AirSpecBridge.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/AliasSurfaceTest.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/CNameTest.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/EnumTest.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/MethodSurfaceTest.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/ParamTest.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/RecursiveHigherKindTypeTest.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/RecursiveSurfaceTest.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/RequiredParamTest.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/SecretParamTest.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/SurfaceSpec.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/SurfaceTest.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/ZeroTest.scala
- build.sbt
When working on Scala 3 support in `surface` module, I found `DOTTY=1 sbt surfaceJVM/test` raises errors like:
<details>
<pre><codE>
[error] Test suite wvlet.airframe.surface.ZeroTest failed with java.lang.NoClassDefFoundError: Could not initialize class wvlet.airframe.metrics.ElapsedTime$.
[error] This may be due to the ClassLoaderLayeringStrategy (ScalaLibrary) used by your task.
[error] To improve performance and reduce memory, sbt attempts to cache the class loaders used to load the project dependencies.
[error] The project class files are loaded in a separate class loader that is created for each test run.
[error] The test class loader accesses the project dependency classes using the cached project dependency classloader.
[error] With this approach, class loading may fail under the …
> Use munit temporarily to avoid airspec <-> surface circular reference

- airframe-surface/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala
The below tests now passes on JVM + Scala 3
- wvlet.airframe.surface.MultipleConstructorArgsTest
- wvlet.airframe.surface.ClassSurfaceTest
✅ 95
```
$ DOTTY=1 sbt surfaceJVM/test:clean;surfaceJVM/test 
[error] Failed: Total 101, Failed 6, Errors 0, Passed 95
[error] Failed tests:
[error]         wvlet.airframe.surface.RecursiveSurfaceTest
[error]         wvlet.airframe.surface.MultipleConstructorArgsTest
[error]         wvlet.airframe.surface.RecursiveHigherKindTypeTest
[error]         wvlet.airframe.surface.reflect.RuntimeSurfaceTest
[error]         wvlet.airframe.surface.ClassSurfaceTest
[error]         wvlet.airframe.surface.SurfaceTest
```
✅ 97(+2)
```
$ DOTTY=1 sbt surfaceJVM/test:clean;surfaceJVM/test ​
[error] Failed: Total 101, Failed 4, Errors 0, Passed 97
[error] Failed tests: …
```
> [surface] Scala 3: Handle case fields as method arguments

- airframe-surface/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/SurfaceTest.scala
It might be quick and dirty 😅 
✅ 97
```
$ DOTTY=1 sbt surfaceJVM/test:clean;surfaceJVM/test ​
[error] Failed: Total 101, Failed 4, Errors 0, Passed 97
[error] Failed tests:
[error]         wvlet.airframe.surface.RecursiveSurfaceTest
[error]         wvlet.airframe.surface.RecursiveHigherKindTypeTest
[error]         wvlet.airframe.surface.reflect.RuntimeSurfaceTest
[error]         wvlet.airframe.surface.SurfaceTest
```
✅ 101(+4)
```
[info] Passed: Total 101, Failed 0, Errors 0, Passed 101
```
> [surface] Scala 3: Pass all tests on JVM

- build.sbt
https://www.scala-lang.org/blog/2022/02/01/scala-3.1.1-released.html
> Upgrade to Scala 3.1.1

- airspec/build.sbt
- build.sbt
When working on Scala 3 support, I often need to run tests over Scala 3 and 2, like:
```
$ DOTTY=1 sbt 
sbt> ++surfaceJVM/test
```
to confirm behaviours both on Scala 3 and 2.
However, `++COMMAND` is failing on Scala 2 right now, because settings are only configured for Scala 3 due to hard-coded `if (DOTTY)`.
This PR replaces `DOTTY` criteria as much as possible to `scalaVersion.value.startsWith("3.")` so cross-build can be
<del>And, `dottyTest/test` now runs all tests on dotty-support-ongoing project.</del>
`projectDotty` already exists for that purpose.
> [build] Make it easier on cross-build while working on Scala 3 support

- .scala-steward.conf
Scala Steward now can configure update frequency granularly.
https://github.com/scala-steward-org/scala-steward/pull/2515
> Slow down awssdk update

- examples/rpc-examples/rpc-scalajs/project/plugins.sbt
- examples/rx-demo/gallery/project/plugins.sbt
Reverts wvlet/airframe#2112
#2118 must be released for AirSpec before upgrading to Scala.js 1.10.0, where UUID.randomUUID() requires crypto module, which is not supported in jsdom.
> Revert "Update sbt-scalajs, scalajs-compiler, ... to 1.10.0"

- airframe-ulid/.js/src/main/scala/wvlet/airframe/ulid/compat.scala
- build.sbt
- docs/airframe-ulid.md
Using a secure random generator is necessary to protect the system from predicting ULID values that will be generated. This is important especially when ULID is exposed as public parameters. 
Since Scala.js 1.10.0, it provides a SecureRandom implementation https://github.com/scala-js/scala-js-java-securerandom 
https://www.scala-js.org/news/2022/04/04/announcing-scalajs-1.10.0/
For the best compatibility, if Node.js `crypto` module or Web Crypto API are not available, it will fallback to non-secure random generator. This is good for testing at jsdom environment, which doesn't support crypto module https://github.com/jsdom/jsdom/issues/1612
> airframe-ulid: Use SecureRandom-based generator for Scala.js

- airframe-codec/.jvm/src/main/scala/wvlet/airframe/codec/StringUnapplyCodec.scala
- airframe-codec/src/main/scala/wvlet/airframe/codec/ThrowableCodec.scala
- airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/internal/GrpcException.scala
- airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/GrpcErrorHandlingTest.scala
- airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/example/DemoApi.scala
- airframe-http/src/main/scala/wvlet/airframe/http/RPCException.scala
- airframe-http/src/main/scala/wvlet/airframe/http/RPCStatus.scala
- airframe-http/src/test/scala/wvlet/airframe/http/RPCExceptionTest.scala
- airframe-http/src/test/scala/wvlet/airframe/http/RPCStatusTest.scala
Embed RPCException to gRPC trailer so that the client can receive detailed RPCException.
> airframe-grpc: Propagate RPCException to clients

- airspec/.js/src/main/scala/wvlet/airspec/Compat.scala
- airspec/.jvm/src/main/scala/wvlet/airspec/Compat.scala
- airspec/build.sbt
- airspec/src/main/scala/wvlet/airspec/AirSpec.scala
- airspec/src/main/scala/wvlet/airspec/AirSpecLauncher.scala
- airspec/src/main/scala/wvlet/airspec/CompatApi.scala
- airspec/src/main/scala/wvlet/airspec/runner/AirSpecContextImpl.scala
- airspec/src/main/scala/wvlet/airspec/runner/AirSpecTask.scala
- airspec/src/main/scala/wvlet/airspec/runner/AirSpecTaskRunner.scala
- airspec/src/main/scala/wvlet/airspec/spi/AirSpecContext.scala
- airspec/src/test/scala/examples/AsyncTest.scala
- airspec/src/test/scala/examples/TestSyntaxSpec.scala
- airspec/src/test/scala/wvlet/airspec/AirSpecLauncherTest.scala
- docs/airspec.md
Added support for running AirSpec tests returning Future values.
> AirSpec: Add async test support

- airframe-http/.js/src/main/scala/wvlet/airframe/http/client/JSHttpAsyncClient.scala
- airframe-http/.js/src/main/scala/wvlet/airframe/http/js/JSHttpClient.scala
- airframe-http/.js/src/test/scala/wvlet/airframe/http/client/JSHttpAsyncClientTest.scala
- airframe-http/.js/src/test/scala/wvlet/airframe/http/js/JSRPCClientTest.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/client/JavaHttpAsyncClient.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/client/JavaHttpSyncClient.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/client/JavaHttpAsyncClientTest.scala
- airframe-http/src/main/scala/wvlet/airframe/http/HttpClientConfig.scala
Add a new JS http client using the new interface added in #2188. 
The previous JSHttpClient implementation will be preserved for compatibility, but its internal will be replaced to the new JSHttpAsyncClient.
> airframe-http: Add JSHttpAsyncClient

- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/Compat.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/client/JavaAsyncClient.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/client/JavaHttpClientBackend.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/client/JavaSyncClient.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/client/JavaAsyncClientTest.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/client/JavaSyncClientTest.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/client/URLConnectionClientTest.scala
- airframe-http/src/main/scala/wvlet/airframe/http/Http.scala
- build.sbt
As we no longer have projects that require Java8, I'd like to drop Java8 support for ease of maintenance. And also, dropping Java8 support enables us to use the standard Java11 HttpClient (#2188), which can be used without dependency like Finagle/OkHttp. 
Note: airframe-http-finagle/okhttp can be used without any change. There is no plan to drop the HTTP clients in these modules.
cc: @wvlet/airframe-dev @exoego
> Drop Java8 support and use Java11 http client by default

- airframe-di/src/main/scala-3/wvlet/airframe/package.scala
- airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/GrpcServer.scala
- airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/GrpcClientTest.scala
- airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/GrpcContextTest.scala
- airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/GrpcErrorLogTest.scala
- airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/GrpcJsonTest.scala
- airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/GrpcRequestLoggerTest.scala
- airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/GrpcServerFactoryTest.scala
- airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/GrpcStreamingTest.scala
- airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/GrpcTest.scala
- airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/example/DemoApi.scala
- airframe-http-router/src/main/scala-3/wvlet/airframe/http/router/RouterBase.scala
> airframe-grpc: Fix syntax for Scala 3

- airframe-http-codegen/src/main/scala/wvlet/airframe/http/codegen/RouteAnalyzer.scala
- airframe-http-codegen/src/main/scala/wvlet/airframe/http/openapi/OpenAPI.scala
- airframe-http-codegen/src/test/scala/example/openapi/OpenAPIExample.scala
- airframe-http-codegen/src/test/scala/wvlet/airframe/http/openapi/OpenAPITest.scala
- airframe-http/src/main/scala/wvlet/airframe/http/HttpContext.scala
TODO: 
- Building router from classes is not working well in Scala 3
> airframe-http-codegen: Scala 3 support (part 1)

- airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/GrpcSurfaceTest.scala
- airframe-surface/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala
Surface for Scala 3 tried to traverse ServerServiceDefinition in grpc-java too deep and caused `java.util.NoSuchElementException: key not found: <special-ops>.<FromJavaObject>` error. 
This PR provides a workaround so as not to traverse private constructors, which might have tricky java classes.
After a new version of AirSpec with this fix is released, DI with gRPC will work.
We still need a fix for [#2194](https://github.com/wvlet/airframe/issues/2194)
> airframe-surface: Do not traverse non-public constructor

- airframe-control/src/main/scala/wvlet/airframe/control/Retry.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/client/JavaAsyncClientTest.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/client/JavaSyncClientTest.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/client/URLConnectionClientTest.scala
- airframe-http/src/main/scala-2/wvlet/airframe/http/client/RPCClientBase.scala
- airframe-http/src/main/scala-2/wvlet/airframe/http/impl/HttpMacros.scala
- airframe-http/src/main/scala-3/wvlet/airframe/http/client/RPCClientBase.scala
- airframe-http/src/main/scala/wvlet/airframe/http/Http.scala
- airframe-http/src/main/scala/wvlet/airframe/http/HttpBackend.scala
- airframe-http/src/main/scala/wvlet/airframe/http/HttpClientConfig.scala
- airframe-http/src/main/scala/wvlet/airframe/http/HttpMessage.scala
- airframe-http/src/main/scala/wvlet/airframe/http/client/HttpClients.scala
This is for complementing functionalities in the old HttpClient interface
> airframe-http: Add readAs[Resp], call[Req, Resp] to http clients

- airframe-di/.jvm/src/test/scala/wvlet/airframe/DesignSerializationTest.scala
- airframe-di/src/test/scala/wvlet/airframe/DesignTest.scala
- airframe-surface/.jvm/src/main/scala-3/wvlet/airframe/surface/reflect/TastySurfaceFactory.scala
- airframe-surface/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/RecursiveHigherKindTypeTest.scala
- build.sbt
module | Before | After 
---|---|---
diJVM | Passed 84 | Passed 89 (+5) All ✅ 
surfaceJVM | Passed 100 |  Passed 101 (+1) All ✅ 
codecJVM | Passed 107 |  Passed 107 (-) 😑 
```
$ DOTTY=1 sbt  projectDotty/test | grep '\[error\]' > error.txt
$ cat error.txt
[error] Error: Total 89, Failed 0, Errors 5, Passed 84, Pending 1
[error] Error during tests:
[error] 	wvlet.airframe.DesignSerializationTest
[error] 	wvlet.airframe.ProviderSerializationTest
[error] 	wvlet.airframe.DesignTest
[error] Error: Total 109, Failed 0, Errors 2, Passed 107, Pending 1
[error] Error during tests:
[error] 	wvlet.airframe.codec.PrimitiveCodecTest
[error] Failed: Total 101, Failed 1, Errors 0, Passed 100
[error] Failed tests:
[error] 	wvlet.airframe.surface.RecursiveHigherKindTypeTest
[error] (codecJVM / Test / …
```
> More dotty support

- airframe-jdbc/src/test/scala/wvlet/airframe/jdbc/ConnectionPoolFactoryTest.scala
- build.sbt
- docs/airframe-jdbc.md
Now that airframe-config supports Scala 3 #2205, airframe-jdbc can support Scala 3 as well.
> airframe-jdbc: Scala 3 support

- airframe-parquet/src/main/scala-2/wvlet/airframe/parquet/ParquetCompat.scala
- airframe-parquet/src/main/scala-3/wvlet/airframe/parquet/ParquetCompat.scala
- airframe-parquet/src/main/scala/wvlet/airframe/parquet/Parquet.scala
- airframe-parquet/src/test/scala/wvlet/airframe/parquet/ParquetQueryTest.scala
- airframe-parquet/src/test/scala/wvlet/airframe/parquet/ParquetTest.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/Expression.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/parser/SQLInterpreter.scala
- build.sbt
- TODO: airframe-parquet needs to find Surface from a given runtime class to use AnyCodec for writing records containing objects.
> airframe-sql: Scala 3 support

- .github/workflows/test.yml
- airframe-codec/src/main/scala/wvlet/airframe/codec/PrimitiveCodec.scala
- airframe-codec/src/test/scala/wvlet/airframe/codec/PrimitiveCodecTest.scala
- airframe-parquet/src/main/scala/wvlet/airframe/parquet/ParquetRecordWriter.scala
- build.sbt
Now that many unit tests runs smoothly for Scala 3, we can enable CI
> Run Scala 3 unit tests on CI

- .github/workflows/codecov.yml
- .github/workflows/package-test.yml
- .github/workflows/sbt-integration.yml
- .github/workflows/test.yml
- sbt-airframe/build.sbt
- sbt-airframe/sbt
JDK17 (LTS version after JDK11) is already supported in Scala https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html
- Use JDK17 by default 
- Test JDK11 only for Scala 2.13 JVM 
- Use JDK11 for releasing to Maven. This is for ensuring binary compatibility with JDK11
> Use JDK17 for regular CI and JDK11 for releases

- airframe-surface/.jvm/src/main/scala-2/wvlet/airframe/surface/reflect/ReflectSurfaceFactory.scala
- airframe-surface/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala
- build.sbt
An alternative approach for #2260 as concurrent creation of the same Surface type should not be a big issue.
> airframe-surface: Avoid recursive update of surface cache

- airframe-metrics/.jvm/src/main/scala/wvlet/airframe/metrics/TimeWindow.scala
Building ZoneOffset is not straightforward compared to using ZoneId.of(name).
> airframe-metrics: Use ZoneId for TimeWindow.withTimeZone() instead of ZoneOffset

- build.sbt
AWS EMR (e.g., serverless), Databricks, etc. still use Java8. To use these platform, we need to compile airframe against JDK8
> Retarget to JDK8

- airframe-di-macros/src/main/scala-2/wvlet/airframe/AirframeMacros.scala
- airframe-di-macros/src/main/scala-2/wvlet/airframe/SourceCode.scala
- airframe-di-macros/src/main/scala-3/wvlet/airframe/SourceCode.scala
- airframe-di/src/test/scala/wvlet/airframe/SourceCodeTest.scala
- airframe-log/src/main/scala-2/wvlet/log/LogMacros.scala
- airframe-log/src/main/scala-3/wvlet/log/LoggerBase.scala
- airframe-log/src/main/scala/wvlet/log/LogRecord.scala
- airspec/src/main/scala-2/wvlet/airspec/AirSpecMacros.scala
This is for preventing the private local folder information to be embedded to the code. This addresses #2326
> Removing full source paths from the generated code 

- airframe-sql/src/main/scala/wvlet/airframe/sql/catalog/DataType.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/parser/SQLTypeParser.scala
- airframe-sql/src/test/resources/wvlet/airframe/sql/catalog/argtypes.txt
- airframe-sql/src/test/resources/wvlet/airframe/sql/catalog/types.txt
- airframe-sql/src/test/scala/wvlet/airframe/sql/catalog/DataTypeTest.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/parser/SQLTypeParserTest.scala
- build.sbt
For parsing column type information returned from information_schema, show functions, etc.
> airframe-sql: Add SQL type name parser

- airspec/README.md
```shell
[info] Reapplying settings...
[info] set current project to airspec (in build file:/Users/yukihiro.okada/IdeaProjects/airframe/airspec/)
[error] Not a valid command: publishSnapshot (similar: publishSnapshots)
[error] Not a valid project ID: publishSnapshot
[error] Expected ':'
[error] Not a valid key: publishSnapshot (similar: isSnapshot, publishTo, publishSigned)
[error] publishSnapshot
[error]
```
> Update README.md to fix

- airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/GrpcContext.scala
- airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/GrpcService.scala
- airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/internal/GrpcContextTrackInterceptor.scala
- airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/GrpcContextTest.scala
- airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/example/DemoApi.scala
- airframe-http/.js/src/main/scala/wvlet/airframe/http/Compat.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/Compat.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/internal/LocalRPCContext.scala
- airframe-http/src/main/scala/wvlet/airframe/http/CompatApi.scala
- airframe-http/src/main/scala/wvlet/airframe/http/RPCContext.scala
To properly access thread-local storage in gRPC, the code needs to be wrapped inside the Listener body.
> airframe-grpc: Fix thread local storage

- airframe-surface/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/RecursiveHigherKindTypeTest.scala
- Remove `import dotty.tools.dotc.core.{Types as DottyTypes}`, which is available only in JVM, for supporting Scala.js
- Use pattern matching with ParamRef and TypeBounds instead of asInstanceOf class check
> airframe-surface: Scala3 higher-kind type support

- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- .github/workflows/test.yml
- airframe-http/.js/src/main/scala/wvlet/airframe/http/js/JSHttpClient.scala
- airframe-rx-html/.js/src/test/scala/wvlet/airframe/http/rx/html/HtmlRenderingTest.scala
- airframe-rx-html/.js/src/test/scala/wvlet/airframe/http/rx/html/RxRenderingTest.scala
- airframe-rx-widget/src/main/scala/wvlet/airframe/rx/html/widget/ui/bootstrap/Button.scala
- airframe-rx-widget/src/test/scala/wvlet/airframe/http/rx/widget/RxWidgetTest.scala
- build.sbt
Now that AirSpec supports Scala 3 + Scala.js, there is no need to use DOTTY flag to switch build.sbt configurations.
- Use Scala3, Scala2 cross build by default. For projects not supporting Scala 3, `scala2Only` setting will be added. 
- Now + projectJVM/publish, + projectJS/publish work for publishing Scala 2/3 modules at once
- All of the Scala.js modules support Scala 3 (rxHtml, widget, etc.)
- Hopefully, IntelliJ understands Scala 3 source code folder for syntax highlighting. 
- DOTTY=true ./sbt is still useful if you want to work on Scala 3 by default.
cc: @exoego
> Scala3 crossbuild

- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/client/JavaClientChannel.scala
Response of JDK's http client contains some pseudo headers that start with `:`.
Finagle's validation error occurs if we try to return a response that include these headers in airframe-http/rpc based server application.
```
2022-10-18 14:19:25.142+0900  warn [FinagleServer] Request("GET /v1/status", from /127.0.0.1:60175) failed: com.twitter.finagle.http.headers.Rfc7230HeaderValidation$NameValidationException: Header ':status': name cannot contain the prohibited character '0x3a': :  - (FinagleServer.scala:272)
com.twitter.finagle.http.headers.Rfc7230HeaderValidation$NameValidationException: Header ':status': name cannot contain the prohibited character '0x3a': :
at com.twitter.finagle.http.headers.Rfc7230HeaderValidation$.validateName(Rfc7230HeaderValidation.scala:106)
at …
```
> Exclude pseudo headers from response of JDK's http client

- airframe-http-codegen/src/test/scala/wvlet/airframe/http/openapi/SimpleOpenAPITest.scala
- airframe-json/src/main/scala/wvlet/airframe/json/YAMLFormatter.scala
- airframe-json/src/test/scala/wvlet/airframe/json/YAMLFormatterTest.scala
- Fixes #2491: Use literal format when necessry
- Add openapi test for multi-line literal
> openapi: Fixes #2491: Use YAML literal for multi-line strings and strings with single quote

- build.sbt
sbt-crossproject now generates the modJVM and modJS lazy vals so can remove them.
This helps lowering the amount of code needed to support Scala Native
> Remove the generated modJVM and modJS definitions

- .github/release-drafter.yml
For properly categorizing test library updates like https://github.com/wvlet/airframe/pull/2508 in the release note draft
> Classify PRs with test-libray-update label as Dependency Updates

- airframe-parquet/src/main/scala/wvlet/airframe/parquet/ParquetQueryPlanner.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/TypeResolver.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/Expression.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlan.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/ResolvedPlan.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/parser/SQLGenerator.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/SQLAnalyzerTest.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/TypeResolverTest.scala
- Added `qualifier` parameter to ResolvedAttribute for tracking aliases
- AliasedRelation.output attributes returns a list of ResolvedAttributes with a qualifier (i.e. aliases)
- Fixed column name match when the context database is in the qualified name (QName)
> airframe-sql: Fixes table/relation alias handling in TypeResolver 

- airframe-http/.js/src/test/scala/wvlet/airframe/http/client/JSRPCClientTest.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/client/RPCHttpClientTest.scala
- airframe-http/src/main/scala/wvlet/airframe/http/HttpClientConfig.scala
- airframe-http/src/main/scala/wvlet/airframe/http/RPCEncoding.scala
Using JSON by default is good for compatibility.
> airframe-http: Use JSON encoding by default for HTTP clients

- airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlan.scala
Include inputAttributes of all relations in UNION's inputAttributes.
> Include inputAttributes of all relations in UNION

- airframe-di/src/main/scala-2/wvlet/airframe/BinderImpl.scala
Aiframe DI will manage only singleton instances within a session for simplicity. This PR mark toInstance[X]... methods as deprecated.
>   airframe-di: Deprecate toInstanceOf, toSingletonOf, toInstanceProvider, toSingletonProvider

- airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/TypeResolver.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlan.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/ResolvedPlan.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/TypeResolverTest.scala
ouptputAttribute stays unresolved if the column is a duplicated key in equi join.
```scala
val p = analyze("select B.id from A inner join B on A.id = B.id")
println(p.outputAttributes) // => List(SingleColumn(UnresolvedAttribute(B.id)))
```
With this fix, outputAttributes will be `List(id:long <- B.id)`.
> airframe-sql: Fix duplicated join keys handling

- airframe-sql/src/main/scala/wvlet/airframe/sql/parser/SQLGenerator.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/parser/SQLGeneratorTest.scala
https://github.com/wvlet/airframe/pull/2586 was not enough to cover subqueries in FROM clause. `SetOperation` also needs to be covered.
> airframe-sql: Fix SQL generation for SetOperation in FROM clause

- airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/TypeResolver.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlan.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/parser/SQLGenerator.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/parser/SQLInterpreter.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/TypeResolverTest.scala
> airframe-sql: Intersect should have attributes of all source relations

- airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/CTEResolver.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/TypeResolver.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/Expression.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlan.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/parser/SQLGenerator.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/parser/SQLInterpreter.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/TypeResolverTest.scala
Prevent resolving `Identifier`s of alias by making them `String`.
> airframe-sql: Prevent resolving Identifiers of column alias

- airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/TypeResolver.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/Expression.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlan.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/parser/SQLGenerator.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/parser/SQLInterpreter.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/TypeResolverTest.scala
I thought we can handle Union by letting `ResolvedAttribute` has multiple `SourceColumn`s, however it wasn't enough.
This pull request will revert it to represent union columns as a special expression type `MultiSourceColumn` which is similar to `UnionColumn` in the previous PR.
> airframe-sql: Refine Union handling

- airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlan.scala
`LogicalPlan.resolved` returns `true` even if there are unresolved attributes inside sub queries without this, but this change may have unexpected side-effect?
By the way, `LogicalPlan.resolved` also returns `true` when `Id(col)` remains in the plan. But it looks like impossible to determine which identifiers should be resolved or not systematically on the current mechanism. For example, it should be resolved if it's a column reference, but shouldn't if it's a column or table alias.
Any ideas to correctly detect identifiers that should be resolved?
> airframe-sql: Fix collectExpression() to cover nested plans

- airframe-http-codegen/src/main/scala/wvlet/airframe/http/openapi/OpenAPI.scala
- airframe-http-codegen/src/main/scala/wvlet/airframe/http/openapi/OpenAPIGenerator.scala
- airframe-http-codegen/src/test/scala/example/openapi/OpenAPIExample.scala
- airframe-http-codegen/src/test/scala/wvlet/airframe/http/openapi/OpenAPITest.scala
- airframe-surface/.jvm/src/main/scala/wvlet/airframe/surface/reflect/RuntimeMethodParameter.scala
- airframe-surface/.jvm/src/test/scala-2/wvlet/airframe/surface/AirSpecBridgeCompat.scala
- airframe-surface/.jvm/src/test/scala-3/wvlet/airframe/surface/AirSpecBridgeCompat.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/AirSpecBridge.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/MethodSurfaceTest.scala
Closes #2596 
This PR improved `RuntimeMethodParameter` so it can extract default method parameters defined in trait such as `trait OpenAPIEndpointExample`.
OpenAPIGenerator leverages `RuntimeMethodParameter` and now generates the `default` field in schema.
Note that Scala 3's `StaticMethodParameter` in `CompileTimeSurfaceFactory` is not touched in this PR.
Because this new feature is useful and `httpCodeGen` project is Scala 2 only at this moment, and I am still new to Scala 3's macro 😓
> OpenAPI: Generate parameters with default value

- airframe-sql/src/main/scala/wvlet/airframe/sql/catalog/DataType.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/catalog/DataTypeParser.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/Expression.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlan.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlanPrinter.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/ResolvedPlan.scala
- airframe-sql/src/test/resources/wvlet/airframe/sql/catalog/types.txt
- airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/TypeResolverTest.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/catalog/DataTypeTest.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/model/LogicalPlanTest.scala
For ease of debugging, this PR adds DataType information to Expression node
- Display DataType wth `LogicalPlan.pp`
- Set DataType for simple Expressions
- Add Expression.{attributeName, dataType, dataTypeName, typeDescription} methods
- Change LogicalPlan.expressions -> childExperssions to clarify what will be returned
- Add DataType.Unknown(?) to show unresolved type of the expression
- Add EmbeddedRecordType to represent DataType of AllColumns and RowConstructor
With this change, the debug message will be like this:
```
[original]
SELECT id, t.key, t.value FROM A
CROSS JOIN UNNEST (
array['c1', 'c2', 'c3'],
array[1, 2, 3]
) AS t (key, value)
[resolved]
SELECT A.id, t.key, t.value FROM default.A CROSS JOIN UNNEST (ARRAY['c1', 'c2', 'c3'], ARRAY[1, 2, 3]) AS t(key, value)
[original plan] …
```
> airframe-sql: Add DataType to Expression nodes

- airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/TypeResolverTest.scala
Simplify `TypeResolverTest` using `shouldMatch` to make it easier to maintain and to add further test cases.
> airframe-sql: Simplify test cases

- .scala-steward.conf
The grouping capability of scala-steward is not ideal because the PR title doesn't contain the new version number. Removing this setting
> internal: Remove grouping of airframe updates

- airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/Optimizer.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/RewriteRule.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/SQLAnalyzer.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/TypeResolver.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlan.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/TypeResolverTest.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/parser/SQLGeneratorTest.scala
Introduce RewriteRule to observe how individual rules rewrite LogicalPlan. This will be used for debugging #2646  
By setting a log level like this: 
airframe-sql/src/test/resources/log-test.properties
```
wvlet.airframe.sql.analyzer.RewriteRule=trace
```
You can see the transformation log:
```
transformed with resolveTableRef:
[before]
[Sort]: (id:?, name:?) => (id:?, name:?)
- SortItem(id:long <- [A.id],None,None,Some(NodeLocation(1,41)))
[Project]:  => (id:?, name:?)
- SingleColumn(Id(id))
- SingleColumn(Id(name))
[TableRef]
- default.A
[after]
[Sort]: (id:?, name:?) => (id:?, name:?)
- SortItem(id:long <- [A.id],None,None,Some(NodeLocation(1,41)))
[Project]: (id:long, name:string) => (id:?, name:?)
- SingleColumn(Id(id))
- SingleColumn(Id(name))
[TableScan]:  => (id:long, name:string) …
```
> airframe-sql: Add RewriteRule to see TypeResolver behavior

- airspec/src/main/scala/wvlet/airspec/runner/AirSpecContextImpl.scala
- airspec/src/main/scala/wvlet/airspec/runner/AirSpecMatcher.scala
- airspec/src/main/scala/wvlet/airspec/runner/AirSpecSbtRunner.scala
- airspec/src/main/scala/wvlet/airspec/runner/AirSpecTaskRunner.scala
- airspec/src/main/scala/wvlet/airspec/spi/AirSpecContext.scala
- airspec/src/test/scala/wvlet/airspec/runner/AirSpecMatcherTest.scala
- airspec/src/test/scala/wvlet/airspec/runner/NestTest.scala
- docs/airspec.md
Support selecting nested test cases with `(test name)/(child test name)/...` syntax. 
Could you take a look? @takezoe @exoego
> airspec: #2637 Support selecting nested test specs

- airspec/build.sbt
AirSpec 22.12.5 fails to run tests in Scala.js because this dependency is missing
> airspec: Include scala-js-macrotas-executor explicitely for Scala.js

- airframe-parquet/src/main/scala/wvlet/airframe/parquet/ParquetQueryPlanner.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/CTEResolver.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/Optimizer.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/RewriteRule.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/SQLAnalyzer.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/SQLAnonymizer.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/TypeResolver.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/Expression.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlan.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/ResolvedPlan.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/parser/SQLGenerator.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/parser/SQLInterpreter.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/SQLAnalyzerTest.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/TypeResolverTest.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/model/ExpressionTest.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/model/LogicalPlanTest.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/parser/SQLGeneratorTest.scala
- build.sbt
- Propagate qualifiers (table name) properly so that join keys can be resolved correctly.
- Merge the common logic for Attribute handling (AllColumn, SingleColumn, MultiColumn, Unresolved/ResolvedAttribute)
- Renamed MultiColumn -> MultiSourceColumn to clarify the meaning
- TypeResolver.resolveTableScan -> Do not add qualifiers to ResolvedAttribute. Qualifiers can be added if they are given in the original SQL
- Fixed Join outputAttributes: 
- JoinUsing(keys, ..): merge join keys as MultiSourceColumn. Added ResolveJoinUsing(...) 
- JoinOn(cond): Output all input child relation outputs
- Changed Attribute class structure
- Add common methods (e.g., qualifier, withQualifier, withAlias, etc.)
- ResolvedAttribute is changed to take a single source column because we can merge multiple …
> airframe-sql: Fix qualifier resolution

- airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/TypeResolver.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/Expression.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlan.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/ResolvedPlan.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/parser/SQLInterpreter.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/TypeResolverTest.scala
- Fixed input/output attributes of set operations 
- Added ResolvedIdentifier to to make Identifier unresolved at the beginning. With this change, we can detect unresolved identifier (p2) in this case:
```scala    
test(s"ru2b: should fail to resolve overridden column name (p2) via union") {
intercept[AssertionFailure] {
analyze("select p2 from (select id as p1 from A union all select id as p2 from B)")
}
}
```
- Fixed some union query tests
> airframe-sql: Fix the resolver of set relations

- airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/TypeResolver.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/Expression.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlan.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/ResolvedPlan.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/parser/SQLInterpreter.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/TypeResolverTest.scala
Traverse only given children in traverseExpressions so as not to traverse references in AllColumns and MultiSourceColumns
> airframe-sql: Fix Expression.traverseExpression for Attribute nodes

- airframe-di/src/main/scala-3/wvlet/airframe/package.scala
- airframe-di/src/main/scala/wvlet/airframe/DISupport.scala
- airframe-di/src/main/scala/wvlet/airframe/Session.scala
- airframe-di/src/test/scala-2/wvlet/airframe/legacy/AssistedInjectionTest.scala
- airframe-di/src/test/scala-3/wvlet/airframe/di/TraitFactoryTest.scala
- airframe-http-router/src/main/scala/wvlet/airframe/http/Router.scala
This is a blocker for supporting airframe-http and grpc in Scala 3 https://github.com/wvlet/airframe/issues/2194
- example https://github.com/lampepfl/dotty/blob/main/tests/run-macros/newClassExtendsClassParams/Macro_1.scala
> airframe-di: registerTraitFactory for Scala 3

- airframe-http-codegen/src/test/scala-2/wvlet/airframe/http/codegen/GenericServiceTest.scala
- airframe-http-codegen/src/test/scala/example/generic/GenericService.scala
- airframe-http-codegen/src/test/scala/wvlet/airframe/http/codegen/GrpcClientGeneratorTest.scala
- airframe-http-codegen/src/test/scala/wvlet/airframe/http/codegen/HttpClientGeneratorTest.scala
- airframe-http-codegen/src/test/scala/wvlet/airframe/http/codegen/RPCClientGeneratorTest.scala
- airframe-http-codegen/src/test/scala/wvlet/airframe/http/openapi/OpenAPITest.scala
- airframe-surface/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala
- build.sbt
- Do not support reflection-based Routers in Scala 3. Will provide a Java-reflection based approach to find `object Api { def defaultRouter: Router[Api] = Router.of[API] }` in #2669 
- Skip supporting default method parameters in Scala 3
- Add http-codegen to projectDotty
> airframe-http-codegen: Scala 3 support

- airframe-http-netty/src/main/scala/wvlet/airframe/http/netty/NetthRequestHandler.scala
- airframe-http-okhttp/src/test/scala/wvlet/airframe/http/okhttp/OkHttpClientTest.scala
- airframe-http/src/main/scala/wvlet/airframe/http/ServerAddress.scala
- build.sbt
- Remove Finagle from test
- TODO:  Interface change #2440
> airframe-okhttp: Scala3 support prep. Remove Finagle from test dependency

- airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/TypeResolver.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/TypeResolverTest.scala
My previous pull request (https://github.com/wvlet/airframe/pull/2674) caused unresolved grouping keys in some cases.
I think `resolveSortItemIndexes` may need the same fix, but not 100% sure.
> airframe-sql: Further fix for resolveAggregationIndexes

- airframe-sql/src/main/scala/wvlet/airframe/sql/model/Expression.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlan.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/model/LogicalPlanTest.scala
This will make possible to traverse/transform `LogicalPlan` in `Expression`.
Another idea is moving all traverse and transform methods (including `mapChildren`) to TreeNode with a signature change `LogicalPlan` -> `TreeNode[_]`. This will change the ability of those methods that can traverse/transform any nodes in the tree, not only `LogicalPlan`. Meaning, no need to have methods for `LogicalPlan` and `Expression` independently.
I'm not sure which is better. 🤔
> airframe-sql: Support in-expression sub-query in traverse and transform

- airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlan.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/TypeResolverTest.scala
airframe-sql fails to resolve output columns of UNION if there are multiple columns:
```
[sql]
select id, name from (select id, name from A union all select id, name from B)
[plan]
[Project]: (id:long) => (id:long, name:?)
- id:long := {*id:long <- A.id, *name:string <- A.name, *id:long <- B.id, *name:string <- B.name}
- name:? := Id(name)
[Union]: (id:long, name:string, id:long, name:string) => (id:long)
[Project]: (id:long, name:string) => (id:long, name:string)
- *id:long <- A.id
- *name:string <- A.name
[TableScan] default.A:  => (id:long, name:string)
[Project]: (id:long, name:string) => (id:long, name:string)
- *id:long <- B.id
- *name:string <- B.name
[TableScan] default.B:  => (id:long, name:string)
[unresolved expressions]
name:? := Id(name)
Id(name)
```
> airframe-sql: Resolve multiple columns from UNION in sub-query

- airframe-sql/src/main/scala/wvlet/airframe/sql/parser/SQLGenerator.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/parser/SQLGeneratorTest.scala
`SQLGenerator` generates invalid SQL if left side of JOIN is sub-query.
> airframe-sql: Fix SQL generation for JOIN

- airframe-sql/src/main/scala/wvlet/airframe/sql/model/Expression.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/TypeResolverTest.scala
To make it possible to resolve columns outside a sub-query that has qualified `AllColumns` like this:
```sql
select t2.name from A t1 inner join (select * from B) t2 using (id)
```
`t2.name` in the select clause cannot be resolved in this SQL.
> airframe-sql: Qualify outputColumns if AllColumns has qualifier

- airframe-sql/src/main/scala/wvlet/airframe/sql/model/Expression.scala
https://github.com/wvlet/airframe/pull/2763 wasn't enough 🙇‍♂️
Unqualifying is also necessary if `AllColumns` doesn't have a qualifier.
> airframe-sql: Unqualify outputColumns if AllColumns doesn't have qualifier

- airframe-log/.jvm/src/main/scala/wvlet/log/LogEnv.scala
Previously, airframe-log added a workaround for #1756, but it caused `sbtn` not to show any log output. 
By disabling the logging initialization in airlift log-manager, we no longer need this workaround.
> airframe-log: Fixes #2777 Use the default System.err for supporting sbtn

- .github/release.yml
- .github/workflows/release-drafter.yml
- .github/workflows/release-note.yml
- README.md
- Updated the release process
- Add release note generator workflow
- Still use release-drafter only for labeling pull requests.
> [internal] Automatically generate release notes 

- airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/SQLAnonymizer.scala
- airframe-sql/src/main/scala/wvlet/airframe/sql/model/Expression.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/TypeResolverTest.scala
When resolving types, the library should ignore case as most engines (ex: Trino) do not handle case-sensitive identifiers themselves.
> fix(airframe-sql): Case should be ignored when resolving identifiers

- .github/workflows/test.yml
- scripts/setup-scalajs.sh
It seems using Node.js 18 breaks all Scala.js build that uses jsdom. 
An example error message:
```
$ node --version
v18.9.0
$ ./sbt
> httpJS/test
Node.js v18.9.0
/Users/leo/work/git/airframe/node_modules/jsdom/lib/jsdom/living/helpers/events.js:15
const event = createAnEvent(e, target._globalObject, eventInterface, attributes);
^
TypeError: Cannot read properties of undefined (reading '_globalObject')
at fireAnEvent (/Users/leo/work/git/airframe/node_modules/jsdom/lib/jsdom/living/helpers/events.js:15:41)
at Timeout._onTimeout (/Users/leo/work/git/airframe/node_modules/jsdom/lib/jsdom/living/post-message.js:36:7)
at listOnTimeout (node:internal/timers:564:17)
at process.processTimers (node:internal/timers:507:7)
```
> Upgrade to Node.js 18

- airframe-surface/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala
This is a workaround for Scala3 compile-time MethodSurface generator, in which the method order becomes unstable
> airframe-surface: Sort MethodSurface alphabetically

- airframe-http-codegen/src/main/scala/wvlet/airframe/http/codegen/HttpCodeGenerator.scala
- airframe-http-codegen/src/main/scala/wvlet/airframe/http/codegen/RouteScanner.scala
- airframe-http-codegen/src/test/scala/example/nested/v1/MyApi.scala
- airframe-http-codegen/src/test/scala/example/nested/v2/MyApi.scala
- airframe-http-codegen/src/test/scala/wvlet/airframe/http/codegen/NestedApiTest.scala
- airframe-http-codegen/src/test/scala/wvlet/airframe/http/codegen/RPCClientGeneratorTest.scala
- airframe-http-codegen/src/test/scala/wvlet/airframe/http/codegen/RxRouterProviderTest.scala
- airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/GrpcErrorLogTest.scala
- airframe-http-netty/src/test/scala/wvlet/airframe/http/netty/NettyRxFilterTest.scala
- airframe-http-netty/src/test/scala/wvlet/airframe/http/netty/NettyRxRPCServerTest.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/Router.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/router/RPCCustomPathTest.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/router/RxRouterConverterTest.scala
- Add REST Endpoint support in RxRouter 
- Support scanning RxRouterProvider definitions in the classpath
> airframe-http: Build Router at runtime using RxRouterProvider for Scala 3 support

- airspec/src/main/scala/wvlet/airspec/spi/Asserts.scala
- airspec/src/test/scala/examples/FlakyBlockTest.scala
- docs/airspec.md
For handling cases like #2869 without changing the test code so much
> airspec: Add flaky { ... } block to skip flaky tests

- airframe-http-netty/src/main/scala/wvlet/airframe/http/netty/NettyBackend.scala
- airframe-http-netty/src/test/scala/wvlet/airframe/http/netty/NettyRxFilterTest.scala
- airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRecorder.scala
- airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRecorderServer.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/router/HttpRequestDispatcher.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/router/Route.scala
- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/router/RxRouterConverterTest.scala
- airframe-http/src/main/scala-2/wvlet/airframe/http/router/RxRouterBase.scala
- airframe-http/src/main/scala-2/wvlet/airframe/http/router/RxRouterMacros.scala
- airframe-http/src/main/scala-3/wvlet/airframe/http/router/RxRouterBase.scala
- airframe-http/src/main/scala/wvlet/airframe/http/HttpBackend.scala
- airframe-http/src/main/scala/wvlet/airframe/http/RxHttpEndpoint.scala
- airframe-http/src/main/scala/wvlet/airframe/http/RxHttpFilter.scala
- airframe-http/src/main/scala/wvlet/airframe/http/router/RedirectToRxEndpoint.scala
- airframe-http/src/main/scala/wvlet/airframe/http/router/RxRouter.scala
- airframe-http/src/test/scala/wvlet/airframe/http/router/CustomEndpointTest.scala
- airframe-http/src/test/scala/wvlet/airframe/http/router/RxRouterTest.scala
Introducing a breaking change before RxHttpFilter is used seriously in applications
> airframe-http: Rename RxFilter/Endpoint to RxHttpFilter/Endpoint

- airframe-http/.js/src/main/scala/wvlet/airframe/http/client/JSHttpClientChannel.scala
The cause of #2893 looks like setting a value to Promise when it's already completed for some unexpected reason. This PR will mitigate the issue so as not to throw IllegalArgumentException at Promise method calls.
> airframe-http: Check the completion of Promise in JSHttpClientChannel #2893

- airframe-http/.js/src/main/scala/wvlet/airframe/http/client/JSHttpClientChannel.scala
- airframe-http/.js/src/test/scala/wvlet/airframe/http/client/JSHttpAsyncClientTest.scala
- airframe-http/.js/src/test/scala/wvlet/airframe/http/client/JSRPCClientTest.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/client/JavaHttpClientBackend.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/client/JavaHttpClientChannel.scala
- airframe-http/src/main/scala/wvlet/airframe/http/client/ClientFilter.scala
- Switch the public REST endpoint for testing from https://httpbin.org/ to https://jsonplaceholder.typicode.com/
> airframe-http (internal): Fix flaky JS http client tests

- airframe-http-codegen/src/main/scala/wvlet/airframe/http/codegen/HttpClientIR.scala
- airframe-http-codegen/src/main/scala/wvlet/airframe/http/codegen/client/RPCClientGenerator.scala
- build.sbt
- sbt-airframe/src/sbt-test/sbt-airframe/generate-client/build.sbt
- sbt-airframe/src/sbt-test/sbt-airframe/generate-client/server/src/main/scala/myapp/server/MyServer.scala
- sbt-airframe/src/sbt-test/sbt-airframe/generate-client/spi/src/main/scala/myapp/spi/MyRPC.scala
- sbt-airframe/src/sbt-test/sbt-airframe/generate-client/spi/src/main/scala/myapp/spi/MyService.scala
- sbt-airframe/src/sbt-test/sbt-airframe/grpc/build.sbt
- sbt-airframe/src/sbt-test/sbt-airframe/js-client/build.sbt
- sbt-airframe/src/sbt-test/sbt-airframe/js-client/test
- sbt-airframe/src/sbt-test/sbt-airframe/openapi/build.sbt
- sbt-airframe/src/sbt-test/sbt-airframe/openapi/test
- sbt-airframe/src/sbt-test/sbt-airframe/rpc-finagle/build.sbt
- sbt-airframe/src/sbt-test/sbt-airframe/rpc-netty/build.sbt
- sbt-airframe/src/sbt-test/sbt-airframe/rpc-netty/test
- internal: Reduce sbt-integration test scope only to Scala 2.12 and Scala 3 for reducing the test overhead
> airframe-http: Support reading REST endpoints with RPC clients

- airframe-http-codegen/src/main/scala/wvlet/airframe/http/codegen/client/HttpClientGenerator.scala
- airframe-http-codegen/src/test/scala/wvlet/airframe/http/codegen/RPCClientGeneratorTest.scala
- airframe-surface/src/main/scala-2/wvlet/airframe/surface/SurfaceMacros.scala
- airframe-surface/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/MethodSurfaceTest.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/SurfaceTest.scala
- build.sbt
- sbt-airframe/src/sbt-test/sbt-airframe/generate-client/build.sbt
With this fix, sbt-airframe code generator produces valid http client code
> airframe-surface: Resolve Any type properly in Scala 3

- airframe-http-codegen/src/main/scala/wvlet/airframe/http/codegen/HttpCodeGenerator.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/Router.scala
- sbt-airframe/build.sbt
- sbt-airframe/src/main/scala/wvlet/airframe/sbt/http/AirframeHttpPlugin.scala
- sbt-airframe/src/sbt-test/sbt-airframe/generate-client/build.sbt
- sbt-airframe/src/sbt-test/sbt-airframe/generate-client/test
- Do not include object hash to router string
- fix
- Fix name
- reduce debug log
- clenaup
- Fix
> sbt-airframe: Regenerate RPC clients upon API change without reload

- airframe-surface/src/main/scala/wvlet/airframe/surface/Surfaces.scala
```
sbt:wvlet> ui/fullLinkJS
[info] compiling 8 Scala sources to /Users/leo/work/git/wvlet/wvlet-api/.js/target/scala-3.2.2/classes ...
[info] compiling 3 Scala sources to /Users/leo/work/git/wvlet/wvlet-ui/target/scala-3.2.2/classes ...
[info] Full optimizing /Users/leo/work/git/wvlet/wvlet-ui/target/scala-3.2.2/ui-opt
[error] file:/home/runner/work/airframe/airframe/airframe-surface/src/main/scala/wvlet/airframe/surface/Surfaces.scala(235:12:Return): java.io.Serializable expected but java.lang.Class found for tree of type org.scalajs.ir.Trees$Apply
[error] file:/home/runner/work/airframe/airframe/airframe-surface/src/main/scala/wvlet/airframe/surface/Surfaces.scala(331:12:Return): java.io.Serializable expected but java.lang.Class found for tree of type org.scalajs.ir.Trees$Apply
[error] …
```
> airframe-surface: An attempt to fix fullLinkJS error

- airframe-benchmark/src/main/scala/wvlet/airframe/benchmark/http_request/RPCRequestBenchmark.scala
- airframe-codec/src/main/scala/wvlet/airframe/codec/MessageCodecFactory.scala
MessageCodecFactory used Surface case class as a cache key, which had a significant overhead. Improved the performance by using Surface.fullName as a cache key:
Before
```
[info] Benchmark                                     Mode  Cnt          Score          Error  Units
[info] RPCRequestBenchmark.rpcBodyOnly              thrpt   10  143043471.699 ± 72497486.069  ops/s
[info] RPCRequestBenchmark.rpcRequestNoCodec        thrpt   10      89063.233 ±      624.039  ops/s
[info] RPCRequestBenchmark.rpcRequestWithJsonSer    thrpt   10      74278.516 ±     1438.154  ops/s
[info] RPCRequestBenchmark.rpcRequestWithRPCMethod  thrpt   10      58004.750 ±      984.233  ops/s
```
After
```
[info] Benchmark                                     Mode  Cnt          Score        Error  Units
[info] …
```
> airframe-codec: 3-5x Improvement of the codec lookup performance of MessageCodecFactory 

- airframe-benchmark/README.md
- airframe-benchmark/src/main/scala/wvlet/airframe/benchmark/http_request/RPCRequestBenchmark.scala
- airframe-benchmark/src/main/scala/wvlet/airframe/benchmark/rpc_finagle/AirframeFinagle.scala
- airframe-benchmark/src/main/scala/wvlet/airframe/benchmark/rpc_request/RPCRequestBenchmark.scala
- airframe-http-netty/src/main/scala/wvlet/airframe/http/netty/NetthRequestHandler.scala
- build.sbt
Add a benchmark that revealed the overhead of building HTTP request/response object in an immutable manner:
```
[info] Benchmark                                              Mode  Cnt          Score         Error  Units
[info] RPCRequestBenchmark.rpcBodyOnly                       thrpt   10  188079929.691 ± 1265070.205  ops/s
[info] RPCRequestBenchmark.rpcNettyResponseBuilder           thrpt   10   16701854.988 ±  319776.222  ops/s
[info] RPCRequestBenchmark.rpcNettyResponseBuilderImmutable  thrpt   10    8819855.917 ±   49780.216  ops/s
[info] RPCRequestBenchmark.rpcRequestWithRPCMethod           thrpt   10     307929.262 ±    2108.229  ops/s
```
This PR also disables Finagle-based benchmark, which doesn't work in Scala 3
> internal: Add http response builder benchmark

- sbt-airframe/src/sbt-test/sbt-airframe/grpc/build.sbt
Scala 3 + grpc issue was fixed in https://github.com/wvlet/airframe/releases/tag/v23.5.5
> fix(grpc) #2883: Scala 3 grpc support works with the latest airframe

- airframe-jdbc/src/main/scala/wvlet/airframe/jdbc/DbConfig.scala
- airframe-jdbc/src/main/scala/wvlet/airframe/jdbc/GenericConnectionPool.scala
- airframe-jdbc/src/test/scala/wvlet/airframe/jdbc/DbConfigTest.scala
- Support `sslmode` parameter in PostgreSQL
- For relax verification when connecting to a DB using a CNAME record.
- When using a RDS host, a RDS is set up with a SSL certificate managed by AWS. But, a hostname is generated with randomly. It's not convenient. So, some of the users use DNS to set up an arbitrary name and use it to connect to the DB.
- At that case, the default sslmode gets cause of the error since a proper SSL certification isn't used.
- For the `psql` command,  it uses `prefer` when connecting to a DB with ssl. And, it works as expected.
> Support sslmode parameter in PostgreSQL

- airframe-rx-html/.js/src/main/scala/wvlet/airframe/rx/html/compat.scala
- airframe-rx-html/.js/src/test/scala/wvlet/airframe/http/rx/html/HtmlRenderingTest.scala
- airframe-rx-html/src/main/scala/wvlet/airframe/rx/html/HtmlNode.scala
- airframe-rx-html/src/main/scala/wvlet/airframe/rx/html/RxElement.scala
- airframe-rx-html/src/main/scala/wvlet/airframe/rx/html/RxEmbedding.scala
- airframe-rx-html/src/main/scala/wvlet/airframe/rx/html/RxEmbeddingSupport.scala
- airframe-rx-html/src/main/scala/wvlet/airframe/rx/html/SvgTags.scala
- airframe-rx-html/src/main/scala/wvlet/airframe/rx/html/package.scala
- airframe-rx-html/src/test/scala/wvlet/airframe/rx/html/HtmlTest.scala
And also closes #2994: Adding svg.title tag
> airframe-rx-html: Support implicit convertion to RxElement with import wvlet.airframe.rx.html.all.*

- airframe-control/src/main/scala/wvlet/airframe/control/Retry.scala
Adding randomness to the retry wait interval, called Jittering, is a better behavior in distributed systems so as not to create synthetic retry patterns between multiple programs accessing the same API.
> control (internal): Use Jittering by default in Retry

- airspec/.jvm/src/main/scala/wvlet/airspec/Compat.scala
- docs/airspec.md
- airspec (fix): Use daemon threads so as not to block scala-cli. Fixes #3049 
- Add usage note
> airspec (feature): scala-cli test support

- airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/TypeResolver.scala
Follow up to https://github.com/wvlet/airframe/pull/3057
> airframe-sql: Remove unnecessary condition from AllColumns resolution

- airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlan.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/TypeResolverTest.scala
Currently, `TypeResolver` fails to resolve cascaded set operations like:
```sql
select id from A union all select id from B union all select id from C
```
due to the following error:
> java.lang.IllegalArgumentException: transpose requires all collections have the same size
> airframe-sql: Support cascaded set operations

- airframe-http/.jvm/src/test/scala/wvlet/airframe/http/client/RPCHttpClientTest.scala
- airframe-http/src/main/scala/wvlet/airframe/http/client/HttpClientConfig.scala
- airframe-http/src/main/scala/wvlet/airframe/http/client/HttpClientFactory.scala
- airframe-http/src/main/scala/wvlet/airframe/http/client/HttpClients.scala
- airframe-integration-test/src/test/scala/wvlet/airframe/test/api/HelloRPCTest.scala
> rpc (fix): Set missing Accept header for RPC requests

- airframe-rx/src/main/scala/wvlet/airframe/rx/Rx.scala
- airframe-rx/src/main/scala/wvlet/airframe/rx/RxRunner.scala
- airframe-rx/src/test/scala/wvlet/airframe/rx/RxTest.scala
> rx (feature): Support join/zip upto 5 elements

- airframe-http-codegen/src/main/scala/wvlet/airframe/http/codegen/client/RPCClientGenerator.scala
> sbt-airframe (fix): Remove unused import Future from generated RPC clients

- airframe-http-okhttp/src/main/scala/wvlet/airframe/http/okhttp/OkHttpChannel.scala
- airframe-http-okhttp/src/main/scala/wvlet/airframe/http/okhttp/package.scala
- airframe-http-okhttp/src/test/scala/wvlet/airframe/http/okhttp/OkHttpTest.scala
- airframe-rx/src/main/scala/wvlet/airframe/rx/RxVar.scala
- Fixes #3109 
- Fix deprecated method usage
- rx (fix): Sychrnoize variable update
> rx (fix): Avoid concurrent modification of RxVar subscribers 

- airframe-rx-html/.js/src/main/scala/wvlet/airframe/rx/html/DOMRenderer.scala
- airframe-rx-html/.js/src/test/scala/wvlet/airframe/http/rx/html/RxRenderingTest.scala
- airframe-rx-html/src/main/scala/wvlet/airframe/rx/html/RxElement.scala
- Reproduce and fixes #3118
- rx-html: Call onMount when Rx is updated
> rx-html (fix): Properly call onMount hook when internal Rx is updated

- airframe-rx-html/src/main/scala/wvlet/airframe/rx/html/RxElement.scala
- airframe-rx-html/src/test/scala/wvlet/airframe/rx/html/RxElementTest.scala
- rx-html (feature): Enable logging in RxElements with info/debug/trace, etc.
- cleanup
>     rx-html (feature): Enable logging in RxElements with info/debug/trace, etc.

- airframe-rx/src/test/scala/wvlet/airframe/rx/RxTest.scala
- airspec/src/main/scala/wvlet/airspec/runner/AirSpecTaskRunner.scala
This fix is necessary due to the change in #3092
> airspec (fix): Async test failed to run RxOps 

- .github/workflows/codecov.yml
- .github/workflows/test.yml
- README.md
- build.sbt
- project/plugin.sbt
As the primary development has moved to Scala 3, adding Scala 3 source code (scala-3) to the IntelliJ project is better for daily development. We still need to support Scala 2 for a while, but we don't have so many Scala 2 specific source code (scala-2 folder). This change is to let IntelliJ recognize scala-3 source code folder to enable syntax highlight, etc.
> internal: Use Scala 3 by default for sbt and IntelliJ

- .github/workflows/codecov.yml
- build.sbt
Due to the change in #3137, coverageAggregate now runs on Scala 3 and chooses a different test report folder. This PR removes scala-2.xx or scala-3 version name from the test report path.
> internal (fix): Collect coverage report xml files properly

- airframe-surface/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala
- build.sbt
Reduce the macro generated code size by binding Surface to local val and reuse it. This fixes #3147
> surface (fix): Reduce the generated code size of Surface.methodOf in Scala 3

- airframe-http-codegen/src/main/scala/wvlet/airframe/http/codegen/client/RPCClientGenerator.scala
This error happened in Scala 3 when compiling a RPC client for a large API
> rpc (fix): Use lazy val for generated RPCMethod to avoid xxxInternals$.<clinit> is too large error

- airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/package.scala
- airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/FinagleTest.scala
- Currently, `convertToFinagleRequest` doesn't respect `Method`, `request path` and etc
> finagle (fix): Properly set http method and path parameters in convertToFinagleRequest

- airspec/build.sbt
- build.sbt
- sbt-airframe/build.sbt
I am not sure how long we need to support JDK8 as all known blockers have been resolved #3191, but at the same time, no urgent need exists to drop jdk8 support for a while. We can wait for merging this fix during 2023.
> breaking: Drop JDK8 Support and build for JDK11 or later

- .github/workflows/package-test.yml
- .github/workflows/release-airspec.yml
- .github/workflows/release-js.yml
- .github/workflows/release-sbt-plugin.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- .github/workflows/test.yml
- .mergify.yml
- build.sbt
Make JDK17 the default version for 24.x series because JDK11 will have no public updates from October 2024. https://endoflife.date/oracle-jdk
> breaking: Drop JDK11 support and make JDK17 the default version

- airframe-codec/src/test/scala-3/wvlet/airframe/codec/Scala3EnumCodecTest.scala
- airframe-surface/src/main/scala-2/wvlet/airframe/surface/Surface.scala
- airframe-surface/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala
- airframe-surface/src/main/scala/wvlet/airframe/surface/Surfaces.scala
> codec (feature): Support Scala 3 Enum

- airframe-surface/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala
- airframe-surface/src/main/scala/wvlet/airframe/surface/Surfaces.scala
- airframe-surface/src/test/scala-3/wvlet/airframe/surface/IntersectionTypeTest.scala
- docs/airframe-surface.md
> surface (feature): Support Scala 3 intersection types

- airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/TypeResolver.scala
- airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/TypeResolverTest.scala
```sql
SELECT id, t.name FROM A CROSS JOIN UNNEST (name) AS t (name)
```
This SQL is valid but fails to resolve with the following error:
```
wvlet.airframe.sql.SQLError: [SyntaxError] line 1:45 name is ambiguous:
- *name:string <- A.name
- *name:?
```
Because the output attribute of AliasedRelation (`t (name)`) is included in the source attributes when resolve `UNNEST (name)` here:
https://github.com/wvlet/airframe/blob/49d31bad29eccd2459eb4c02593d371c1b55082a/airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/TypeResolver.scala#L319-L321
- `r` is CrossJoin
- `r.inputAttributes` is `left.outputAttributes + right.outputAttributes`
- `right` is AliasedRelation(Unnest)
I think output attributes of AliasedRelation shouldn't be in the scope when Unnest is resolved but I didn't come up …
> airframe-sql: Resolve UNNEST earlier to prevent cyclic references

- .scalafix.conf
- airframe-di/src/main/scala/wvlet/airframe/Session.scala
- airframe-http-codegen/src/main/scala/wvlet/airframe/http/codegen/client/HttpClientGenerator.scala
- airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/GrpcContext.scala
- airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/internal/GrpcServiceBuilder.scala
- airframe-json/src/main/scala/wvlet/airframe/json/package.scala
- airframe-rx/src/main/scala/wvlet/airframe/rx/package.scala
- project/plugin.sbt
Testing scalafix.
Due to scala2/3 compatibilities, we cannot enable some common rules, but at least https://github.com/scalacenter/scalafix/issues/542 worked
> internal: Introduce scalafix

- airframe-msgpack/src/main/scala/wvlet/airframe/msgpack/spi/Value.scala
- airframe-parquet/src/main/scala/wvlet/airframe/parquet/ParquetRecordReader.scala
- airframe-parquet/src/main/scala/wvlet/airframe/parquet/ParquetSchema.scala
- airframe-parquet/src/main/scala/wvlet/airframe/parquet/ParquetWriteCodec.scala
- airframe-parquet/src/test/scala/wvlet/airframe/parquet/ParquetTest.scala
Previously ParquetWriter used MessagePack for embedding complex object data into a column. For compatibility with the Parquet ecosystem (e.g., DuckDB), using JSON is better.
> parquet (feature): Encode complex objects as JSON columns

- airframe-http/.js/src/main/scala/wvlet/airframe/http/client/JSFetchChannel.scala
- airframe-http/.js/src/main/scala/wvlet/airframe/http/client/JSHttpClientBackend.scala
- airframe-http/.js/src/test/scala/wvlet/airframe/http/client/JSHttpAsyncClientTest.scala
- airframe-http/src/main/scala/wvlet/airframe/http/client/HttpClientConfig.scala
- build.sbt
- scripts/setup-scalajs.sh
Enable using [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API), which works only in browser.
```scala
val client = Http.client.withFetchAPI.newJSClient
```
Closes #2897
> http (feature): Add an option to use Fetch API for JSHttpClient

- airframe-http/src/main/scala/wvlet/airframe/http/HttpClientException.scala
JDK's HttpClient throws IOException with "(address): GOAWAY received" error message. This PR addresses this error.
> http (fix): Fixes #3421 Retry upon GOAWAY message from HTTP/2 servers

- airframe-surface/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/i3416.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/i3419.scala
Starting with tests - I hope I will be able to implement the fix as well.
> surface (fix): Fix #3416 and #3419 - protected and package private access

- airframe-surface/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/i3418.scala
Again starting with the test, passing in Scala 2
Let us see if I will be able to fix it, this time I am not yet sure where to start.
> surface (fix): Fixes #3418 Handle surface of List of generic tuples

- airframe-surface/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala
- airframe-surface/src/test/scala/wvlet/airframe/surface/i3417.scala
Do not use `.tree` to obtain parameter types, use `typeMember` instead. The code is simpler and more reliable, avoiding issue https://github.com/scala/scala3/issues/19795 (#3417)
> surface (internal): Use .typeMember instead of .tree to get parameter types

- airframe-surface/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala
- airframe-surface/src/test/scala-3/wvlet/airframe/surface/GenericMethodTest.scala
This PR implements a test and Scala 3 fix of #3454. The major part of the fix is a simplification of `typeMappingTable` function. I am not 100% sure what the previous implementation using `method.paramSymss` was trying to do, I only hope whatever it was, it had tests in place for that.
@xerial The new test fails on Scala 2 - if you or anyone is interested in completing the fix, feel free to continue.
> surface: Fix #3454 - methods in generic classes - for Scala 3

- airframe-surface/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala
Fixes issue investigated as https://github.com/scala/scala3/issues/20072
Unfortunately there are still other issues preventing compiling with `-Xcheck-macros` (https://stackoverflow.com/questions/78193025/how-to-extract-type-parameter-from-typelambda-correctly), but this fix is an important step in that direction.
> Surface internal - Fix tree owner in `surfaceDefs` `ValDef`

- airframe-rx-html/.js/src/main/scala/wvlet/airframe/rx/html/DOMRenderer.scala
- airframe-rx-html/.js/src/test/scala/wvlet/airframe/http/rx/html/RenderErrorTest.scala
- **Reproduce vanished DOM nodes upon errors**
- **Add test case**
> rx-html (fix): Show warning logs when RxElement rendering failed

- airframe-di/.native/src/main/scala-3/wvlet/airframe/lifecycle/AddShutdownHook.scala
- airframe-di/.native/src/main/scala-3/wvlet/airframe/lifecycle/JSR250LifeCycleExecutor.scala
- airframe-log/.native/src/main/scala/wvlet/log/LogEnv.scala
- airframe-log/.native/src/main/scala/wvlet/log/LogTimestampFormatter.scala
- airframe-rx/.native/src/main/scala-3/wvlet/airframe/rx/compat.scala
- airframe-surface/.native/src/main/scala-3/wvlet/airframe/surface/SurfaceFactory.scala
- airframe-surface/.native/src/main/scala-3/wvlet/airframe/surface/package.scala
- airframe-surface/.native/src/main/scala-3/wvlet/airframe/surface/surface.scala
- airframe-surface/src/main/scala/wvlet/airframe/surface/CName.scala
- airspec/.native/src/main/scala-3/wvlet/airspec/Compat.scala
- airspec/.native/src/main/scala-3/wvlet/airspec/PlatformAirSpec.scala
- airspec/build.sbt
- airspec/project/plugin.sbt
- project/plugin.sbt
To support Scala Native, airspec needs to support Scala Native as airspec is used for testing airframe modules.
- Target only for Scala 3 for reducing the maintenance overhead
- Compilation passed, but need to check why no test class is found 
Challenges:
- No java.util.logging, which is necessary for airframe-log
- No java.util.concurrent.Executor
> airspec (internal): Prepare for Scala Native 0.5 support 

- airframe-surface/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala
- airframe-surface/src/test/scala-3/wvlet/airframe/surface/Scala3NewTypeTest.scala
The PR contains a failing test demonstrating issue. Following code fails:
```scala
object O:
opaque type InnerOpaque = Double
test("Opaque types from inner object") {
val s = Surface.of[O.InnerOpaque]
}
```
The error is:
> java.util.NoSuchElementException: key not found: wvlet.airframe.surface.Scala3NewTypeTest.O.InnerOpaque
I will try to create a fix.
> surface (fix): Fixed a bug in getting a surface of inner opaque type

- airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleRPCContext.scala
- airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/ThreadLocalStorageTest.scala
- airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/GrpcContext.scala
- airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/example/DemoApi.scala
- airframe-http-netty/src/main/scala/wvlet/airframe/http/netty/NettyBackend.scala
- airframe-http-netty/src/main/scala/wvlet/airframe/http/netty/NettyRPCContext.scala
- airframe-http-netty/src/test/scala/wvlet/airframe/http/netty/NettyBackendTest.scala
- airframe-http-netty/src/test/scala/wvlet/airframe/http/netty/NettyLoggingTest.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/Compat.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/internal/LocalRPCContext.scala
- airframe-http/.jvm/src/main/scala/wvlet/airframe/http/internal/TLSSupport.scala
- airframe-http/src/main/scala/wvlet/airframe/http/RPCContext.scala
- docs/airframe-http.md
- docs/airframe-rpc.md
- Breaking change: `RPCContext.current.getThreadLocal[A](key: String): A`  -> `RPCContext.current.getThreadLocal(key: String): Any` to avoid type cast error
- Also, fixed a bug of getting the previous thread-local values
> http (fix, breaking): RPCContext.current.getThreadLocal interface change to avoid unsafe type cast

- airspec/build.sbt
- airspec/src/main/scala/wvlet/airspec/AirSpecLauncher.scala
- airspec/src/main/scala/wvlet/airspec/runner/AirSpecSbtRunner.scala
- airspec/src/main/scala/wvlet/airspec/runner/AirSpecTaskRunner.scala
> airspec (fix): Enable -l,-L loglevel options in forked JVM tests

- airframe-surface/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala
Since Scala 3.6  context bounds would be mapped to using arguments, previously they were using implicit arguments. 
This change affects the macros which eliminate ClassTag context bound arguments. 
The issue was detected by the Scala 3 Open Community build - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/10640209328)
> Fix macros under Scala 3.6 change to context bounds

- airspec/src/main/scala/wvlet/airspec/runner/AirSpecSbtRunner.scala
- docs/airspec.md
> airspec (deprecated): Require a space in -L (pattern)=(loglevel) option

- airframe-log/.jvm/src/main/scala/wvlet/log/LogRotationHandler.scala
- airspec/build.sbt
- build.sbt
SizeAndTimeBasedFNATP of logback-core was deprecated 8 years ago.  This fix will remove its usage https://github.com/qos-ch/logback/blame/42caff87ae6eb553dcbf77e25ba87a9d340357ee/logback-core/src/main/java/ch/qos/logback/core/CoreConstants.java#L240
> Upgrade logback-core to 1.5.8

- airframe-http/src/main/scala/wvlet/airframe/http/HttpMultiMap.scala
```scala
val m = HttpMultiMap.empty
.add("key", "value1")
.add("key", "value2")
.add("key", "value3")
println(m.getAll("key")) // Vector(List(value1, value2), v, a, l, u, e, 3)
```
> http (fix): Fix a bug in HttpMultiMap.add() when more than 3 values are added with the same key

- airframe-log/src/main/scala/wvlet/log/Logger.scala
- airframe-rx-html/.js/src/main/scala/wvlet/airframe/rx/html/DOMRenderer.scala
- airframe-rx-html/.js/src/test/scala/wvlet/airframe/http/rx/html/RxOnMountTest.scala
- airframe-rx-html/.js/src/test/scala/wvlet/airframe/http/rx/html/RxRenderingTest.scala
- airframe-rx-html/src/main/scala/wvlet/airframe/rx/html/RxElement.scala
- **rx-html (breaking): RxElement.onMount(n: dom.Node) now takes a node argument**
- This is a fix for correctly calling onMount hook after the node is rendered to the document (using MutationObserver https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver)
- **Fix message**
> rx-html (breaking): RxElement.onMount(...) requires a node argument

- airframe-http/src/main/scala-3/wvlet/airframe/http/client/HttpClientCompat.scala
- airframe-http/src/main/scala/wvlet/airframe/http/client/AsyncClient.scala
- airframe-http/src/main/scala/wvlet/airframe/http/client/HttpClientContext.scala
- airframe-http/src/main/scala/wvlet/airframe/http/client/SyncClient.scala
> http (feature): Support adding HttpClientContext to Http client readAs, call, rpc methods

- airframe-http-codegen/src/main/scala/wvlet/airframe/http/openapi/OpenAPIGenerator.scala
- airframe-http-codegen/src/test/scala/wvlet/airframe/http/openapi/SimpleOpenAPITest.scala
- Update OpenAPIGenerator to handle Rx[_] return types
- Add test case for Rx[HelloRet] return type in SimpleOpenAPITest
- Ensure Rx[_] types are correctly represented in OpenAPI schema
> http (feature): Add OpenAPI schema support for Rx return types
