README.md

I added initial usage documentation.

Add usage docs

---

src/main/scala/wvlet/airframe/Design.scala
src/main/scala/wvlet/airframe/LifeCycleHook.scala
src/main/scala/wvlet/airframe/LifeCycleManager.scala
src/main/scala/wvlet/airframe/Session.scala
src/main/scala/wvlet/airframe/SessionImpl.scala

Before #12, we need to fix shutdown order of services.

[WIP] Lifecycle shutdown order

---

.gitignore
build.sbt
src/main/scala/wvlet/airframe/Binder.scala
src/main/scala/wvlet/airframe/Design.scala
src/main/scala/wvlet/airframe/SessionImpl.scala
src/main/scala/wvlet/airframe/package.scala
src/test/scala/wvlet/airframe/AirframeTest.scala
src/test/scala/wvlet/airframe/DesignTest.scala

Upgrade to wvlet 0.26

---

README.md
RELEASE_NOTES.md
build.sbt
version.sbt

Release 0.11

---

build.sbt
surface/README.md
surface/jvm/src/main/scala/wvlet/surface/reflect/ObjectBuilder.scala
surface/jvm/src/main/scala/wvlet/surface/reflect/Path.scala
surface/jvm/src/main/scala/wvlet/surface/reflect/ReflectTypeUtil.scala
surface/jvm/src/main/scala/wvlet/surface/reflect/RuntimeMethodParameter.scala
surface/jvm/src/main/scala/wvlet/surface/reflect/RuntimeSurface.scala
surface/jvm/src/main/scala/wvlet/surface/reflect/TypeConverter.scala
surface/jvm/src/main/scala/wvlet/surface/reflect/package.scala
surface/jvm/src/test/scala/wvlet/surface/reflect/PathTest.scala
surface/jvm/src/test/scala/wvlet/surface/reflect/RuntimeAnnotationTest.scala
surface/jvm/src/test/scala/wvlet/surface/reflect/RuntimeSurfaceTest.scala
surface/jvm/src/test/scala/wvlet/surface/reflect/RuntimeTaggedTypeTest.scala
surface/shared/src/main/scala/wvlet/surface/Surface.scala
surface/shared/src/main/scala/wvlet/surface/SurfaceMacros.scala
surface/shared/src/main/scala/wvlet/surface/Zero.scala
surface/shared/src/test/scala/wvlet/surface/MethodSurfaceTest.scala
surface/shared/src/test/scala/wvlet/surface/ParamTest.scala
surface/shared/src/test/scala/wvlet/surface/SurfaceSpec.scala
surface/shared/src/test/scala/wvlet/surface/SurfaceTest.scala
surface/shared/src/test/scala/wvlet/surface/TaggedTypeTest.scala
surface/shared/src/test/scala/wvlet/surface/ZeroTest.scala

This is necessary for using https://github.com/wvlet/config with the latest version of Airframe without changing the code so much.

Add reflection-based Surface generator to support Surface(ru.Type)

---

.travis.yml
build.sbt
project/plugin.sbt

This PR updates doc site (wvlet.org/airframe) in Travis CI when master branch is updated.

Automate doc update

---

build.sbt
docs/src/main/tut/docs/release-notes.md
version.sbt

Add release notes for 0.17

---

airframe-macros/shared/src/main/scala/wvlet/airframe/AirframeMacros.scala
airframe/shared/src/main/scala/wvlet/airframe/AirframeSession.scala
airframe/shared/src/main/scala/wvlet/airframe/Session.scala
airframe/shared/src/main/scala/wvlet/airframe/SessionHolder.scala
airframe/shared/src/test/scala/wvlet/airframe/AssistedInjectionTest.scala
docs/src/main/tut/docs/internals.md

Assisted injection can be implemented by properly passing session. #78

Add assisted injection example

---

airframe-macros/shared/src/main/scala/wvlet/airframe/AirframeMacros.scala
airframe/shared/src/main/scala/wvlet/airframe/LifeCycleHook.scala
airframe/shared/src/main/scala/wvlet/airframe/LifeCycleManager.scala
airframe/shared/src/main/scala/wvlet/airframe/package.scala
airframe/shared/src/test/scala/wvlet/airframe/LifeCycleManagerTest.scala
docs/src/main/tut/docs/index.md

Add beforeShutdown

---

airframe/js/src/main/scala/wvlet/airframe/JSR250LifeCycleExecutor.scala
airframe/jvm/src/main/scala/wvlet/airframe/JSR250LifeCycleExecutor.scala
airframe/jvm/src/test/scala/wvlet/airframe/JSR250LifeCycleExecutorTest.scala
airframe/shared/src/main/scala/wvlet/airframe/LifeCycleManager.scala
airframe/shared/src/main/scala/wvlet/airframe/package.scala
airframe/shared/src/test/scala/wvlet/airframe/LifeCycleManagerTest.scala
docs/src/main/tut/docs/comparison.md
docs/src/main/tut/docs/index.md

Add PostConstrct (onInit) and PreDestroy (onShutdown) 

---

airframe/shared/src/test/scala/wvlet/airframe/MapBindingTest.scala
docs/src/main/tut/docs/bindings.md

We can just use Scala for supporting path-specific binder #99

Add Multibinding example

---

build.sbt
log/jvm/src/main/scala/wvlet/log/LogRotationHandler.scala
log/jvm/src/main/scala/wvlet/log/io/IOUtil.scala
log/jvm/src/test/scala/wvlet/log/LogRotationHandlerTest.scala
project/build.properties

For making it compatible with Presto 0.188, which uses logback-core 1.2.3

Upgrade to logback-core 1.2.3 and sbt-1.0.3

---

airframe-log/README.md
airframe-log/shared/src/main/scala/wvlet/log/LogMacros.scala

ref: https://github.com/wvlet/airframe/issues/151

[log] Add option to disable code gen

---

airframe/shared/src/main/scala/wvlet/airframe/Binder.scala
airframe/shared/src/main/scala/wvlet/airframe/package.scala
airframe/shared/src/test/scala/wvlet/airframe/ProviderTest.scala
docs/src/main/tut/docs/index.md

Use singleton binding by default

---

airframe-http/src/main/scala/wvlet/airframe/http/Router.scala
airframe-json/.jvm/src/test/scala/wvlet/airframe/json/JSONScannerBenchmark.scala
airframe-json/src/main/scala/wvlet/airframe/json/JSONEventHandler.scala
airframe-json/src/main/scala/wvlet/airframe/json/JSONParseException.scala
airframe-json/src/main/scala/wvlet/airframe/json/JSONScanner.scala
airframe-json/src/main/scala/wvlet/airframe/json/JSONSource.scala
airframe-json/src/test/resources/twitter.json
airframe-json/src/test/scala/wvlet/airframe/json/JSONScannerBenchmark.scala
airframe-json/src/test/scala/wvlet/airframe/json/JSONScannerTest.scala
airframe-json/src/test/scala/wvlet/airframe/json/SimpleJSONEventHandler.scala
build.sbt

JSON pull parser implementation, which does not build JSON objects.

airframe-json 

---

airframe-codec/src/main/scala/wvlet/airframe/codec/JSONCodec.scala
airframe-codec/src/main/scala/wvlet/airframe/codec/MessageCodec.scala
airframe-codec/src/main/scala/wvlet/airframe/codec/ObjectCodec.scala
airframe-codec/src/test/scala/wvlet/airframe/codec/CodecSpec.scala
airframe-codec/src/test/scala/wvlet/airframe/codec/JSONCodecTest.scala
airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleRouter.scala
airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/package.scala
airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/FinagleRouterTest.scala
airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/FinagleTest.scala
airframe-http/src/main/scala/wvlet/airframe/http/ControllerProvider.scala
airframe-http/src/main/scala/wvlet/airframe/http/Http.scala
airframe-http/src/main/scala/wvlet/airframe/http/Router.scala
airframe-http/src/main/scala/wvlet/airframe/http/package.scala
airframe-http/src/test/scala/wvlet/airframe/http/RouterTest.scala
airframe-tablet/src/main/scala/wvlet/airframe/tablet/text/ObjectJSONCodec.scala
airframe/src/main/scala/wvlet/airframe/AirframeSession.scala
airframe/src/main/scala/wvlet/airframe/Session.scala
build.sbt

- Add default designs for airframe-http and finagle
- Cleanup interfaces
- Add finagle examples

airframe-http-finagle enhancement

---

airframe/src/main/scala/wvlet/airframe/AirframeSession.scala
airframe/src/main/scala/wvlet/airframe/Session.scala
airframe/src/main/scala/wvlet/airframe/SessionBuilder.scala
airframe/src/test/scala/wvlet/airframe/SessionTest.scala

Support bind[Design] to reference the original design

---

docs/src/main/tut/docs/index.md

I think the MyApp constructor is wrong. Am I wrong? Please confirm...

Fix MyApp constructor

---

airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/package.scala
airframe-http/src/main/scala/wvlet/airframe/http/Router.scala

This pull request fixes several typo I found in airframe-http, airframe-http-finagle.

Fix typo in http, finagle modules

---

airframe/src/main/scala/wvlet/airframe/Design.scala

See the discussion at #256 for details

Fix #256 by limiting the visibility of Design.blanc

---

.travis.yml
airframe-opts/src/main/scala/wvlet/airframe/opts/StringTemplate.scala
build.sbt

Need to wait until a new version of Scala 2.13.x, which will restore String.linesIterator: https://github.com/scala/scala/pull/7269

Use oraclejdk11

---

docs/src/main/tut/docs/index.md

Fix typo DatabaseServcie => DatabaseService.

Fix typo DatabaseService

---

airframe/src/main/scala/wvlet/airframe/package.scala
airframe/src/test/scala/example/BindSingleton.scala
airframe/src/test/scala/wvlet/airframe/ProviderTest.scala
airframe/src/test/scala/wvlet/airframe/SingletonTest.scala

Deprecate bindSingleton[X] now that bind[X] binds singletons by default

---

airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/FinagleRouterTest.scala
airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/FinagleServerFactoryTest.scala
airframe-http/src/main/scala/wvlet/airframe/http/Router.scala
airframe-http/src/main/scala/wvlet/airframe/http/RouterMacros.scala
airframe-macros/shared/src/main/scala/wvlet/airframe/AirframeMacros.scala
airframe/src/main/scala/wvlet/airframe/package.scala
docs/src/main/tut/docs/airframe-http.md

Register a trait factory when Route.of[A] is called

---

airframe-macros/shared/src/main/scala/wvlet/airframe/AirframeMacros.scala
airframe/.jvm/src/main/scala/wvlet/airframe/JSR250LifeCycleExecutor.scala
airframe/src/main/scala/wvlet/airframe/AirframeSession.scala
airframe/src/main/scala/wvlet/airframe/LifeCycleHook.scala
airframe/src/main/scala/wvlet/airframe/LifeCycleManager.scala
airframe/src/main/scala/wvlet/airframe/Session.scala
airframe/src/main/scala/wvlet/airframe/package.scala
airframe/src/test/scala/wvlet/airframe/FactoryBindingTest.scala
airframe/src/test/scala/wvlet/airframe/LifeCycleManagerTest.scala
airframe/src/test/scala/wvlet/airframe/ProviderTest.scala

Deprecate in-traint bindInstance[X]

---

airframe-jdbc/src/test/scala/wvlet/airframe/jdbc/ConnectionPoolFactoryTest.scala
airframe-spec/shared/src/main/scala/wvlet/airframe/AirframeSpec.scala
airframe/src/main/scala/wvlet/airframe/AirframeSession.scala
airframe/src/main/scala/wvlet/airframe/Design.scala
airframe/src/main/scala/wvlet/airframe/LifeCycleManager.scala
airframe/src/main/scala/wvlet/airframe/Session.scala
airframe/src/main/scala/wvlet/airframe/SessionBuilder.scala
airframe/src/test/scala/wvlet/airframe/ChildSessionTest.scala
docs/src/main/tut/docs/index.md

Child session support

---

airframe-config/src/test/scala/wvlet/airframe/config/ConfigOverrideTest.scala
airframe-jdbc/src/main/scala/wvlet/airframe/jdbc/ConnectionPool.scala
airframe-jdbc/src/main/scala/wvlet/airframe/jdbc/DbConfig.scala
airframe-jdbc/src/test/scala/wvlet/airframe/jdbc/ConnectionPoolFactoryTest.scala
docs/src/main/tut/docs/airframe-jdbc.md

#133: Add DbConfig helper

---

airframe/src/main/scala/wvlet/airframe/Design.scala
airframe/src/main/scala/wvlet/airframe/SessionBuilder.scala
airframe/src/test/scala/wvlet/airframe/SessionTest.scala

Check Design duplicates right before building a new Session

---

airframe-log/jvm/src/main/scala/wvlet/log/LogTimestampFormatter.scala

Add milli-sec to log formats

---

airframe-config/src/main/scala/wvlet/airframe/config/DesignOptionsWithConfig.scala
airframe-log/jvm/src/main/scala/wvlet/log/AirframeLogManager.scala
airframe-log/shared/src/main/scala/wvlet/log/Logger.scala
airframe/.jvm/src/main/scala/wvlet/airframe/AddShutdownHook.scala
airframe/src/main/scala/wvlet/airframe/AirframeSession.scala
airframe/src/main/scala/wvlet/airframe/Design.scala
airframe/src/main/scala/wvlet/airframe/LifeCycleEventHandler.scala
airframe/src/main/scala/wvlet/airframe/LifeCycleManager.scala
airframe/src/main/scala/wvlet/airframe/Session.scala
airframe/src/main/scala/wvlet/airframe/SessionBuilder.scala

Shutdown log manager

---

airframe-codec/.jvm/src/test/scala/wvlet/airframe/codec/ObjectCodecTest.scala
airframe-codec/src/main/scala/wvlet/airframe/codec/ObjectCodec.scala
airframe-launcher/src/main/scala/wvlet/airframe/launcher/Launcher.scala
airframe-launcher/src/test/scala/wvlet/airframe/launcher/ArgProcessorTest.scala
airframe-surface/jvm/src/main/scala/wvlet/airframe/surface/reflect/ReflectMethodSurface.scala
airframe-surface/jvm/src/main/scala/wvlet/airframe/surface/reflect/RuntimeMethodParameter.scala
airframe-surface/shared/src/main/scala/wvlet/airframe/surface/Surface.scala

Fix finding the method default values

---

airframe-launcher/src/main/scala/wvlet/airframe/launcher/OptionParser.scala
airframe-launcher/src/main/scala/wvlet/airframe/launcher/StringTree.scala
airframe-launcher/src/main/scala/wvlet/airframe/launcher/StringTreeCodec.scala
airframe-launcher/src/test/scala/wvlet/airframe/launcher/ArgProcessorTest.scala
airframe-launcher/src/test/scala/wvlet/airframe/launcher/StringTreeTest.scala
airframe-spec/shared/src/main/scala/wvlet/airframe/AirframeSpec.scala

- And also simplifying ValueHolder as StringTree

Fix array argument mapping

---

airframe-stream/src/main/scala/wvlet/airframe/stream/spi/SQLModel.scala
airframe-stream/src/main/scala/wvlet/airframe/stream/sql/SQLPrinter.scala
airframe-stream/src/main/scala/wvlet/airframe/stream/sql/parser/SQLInterpreter.scala
airframe-stream/src/main/scala/wvlet/airframe/stream/sql/parser/SQLParser.scala
airframe-stream/src/test/scala/wvlet/airframe/stream/sql/parser/SQLParserTest.scala
airframe-stream/src/test/scala/wvlet/airframe/stream/sql/parser/SQLPrinterTest.scala
airframe-stream/src/test/scala/wvlet/airframe/stream/sql/parser/SQLTokenizerTest.scala

- Fixed SQL models for TPC-H and TPC-DS
- Add SQLPrinter to generate SQL from SQLModel

Add roundtrip tests: SQL -> Model -> SQL' -> Model'

---

airframe/src/main/scala/wvlet/airframe/Session.scala
airframe/src/test/scala/example/BindFactory.scala

Allows to use bindFactory outside of wvlet.airframe package

---

airframe-control/src/main/scala/wvlet/airframe/control/Control.scala
airframe-control/src/test/scala/wvlet/airframe/control/ControlTest.scala

Not ignore resource closing exception in withResource

---

docs/src/main/tut/docs/airframe-config.md

fix typo in docs

---

airframe/src/main/scala/wvlet/airframe/Airframe.scala
airframe/src/main/scala/wvlet/airframe/Design.scala
airframe/src/main/scala/wvlet/airframe/package.scala
airframe/src/test/scala/wvlet/airframe/DesignTest.scala

Add Design.empty

---

airframe-codec/.jvm/src/test/scala/wvlet/airframe/codec/JSONCodecTest.scala
airframe-codec/.jvm/src/test/scala/wvlet/airframe/codec/ObjectCodecTest.scala
airframe-codec/src/main/scala/wvlet/airframe/codec/MessageCodec.scala

Add MessageCodec.unpackJson

---

airframe-codec/.jvm/src/main/scala/wvlet/airframe/codec/JDBCCodec.scala
airframe-codec/.jvm/src/test/scala/wvlet/airframe/codec/JDBCCodecTest.scala
airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRecord.scala
airframe-tablet/src/main/scala/wvlet/airframe/tablet/jdbc/ResultSetReader.scala

Add ResultSetCodec.toJsonSeq

---

airframe-codec/.jvm/src/test/scala/wvlet/airframe/codec/CollectionCodecTest.scala
airframe-codec/src/main/scala/wvlet/airframe/codec/CollectionCodec.scala

Support reading String as JSON array or map

---

airframe-macros/src/main/scala/wvlet/airframe/AirframeMacros.scala
airframe/src/test/scala/wvlet/airframe/AirframeTest.scala

Fix bind instance error

---

airframe-fluentd/src/main/scala/wvlet/airframe/fluentd/Fluentd.scala
airframe-fluentd/src/main/scala/wvlet/airframe/fluentd/FluentdLogger.scala
airframe-fluentd/src/main/scala/wvlet/airframe/fluentd/MetricLogger.scala
airframe-fluentd/src/main/scala/wvlet/airframe/fluentd/package.scala
airframe-fluentd/src/test/scala/wvlet/airframe/fluentd/FluencyTest.scala
build.sbt

Fluentd output check

---

airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleServer.scala
airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/package.scala
airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/FinagleRouterTest.scala
airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/FinagleServerFactoryTest.scala
airframe-http/README.md
airframe/src/main/scala/wvlet/airframe/AirframeSession.scala
airframe/src/main/scala/wvlet/airframe/Session.scala

airframe-http-finagle: Support adding tracing to FinagleServer

---

airframe-control/README.md
airframe-control/src/main/scala/wvlet/airframe/control/parallel/package.scala
airframe-control/src/test/scala/wvlet/airframe/control/ParallelTest.scala

airframe-control: Implicit classes for parallel map

---

airframe-codec/.jvm/src/test/scala/wvlet/airframe/codec/MetricsCodecTest.scala
airframe-metrics/shared/src/main/scala/wvlet/airframe/metrics/DataSize.scala
airframe-surface/shared/src/main/scala/wvlet/airframe/surface/Zero.scala
build.sbt

airframe-surface: Add Zero.register(surface, A)

---

airframe-codec/.jvm/src/test/scala/wvlet/airframe/codec/ValueCodecTest.scala
airframe-codec/src/main/scala/wvlet/airframe/codec/PrimitiveCodec.scala
airframe-msgpack/src/main/scala/wvlet/airframe/msgpack/spi/Value.scala
airframe-msgpack/src/main/scala/wvlet/airframe/msgpack/spi/package.scala

airframe-code: Support MsgPack as parameter codec

---

airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleServer.scala
airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/FinagleRouterTest.scala

airframe-http: Show the cause of an internal server error

---

airframe-codec/src/main/scala/wvlet/airframe/codec/JSONCodec.scala
airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleRouter.scala
airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/package.scala
airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/FinagleRouterTest.scala
airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/FinagleTest.scala
airframe-http/src/main/scala/wvlet/airframe/http/Http.scala
airframe-http/src/main/scala/wvlet/airframe/http/Router.scala

Support non-JSON content body

---

airframe-log/jvm/src/main/scala/wvlet/log/LogLevelScanner.scala
airframe-log/jvm/src/main/scala/wvlet/log/io/Resource.scala
airframe-log/jvm/src/test/scala/wvlet/log/LogLevelScannerTest.scala

Remove Stream[X] usage for Scala 2.13.0 compatibility

---

airframe/src/main/scala/wvlet/airframe/Design.scala
build.sbt

Add a workaround for Java serializer + sbt classloader + Scala 2.13.0-RC1 failure

---

.travis.yml
build.sbt

Upgrade to Scala 2.13.0

---

airframe-jmx/src/main/scala/wvlet/airframe/jmx/JMXUtil.scala
airframe-log/jvm/src/test/scala/wvlet/log/LoggerJMXTest.scala
airframe-spec/shared/src/main/scala/wvlet/airframe/AirframeSpec.scala
airframe/.jvm/src/main/scala/wvlet/airframe/AddShutdownHook.scala
build.sbt
project/build.properties

Upgrade to sbt-1.3.0-RC2

---

airframe-canvas/src/main/scala/wvlet/airframe/canvas/DirectByteBufferAccess.scala
airframe-jdbc/src/main/scala/wvlet/airframe/jdbc/SQLiteConnectionPool.scala
airframe-jmx/src/main/scala/wvlet/airframe/jmx/JMXUtil.scala
airframe-surface/jvm/src/main/scala/wvlet/airframe/surface/reflect/ReflectTypeUtil.scala

Revert "Use context class loader to fix sbt/sbt#4760"

---

airframe-canvas/src/main/scala/wvlet/airframe/canvas/Memory.scala
airframe-control/src/main/scala/wvlet/airframe/control/Shell.scala
airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleServer.scala
airframe-msgpack-benchmark/src/main/scala/wvlet/airframe/benchmark/msgpack/MsgpackBenchmark.scala
airframe-msgpack-benchmark/src/main/scala/wvlet/airframe/benchmark/msgpack/MsgpackBenchmarkMain.scala
airframe/src/main/scala/wvlet/airframe/tracing/Tracer.scala
examples/src/main/scala/wvlet/airframe/examples/di/DI_02_ConstructorInjection.scala
examples/src/main/scala/wvlet/airframe/examples/di/DI_08_OverrideBinding.scala
examples/src/main/scala/wvlet/airframe/examples/di/DI_10_TypeAliasBinding.scala

procedure syntax is deprecated https://github.com/scala/scala/commit/1d4d901fcea0a162cd139836b246e85cc0130a6b

fix procedure syntax

---

airframe-codec/.jvm/src/test/scala/wvlet/airframe/codec/MessageCodecTest.scala
airframe-codec/src/main/scala/wvlet/airframe/codec/CodecMacros.scala
airframe-codec/src/main/scala/wvlet/airframe/codec/MessageCodec.scala
airframe-codec/src/main/scala/wvlet/airframe/codec/MessageCodecFactory.scala

Move to/fromJson to MessageCodecFactory to use custom codecs

Add convenient methods to convert JSON <-> Scala object

---

.travis.yml
airframe-config/src/main/scala/wvlet/airframe/config/Config.scala
airframe-config/src/main/scala/wvlet/airframe/config/package.scala
airframe-config/src/test/scala/wvlet/airframe/config/ConfigPackageTest.scala
airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRecorder.scala
airframe-macros/src/main/scala/wvlet/airframe/AirframeMacros.scala
airframe/src/main/scala/wvlet/airframe/AirframeException.scala
airframe/src/main/scala/wvlet/airframe/AirframeSession.scala
airframe/src/main/scala/wvlet/airframe/Binder.scala
airframe/src/main/scala/wvlet/airframe/Design.scala
airframe/src/main/scala/wvlet/airframe/Session.scala
airframe/src/main/scala/wvlet/airframe/SourceCode.scala
airframe/src/main/scala/wvlet/airframe/package.scala

This PR is for showing the source code location when some binding error happens:
```
[MISSING_DEPENDENCY] Binding for String at AirframeTest.scala:253 is not found: String  - (AirframeTest.scala:371)
```
This also embeds SourceCode information where the binding is defined in the design. It will be shown at trace log when AirframeSession resolves the dependency. This information will be useful to draw dependency graphs of DI, which will be in another PR.

airframe-di: Show binding line numbers

---

airframe-control/src/main/scala/wvlet/airframe/control/OSType.scala
airframe-control/src/main/scala/wvlet/airframe/control/Shell.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpStatus.scala
airframe-launcher/src/main/scala/wvlet/airframe/launcher/HelpMessagePrinter.scala
airframe-launcher/src/main/scala/wvlet/airframe/launcher/OptionSchema.scala
airframe-msgpack-benchmark/src/main/scala/wvlet/airframe/benchmark/msgpack/MsgpackBenchmark.scala
airframe-msgpack-benchmark/src/main/scala/wvlet/airframe/benchmark/msgpack/MsgpackBenchmarkMain.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/Graph.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/TableGraph.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/model/Expression.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlan.scala
airframe/src/main/scala/wvlet/airframe/Session.scala

add type annotations with Unit/String/Boolean

fix type annotation syntax

---

airframe-json/src/main/scala/wvlet/airframe/json/JSON.scala
airframe-json/src/main/scala/wvlet/airframe/json/package.scala
airframe-json/src/test/scala/wvlet/airframe/json/JSONTest.scala

Added following methods:
- `JSONObject.get()`
- `JSONArray.apply()`
Also added JSON extraction DSL for ease:
```scala
val json = """{"user": [{ "id": 1 }, { "id": 2 }]}"""
val id = (JSON.parse(json) / "user" / "id")(0).value.asInstanceOf[Long] // => 1
```

DSL for JSON extraction

---

airframe-http/README.md

Tried with airframe-http-finagle 19.7.1

Fixed compile errors

---

airframe-metrics/jvm/src/main/scala/wvlet/airframe/metrics/TimeWindow.scala
airframe-metrics/jvm/src/test/scala/wvlet/airframe/metrics/TimeWindowTest.scala

- Calculate diff TimeWindow between start and end.
https://github.com/wvlet/airframe/issues/528#issuecomment-508300291

add kinds of diff method in TimeWindow

---

airframe-json/README.md

Fix airframe-json README typo

---

airframe-config/README.md

Fix airframe-config README typo

---

airframe-json/src/main/scala/wvlet/airframe/json/JSONParseException.scala
airframe-json/src/main/scala/wvlet/airframe/json/JSONValueBuilder.scala
airframe-json/src/test/scala/wvlet/airframe/json/JSONParserTest.scala
build.sbt

airframe-json: Add IntegerOverflow exception

---

airframe-surface/jvm/src/test/scala/wvlet/airframe/surface/ClassSurfaceTest.scala
airframe-surface/jvm/src/test/scala/wvlet/airframe/surface/SurfaceJVMTest.scala
airframe-surface/jvm/src/test/scala/wvlet/airframe/surface/reflect/PathTest.scala
airframe-surface/jvm/src/test/scala/wvlet/airframe/surface/reflect/RuntimeAnnotationTest.scala
airframe-surface/jvm/src/test/scala/wvlet/airframe/surface/reflect/RuntimeSurfaceTest.scala
airframe-surface/jvm/src/test/scala/wvlet/airframe/surface/reflect/RuntimeTaggedTypeTest.scala
airframe-surface/shared/src/test/scala/wvlet/airframe/surface/CNameTest.scala
airframe-surface/shared/src/test/scala/wvlet/airframe/surface/MethodSurfaceTest.scala
airframe-surface/shared/src/test/scala/wvlet/airframe/surface/MultipleConstructorArgsTest.scala
airframe-surface/shared/src/test/scala/wvlet/airframe/surface/ParamTest.scala
airframe-surface/shared/src/test/scala/wvlet/airframe/surface/RecursiveHigherKindTypeTest.scala
airframe-surface/shared/src/test/scala/wvlet/airframe/surface/RecursiveSurfaceTest.scala
airframe-surface/shared/src/test/scala/wvlet/airframe/surface/SurfaceSpec.scala
airframe-surface/shared/src/test/scala/wvlet/airframe/surface/SurfaceTest.scala
airframe-surface/shared/src/test/scala/wvlet/airframe/surface/TaggedTypeTest.scala
airframe-surface/shared/src/test/scala/wvlet/airframe/surface/ZeroTest.scala
build.sbt

Use AirSpec for airframe-surface tests

---

airframe-log/js/src/main/scala/wvlet/log/LogEnv.scala
airframe-log/jvm/src/main/scala/wvlet/log/LogEnv.scala
airframe-log/jvm/src/test/scala/wvlet/log/LoggerJMXTest.scala
airframe-log/shared/src/main/scala/wvlet/log/LogEnvBase.scala
airframe-log/shared/src/test/scala/wvlet/log/Spec.scala
airframe-surface/jvm/src/main/scala/wvlet/airframe/surface/reflect/MethodCallBuilder.scala
build.sbt

For resolving cyclic dependencies #591

Make Airspec a standalone project

---

airframe-di-macros/src/main/scala/wvlet/airframe/SourceCode.scala
airframe-log/js/src/main/scala/wvlet/log/JSLogger.scala
airframe-log/shared/src/test/scala/wvlet/log/LoggerTest.scala
airframe-surface/jvm/src/test/scala/wvlet/airframe/surface/SurfaceJVMTest.scala
airframe-surface/jvm/src/test/scala/wvlet/airframe/surface/reflect/RuntimeAnnotationTest.scala
airframe-surface/jvm/src/test/scala/wvlet/airframe/surface/reflect/RuntimeSurfaceTest.scala
airframe-surface/shared/src/main/scala/wvlet/airframe/surface/SurfaceMacros.scala
airframe-surface/shared/src/test/scala/wvlet/airframe/surface/MethodSurfaceTest.scala
airframe-surface/shared/src/test/scala/wvlet/airframe/surface/SurfaceTest.scala
airframe-surface/shared/src/test/scala/wvlet/airframe/surface/ZeroTest.scala
airspec/README.md
airspec/src/main/scala/wvlet/airframe/spec/AirSpec.scala
airspec/src/main/scala/wvlet/airframe/spec/AirSpecMacros.scala
airspec/src/main/scala/wvlet/airframe/spec/runner/AirSpecLogger.scala
airspec/src/main/scala/wvlet/airframe/spec/spi/Asserts.scala
airspec/src/main/scala/wvlet/airframe/spec/spi/RichAsserts.scala
airspec/src/test/scala/examples/ShouldBeTest.scala
airspec/src/test/scala/examples/TestSpec.scala

airspec: shouldBe matchers

---

airframe-log/shared/src/main/scala/wvlet/log/Logger.scala
airspec/src/main/scala/wvlet/airspec/runner/AirSpecLogger.scala
airspec/src/main/scala/wvlet/airspec/runner/AirSpecRunner.scala
airspec/src/main/scala/wvlet/airspec/runner/AirSpecTask.scala
airspec/src/main/scala/wvlet/airspec/runner/AirSpecTaskRunner.scala

- Share the task logger
- Fix concurrent log handler configuration issue

airspec: Fix duplicated log message issue

---

build.sbt

For using AirSpec as a standalone library

airspec: Add airspec-light project settings

---

airframe-surface/jvm/src/main/scala/wvlet/airframe/surface/reflect/ReflectSurfaceFactory.scala
airframe-surface/shared/src/main/scala/wvlet/airframe/surface/SurfaceMacros.scala
airframe/src/test/scala/wvlet/airframe/HigherKindTypeTest.scala
airframe/src/test/scala/wvlet/airframe/SingletonTest.scala
airspec/.jvm/src/test/scala/wvlet/airspec/TestExtension.scala
airspec/src/main/scala/wvlet/airspec/AirSpec.scala
airspec/src/main/scala/wvlet/airspec/spi/PropertyCheck.scala
airspec/src/test/scala/examples/DITest.scala
build.sbt

airspec: Support AirSpec.design, localDesign

---

project/build.properties

- This version includes a fix for slow publishing to Sonatype NEXUS https://github.com/sbt/librarymanagement/pull/317

Upgrade to sbt 1.3.0-RC5

---

airframe-json/src/main/scala/wvlet/airframe/json/JSON.scala
airframe-json/src/main/scala/wvlet/airframe/json/JSONScanner.scala
airframe-msgpack/.jvm/src/test/scala/wvlet/airframe/msgpack/json/JSONToMessagePackConverterTest.scala
airframe-msgpack/src/main/scala/wvlet/airframe/msgpack/json/JSONToMessagePackConverter.scala
airframe-msgpack/src/main/scala/wvlet/airframe/msgpack/spi/MessagePack.scala
airframe-msgpack/src/main/scala/wvlet/airframe/msgpack/spi/Value.scala
airframe-msgpack/src/test/scala/wvlet/airframe/msgpack/json/JSONToMessagePackConverterTest.scala
airframe-msgpack/src/test/scala/wvlet/airframe/msgpack/spi/ValueTest.scala
build.sbt

This PR adds an efficient conversion method from JSON to msgpack
cc: @takezoe

Add a stream json-msgpack converter

---

airframe-di-macros/src/main/scala/wvlet/airframe/AirframeMacros.scala
airframe-surface/jvm/src/main/scala/wvlet/airframe/surface/reflect/ReflectSurfaceFactory.scala
airframe/src/main/scala/wvlet/airframe/AirframeException.scala
airframe/src/main/scala/wvlet/airframe/LifeCycleManager.scala
airframe/src/test/scala/wvlet/airframe/LifeCycleManagerTest.scala

airframe-di: throw exceptions occurred at shutdown hooks later

---

airframe-di-macros/src/main/scala/wvlet/airframe/AirframeMacros.scala
airframe/src/main/scala/wvlet/airframe/AirframeSession.scala
airframe/src/main/scala/wvlet/airframe/Binder.scala
airframe/src/main/scala/wvlet/airframe/Design.scala
airframe/src/main/scala/wvlet/airframe/LifeCycleManager.scala
airframe/src/main/scala/wvlet/airframe/package.scala
airframe/src/test/scala/wvlet/airframe/DesignTimeLifeCycleHookTest.scala
airspec/README.md
examples/src/test/scala/wvlet/airframe/examples/airspec/AirSpec_03_DI.scala

airframe-di: #651 Support design-time lifecycle hooks

---

airframe/src/main/scala/wvlet/airframe/AirframeSession.scala
airframe/src/main/scala/wvlet/airframe/LifeCycle.scala
airframe/src/main/scala/wvlet/airframe/LifeCycleManager.scala
airframe/src/main/scala/wvlet/airframe/package.scala
airframe/src/test/scala/wvlet/airframe/AirframeTest.scala
airframe/src/test/scala/wvlet/airframe/LifeCycleManagerTest.scala
airframe/src/test/scala/wvlet/airframe/SingletonTest.scala

airframe-di: Add Lifecycle interface

---

airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleClient.scala
airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleResponseHandler.scala
airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/FinagleRouterTest.scala

airframe-http-finagle: Support Reader[Buf] stream response

---

airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleClient.scala
airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleResponseHandler.scala
airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/FinagleRouterTest.scala

- Add nativeClient 
- Do not call setChunked multiple times

aiframe-http: streaming fixes

---

.travis.yml
build.sbt
sbt
scripts/release.sh

- https://github.com/scala/scala/releases/tag/v2.12.10

Upgrade to Scala 2.12.10

---

.travis.yml

https://twitter.com/alxarchambault/status/1172609389439725568

Cache only .cache folder for coursier

---

airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleClient.scala
airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/FinagleClientTest.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpClient.scala

airframe-http: Support patch, patchOps, deleteOps methods

---

airframe-codec/.js/src/main/scala/wvlet/airframe/codec/Compat.scala
airframe-codec/.jvm/src/main/scala/wvlet/airframe/codec/Compat.scala
airframe-codec/.jvm/src/test/scala/wvlet/airframe/codec/ObjectCodecTest.scala
airframe-codec/src/main/scala/wvlet/airframe/codec/ObjectCodec.scala
airframe-codec/src/main/scala/wvlet/airframe/codec/required.java
airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleServer.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpServerException.scala
airframe-http/src/main/scala/wvlet/airframe/http/Route.scala
airframe-surface/jvm/src/main/scala/wvlet/airframe/surface/reflect/RuntimeMethodParameter.scala
airframe-surface/jvm/src/main/scala/wvlet/airframe/surface/reflect/package.scala
airframe-surface/shared/src/main/scala/wvlet/airframe/surface/Surface.scala
airframe-surface/shared/src/main/scala/wvlet/airframe/surface/SurfaceMacros.scala
airframe-surface/shared/src/main/scala/wvlet/airframe/surface/Surfaces.scala
airframe-surface/shared/src/main/scala/wvlet/airframe/surface/required.java
airframe-surface/shared/src/test/scala/wvlet/airframe/surface/RequiredParamTest.scala

airframe-codec: Add @required to mark must-have parameters

---

airframe-codec/.js/src/main/scala/wvlet/airframe/codec/Compat.scala
airframe-codec/.jvm/src/main/scala/wvlet/airframe/codec/Compat.scala
airframe-codec/.jvm/src/main/scala/wvlet/airframe/codec/JVMCodecFactory.scala
airframe-codec/.jvm/src/main/scala/wvlet/airframe/codec/JavaTimeCodec.scala
airframe-codec/.jvm/src/test/scala/wvlet/airframe/codec/MessageCodecTest.scala
airframe-codec/.jvm/src/test/scala/wvlet/airframe/codec/ValueCodecTest.scala
airframe-codec/src/main/scala/wvlet/airframe/codec/CollectionCodec.scala
airframe-codec/src/test/scala/wvlet/airframe/codec/CodecSpec.scala
airframe-codec/src/test/scala/wvlet/airframe/codec/CollectionCodecTest.scala
airframe-codec/src/test/scala/wvlet/airframe/codec/InnerClassCodecTest.scala
airframe-codec/src/test/scala/wvlet/airframe/codec/JSONCodecTest.scala
airframe-codec/src/test/scala/wvlet/airframe/codec/ObjectCodecTest.scala
airframe-codec/src/test/scala/wvlet/airframe/codec/PrimitiveCodecTest.scala
airframe-codec/src/test/scala/wvlet/airframe/codec/ScalaStandardCodecTest.scala
airframe-msgpack/.js/src/main/scala/wvlet/airframe/msgpack/spi/Compat.scala
airframe-msgpack/.jvm/src/main/scala/wvlet/airframe/msgpack/impl/PackerImpl.scala
airframe-msgpack/.jvm/src/main/scala/wvlet/airframe/msgpack/spi/Compat.scala
airframe-msgpack/.jvm/src/test/scala/wvlet/airframe/msgpack/json/JSONToMessagePackConverterTest.scala
airframe-msgpack/src/main/scala/wvlet/airframe/msgpack/impl/PureScalaBufferPacker.scala
airframe-msgpack/src/main/scala/wvlet/airframe/msgpack/impl/PureScalaBufferUnpacker.scala
airframe-msgpack/src/main/scala/wvlet/airframe/msgpack/io/ByteArrayBuffer.scala
airframe-msgpack/src/main/scala/wvlet/airframe/msgpack/spi/OffsetPacker.scala
airframe-msgpack/src/main/scala/wvlet/airframe/msgpack/spi/OffsetUnpacker.scala
airframe-msgpack/src/main/scala/wvlet/airframe/msgpack/spi/ReadCursor.scala
airframe-msgpack/src/main/scala/wvlet/airframe/msgpack/spi/WriteCursor.scala
airframe-msgpack/src/test/scala/wvlet/airframe/msgpack/io/ByteArrayBufferTest.scala

Necessary for using airframe-codec in Scala.js

airframe-msgpack: Pure Scala packer/unpacker

---

airframe-config/src/main/scala/wvlet/airframe/config/package.scala

This enables us to use `Config.overrideWithProperties()` on `Design` as follows:
```scala
module
.withConfigEnv(env = "production", defaultEnv = "default")
.bindConfigFromYaml[LogConfig]("access-log.yml")
.bindConfigFromYaml[ServerConfig]("server.yml")
.overrideConfigWithPropertiesFile("config/test.properties")
```

Airframe DI integration for Config.overrideConfigWithPropertiesFile()

---

airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleBackend.scala
airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/FinagleRouterTest.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpBackend.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpRequestDispatcher.scala

airframe-http: #796 Support returning Scala Future

---

airframe-control/README.md
airframe-control/src/main/scala/wvlet/airframe/control/Retry.scala
airframe-control/src/test/scala/wvlet/airframe/control/RetryTest.scala

airframe-control: #767 Add bounded backoff retry

---

airframe-di-macros/src/main/scala/wvlet/airframe/AirframeMacros.scala
airframe/README.md
airframe/src/main/scala/wvlet/airframe/package.scala
airframe/src/test/scala/wvlet/airframe/BindLocalTest.scala

airframe-di: Add in-trait bindLocal

---

airframe-launcher/src/main/scala/wvlet/airframe/launcher/HelpMessagePrinter.scala
airframe-launcher/src/main/scala/wvlet/airframe/launcher/Launcher.scala
airframe-launcher/src/test/scala/wvlet/airframe/launcher/LauncherTest.scala

airframe-launcher: #523 Add coloring to the help message

---

airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleClient.scala
airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/FinagleClientTest.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpClient.scala

Add some convenient methods to `HttpClient` for handling a raw response.

Add raw response methods to HttpClient

---

airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/LeafFilterTest.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpFilter.scala
airframe-http/src/main/scala/wvlet/airframe/http/Router.scala
airframe-http/src/main/scala/wvlet/airframe/http/router/HttpRequestDispatcher.scala

airframe-http: Support leaf filters without @Endpoint mapping

---

airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/InOutTableFinder.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/Optimizer.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/QuerySignature.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/SQLAnalyzer.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/SQLAnonymizer.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/TypeResolver.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/catalog/Catalog.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/catalog/DataType.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/model/Expression.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlan.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlanPrinter.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/model/ResolvedPlan.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/model/TreeNode.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/parser/SQLGenerator.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/parser/SQLInterpreter.scala
airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/SQLAnalyzerTest.scala
airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/SQLAnonymizerTest.scala
airframe-sql/src/test/scala/wvlet/airframe/sql/catalog/DataTypeTest.scala
airframe-sql/src/test/scala/wvlet/airframe/sql/parser/SQLParserTest.scala
build.sbt

Extends airframe-sql https://github.com/wvlet/airframe/tree/master/airframe-sql
- Resolve input/output columns names of operators from table schema
- Pushdown column accesses of each operator
Related:
- https://github.com/prestosql/presto/blob/master/presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PruneUnreferencedOutputs.java

[WIP] SQL typer

---

.github/workflows/release-js.yml
.github/workflows/test.yml
airframe/.jvm/src/main/scala/wvlet/airframe/lifecycle/AddShutdownHook.scala
build.sbt

Follow-up of #869 
It will close #868

Publish Scala.js binaries for Scala 2.13

---

airframe-http-finagle/src/test/resources/wvlet/airframe/http/finagle/static2/index2.html
airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/StaticContentTest.scala
airframe-http/src/main/scala/wvlet/airframe/http/StaticContent.scala
docs/airframe-http.md

airframe-http: #865 Support multiple static content paths

---

airframe-http/src/main/scala/wvlet/airframe/http/router/RouteMatcher.scala
airframe-http/src/test/scala/wvlet/airframe/http/PathSequenceTest.scala

airframe-http: #864 Support empty strings for /*path endpoint

---

.github/workflows/release-js.yml
build.sbt
project/plugin.sbt
scripts/publish.sh

To be consistent with other Scala.js projects

Rename SCALA_JS_VERSION -> SCALAJS_VESRION

---

airframe-config/src/test/scala/wvlet/airframe/config/AirframeBootstrapTest.scala
airframe-surface/jvm/src/main/scala/wvlet/airframe/surface/reflect/RuntimeMethodParameter.scala
airframe-surface/shared/src/test/scala/wvlet/airframe/surface/ParamTest.scala

airframe-surface: Fix private field access

---

airframe-config/src/main/scala/wvlet/airframe/config/Config.scala
airframe-config/src/main/scala/wvlet/airframe/config/PropertiesConfig.scala
airframe-jdbc/src/test/resources/config.properties
airframe-jdbc/src/test/resources/dbconfig.yml
airframe-jdbc/src/test/scala/wvlet/airframe/jdbc/DbConfigTest.scala
airframe-surface/jvm/src/main/scala/wvlet/airframe/surface/reflect/ObjectBuilder.scala

airframe-config: various Config mapping improvement

---

airspec/.js/src/main/scala/wvlet/airspec/Compat.scala
airspec/.jvm/src/main/scala/wvlet/airspec/Compat.scala
airspec/src/main/scala/wvlet/airspec/AirSpec.scala
airspec/src/main/scala/wvlet/airspec/AirSpecLauncher.scala
airspec/src/main/scala/wvlet/airspec/CompatApi.scala
airspec/src/main/scala/wvlet/airspec/Framework.scala
airspec/src/main/scala/wvlet/airspec/runner/AirSpecEventHandler.scala
airspec/src/main/scala/wvlet/airspec/runner/AirSpecSbtRunner.scala
airspec/src/main/scala/wvlet/airspec/runner/AirSpecTask.scala
airspec/src/main/scala/wvlet/airspec/runner/AirSpecTaskRunner.scala
airspec/src/test/scala/wvlet/airspec/AirSpecLauncherTest.scala

Airspec: Add AirSpecLauncher for standalone testing

---

.github/workflows/release-js.yml
.github/workflows/test.yml
build.sbt
project/plugin.sbt

Upgrade to Scala.js 1.0.0

---

airspec/.js/src/main/scala/wvlet/airspec/Compat.scala
airspec/.js/src/main/scala/wvlet/airspec/spi/JsObjectMatcher.scala
airspec/.js/src/test/scala/jsexamples/JSMatcherTest.scala
airspec/.jvm/src/main/scala/wvlet/airspec/Compat.scala
airspec/src/main/scala/wvlet/airspec/CompatApi.scala
airspec/src/main/scala/wvlet/airspec/spi/Asserts.scala
airspec/src/main/scala/wvlet/airspec/spi/RichAsserts.scala

airspec: Support js.Object matcher

---

airframe-config/src/main/scala/wvlet/airframe/config/Config.scala
airframe-jdbc/src/main/scala/wvlet/airframe/jdbc/DbConfig.scala
airframe-surface/jvm/src/main/scala/wvlet/airframe/surface/reflect/RuntimeMethodParameter.scala
airframe-surface/shared/src/main/scala/wvlet/airframe/surface/Surface.scala
airframe-surface/shared/src/main/scala/wvlet/airframe/surface/SurfaceMacros.scala
airframe-surface/shared/src/main/scala/wvlet/airframe/surface/Surfaces.scala
airframe-surface/shared/src/main/scala/wvlet/airframe/surface/secret.java
airframe-surface/shared/src/test/scala/wvlet/airframe/surface/SecretParamTest.scala

Moved `@secret` annotation to wvlet.airframe.surface package.

---

airframe-rx/.js/src/main/scala/wvlet/airframe/rx/html/DOMRenderer.scala
airframe-rx/.js/src/test/scala/wvlet/airframe/rx/html/HtmlTest.scala

airframe-rx: #961 Support add/overwrite of DOM attributes

---

airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleClient.scala
airframe-http/.js/src/main/scala/wvlet/airframe/http/Compat.scala
airframe-http/.js/src/main/scala/wvlet/airframe/http/js/JSHttpClient.scala
airframe-http/.js/src/test/scala/wvlet/airframe/http/js/JSHttpClientTest.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/Compat.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/client/ScalaHttpClient.scala
airframe-http/src/main/scala/wvlet/airframe/http/CompatApi.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpClient.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpMessage.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpMultiMap.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpMultiMapCodec.scala

- Support requestFilter in JSHttpClient
- Support both msgpack/json encoding
- Support HttpMessage.Request, Response 
- Support request retry and error classifier using the same logic with JVM HttpClient

airframe-http: Enhance JS client

---

build.sbt

https://github.com/scala/scala/releases/tag/v2.12.11

Upgrade to Scala 2.12.11 

---

airframe-http/.js/src/main/scala/wvlet/airframe/http/js/JSHttpClient.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/HttpClientGenerator.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/HttpClientIR.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/RouteScanner.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/client/HttpClientType.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/client/ScalaHttpClient.scala
airframe-http/.jvm/src/test/scala/wvlet/airframe/http/codegen/HttpClientGeneratorTest.scala
airframe-http/src/main/scala/wvlet/airframe/http/SimpleHttp.scala
build.sbt
project/plugin.sbt
sbt-airframe/src/main/scala/wvlet/airframe/sbt/http/AirframeHttpPlugin.scala

This will resolve:
- Multiple Scala version support #970 
- Client code refresh issue

sbt-airframe: Use pre-built airframe-http package for generating client code

---

airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleFilter.scala
airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/CustomCodecTest.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/router/HttpEndpointExecutionContext.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/router/HttpRequestDispatcher.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/router/HttpRequestMapper.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/router/Route.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/router/RouteMatcher.scala
airframe-http/.jvm/src/test/scala/wvlet/airframe/http/RouterTest.scala

airframe-http: #1003 Use custom codec for request mapping

---

build.sbt

airspec: #1019 Add scala-reflect to the airspec dependency

---

airframe-http-rx/src/main/scala/wvlet/airframe/http/rx/Rx.scala
airframe-http-rx/src/test/scala/wvlet/airframe/http/rx/RxTest.scala

airframe-http-rx: Support filter

---

.github/workflows/test.yml
build.sbt

https://github.com/scala/scala/releases/tag/v2.13.2

Upgrade to Scala 2.13.2

---

airframe/.jvm/src/main/scala/wvlet/airframe/lifecycle/AddShutdownHook.scala

airframe-di: #1068 Do not close loggers upon session shutdown

---

airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/FinagleRouterTest.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/router/HttpRequestMapper.scala
airframe-surface/shared/src/main/scala/wvlet/airframe/surface/Surface.scala

airframe-http: #1086 Support query_string mapping for non GET requests

---

airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/filter/HttpAccessLogFilter.scala
airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/HttpAccessLogTest.scala

This change is for removing almost duplicated log data. In this example, Request object is dumped with toString:
```
{"response_time_ms":0,"time":1589587971,"event_time":"2020-05-15T17:12:51.888-0700",
"method":"DELETE","path":"/user/1","uri":"/user/1","request_size":14,"remote_host":"127.0.0.1","remote_port":55653,"host":"localhost:55637","content_type":"application/json;charset=utf-8","x_request_id":"10","content_length":"14","finagle_ctx_com.twitter.finagle.retries":"0","status_code":200,"status_code_name":"OK","response_size":38,"response_content_type":"application/json;charset=utf-8",
"rpc_class":"wvlet.airframe.http.finagle.FinagleClientTestApi",
"rpc_method":"delete",
"rpc_args":{"id":1,"request":"Request(\"DELETE /user/1\", from /127.0.0.1:55653)"}}
```
This PR removes …

airframe-http: Suppress request objects from rpc_args logs

---

airframe-codec/src/main/scala/wvlet/airframe/codec/MessageContext.scala
airframe-codec/src/main/scala/wvlet/airframe/codec/PrimitiveCodec.scala
airframe-codec/src/test/scala/wvlet/airframe/codec/CollectionCodecTest.scala

airframe-codec: #1083 Support JSON arrays to Array[X] mapping

---

airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/filter/HttpAccessLogFilter.scala
airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/HttpAccessLogTest.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/Router.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/router/Route.scala
airframe-http/.jvm/src/test/scala/wvlet/airframe/http/ApiRouterTest.scala
airframe-http/.jvm/src/test/scala/wvlet/airframe/http/RPCTest.scala

Closes #1112
@shimamoto This will be useful for collecting audit logs of RPC calls.

airframe-http: #1112 Report RPC interface class

---

airframe-codec/.js/src/main/scala/wvlet/airframe/codec/Compat.scala
airframe-codec/.jvm/src/main/scala/wvlet/airframe/codec/Compat.scala
airframe-codec/src/main/scala/wvlet/airframe/codec/ObjectCodec.scala
airframe-codec/src/main/scala/wvlet/airframe/codec/PrimitiveCodec.scala
airframe-codec/src/test/scala/wvlet/airframe/codec/PrimitiveCodecTest.scala

This will close #1091
@shimamoto @takezoe This PR will be useful to report the detailed RPC call arguments in JSON format.

airframe-codec: #1091 Support complex types in AnyCodec

---

.github/workflows/release-js.yml
build.sbt
project/build.properties

This is a workaround for https://github.com/sbt/sbt/issues/5586

Upgrade to sbt 1.3.12 with Scala.js build fixes

---

airframe/src/main/scala/wvlet/airframe/Binder.scala
airframe/src/main/scala/wvlet/airframe/SessionBuilder.scala
airframe/src/main/scala/wvlet/airframe/lifecycle/LifeCycleManager.scala
airframe/src/main/scala/wvlet/airframe/tracing/TraceEvent.scala
airframe/src/main/scala/wvlet/airframe/tracing/Tracer.scala
airframe/src/test/scala/wvlet/airframe/lifecycle/DesignTimeLifeCycleHookTest.scala
docs/airframe.md

airframe-di: Add .afterStart lifecycle hook

---

airframe-msgpack/.jvm/src/main/scala/wvlet/airframe/msgpack/impl/PackerImpl.scala
airframe-msgpack/src/main/scala/wvlet/airframe/msgpack/spi/Packer.scala
airframe-msgpack/src/test/scala/wvlet/airframe/msgpack/spi/RoundTripTest.scala

To force using timestamp32 wherever possible

airframe-msgpack: #1159 Support packTimestamp(unixtime)

---

airframe-fluentd/src/main/scala/wvlet/airframe/fluentd/Fluentd.scala
airframe-fluentd/src/main/scala/wvlet/airframe/fluentd/FluentdLogger.scala
airframe-fluentd/src/main/scala/wvlet/airframe/fluentd/MetricLogger.scala
airframe-fluentd/src/main/scala/wvlet/airframe/fluentd/package.scala
airframe-fluentd/src/test/scala/wvlet/airframe/fluentd/FluentdTest.scala
docs/airframe-fluentd.md

For the ease of initializing Fluentd (and TD) loggers 
cc: @NomadBlacky

airframe-fluentd: Convenient factories for initializing fluentd/td loggers

---

airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/GrpcServer.scala
airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/gRPC.scala
airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/GrpcServiceBuilderTest.scala
airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/GrpcTest.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/HttpClientIR.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/client/GrpcClient.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/client/ScalaHttpClient.scala
airframe-http/.jvm/src/test/scala/example/rpc/RPCTestService.scala
airframe-http/.jvm/src/test/scala/wvlet/airframe/http/codegen/GrpcClientGeneratorTest.scala
build.sbt
docs/airframe-rpc.md
sbt-airframe/src/sbt-test/sbt-airframe/generate-client/server/src/main/scala/myapp/server/MyServer.scala
sbt-airframe/src/sbt-test/sbt-airframe/grpc/api/src/main/scala/example/api/GreeterApi.scala
sbt-airframe/src/sbt-test/sbt-airframe/grpc/build.sbt
sbt-airframe/src/sbt-test/sbt-airframe/grpc/project/build.properties
sbt-airframe/src/sbt-test/sbt-airframe/grpc/project/plugins.sbt
sbt-airframe/src/sbt-test/sbt-airframe/grpc/server/src/test/scala/example/api/GreeterApiTest.scala
sbt-airframe/src/sbt-test/sbt-airframe/grpc/test

- Add gRPC client code generator
- non-blocking client (grpc-async)  (todo in another PR)

airframe-grpc: Genearte gRPC clients

---

airframe-http/.jvm/src/test/scala/wvlet/airframe/http/HttpClientTest.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpClientException.scala

airframe-http: Retry on 408 request timeout

---

airframe-codec/.jvm/src/test/scala/wvlet/airframe/codec/MessageCodecTest.scala
airframe-codec/src/main/scala/wvlet/airframe/codec/EnumCodec.scala
airframe-codec/src/main/scala/wvlet/airframe/codec/MessageCodec.scala
airframe-codec/src/test/scala/wvlet/airframe/codec/EnumCodecTest.scala
airframe-codec/src/test/scala/wvlet/airframe/codec/ScalaStandardCodecTest.scala
airframe-http/.jvm/src/test/scala/wvlet/airframe/http/HttpRequestMapperTest.scala

airfame-codec: Throw an exception for invalid enum string

---

airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/GrpcLoggingInterceptor.scala
airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/GrpcServer.scala
airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/GrpcLoggingInterceptorTest.scala
airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/example/Greeter.scala

airframe-grpc: Support gRPC server interceptors

---

airframe-codec/src/main/scala/wvlet/airframe/codec/ULIDCodec.scala
airframe-codec/src/test/scala/wvlet/airframe/codec/ScalaStandardCodecTest.scala
airframe-control/.jvm/src/test/scala/wvlet/airframe/control/ULIDCalendarTest.scala
airframe-control/README.md
airframe-control/src/main/scala/wvlet/airframe/control/ULID.scala
airframe-control/src/test/scala/wvlet/airframe/control/ULIDTest.scala
build.sbt

Closes #1221 
cc: @petitviolet

airframe-control: Support ULID

---

airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/RouteScanner.scala
airframe-surface/jvm/src/main/scala/wvlet/airframe/surface/reflect/package.scala

sbt-airframe: Limit the scope of finding @RPC annotations

---

airframe-codec/src/main/scala/wvlet/airframe/codec/CollectionCodec.scala
airframe-codec/src/main/scala/wvlet/airframe/codec/MessageCodecFinder.scala
airframe-codec/src/test/scala/wvlet/airframe/codec/CollectionCodecTest.scala

airframe-codec: Support ListMap codec

---

sbt

curl -Ls https://git.io/sbt > ./sbt

internal: Update sbt script

---

.github/workflows/package-test.yml
.github/workflows/test.yml
build.sbt

Added a new CI task to test publish (including package, doc) works properly before releasing artifacts. Without this check, releasing at CI can fail and fixing the issue can be tricky.

internal: Add packaging test

---

.gitignore
airframe-rx/.js/src/main/scala/wvlet/airframe/rx/compat.scala
airframe-rx/.jvm/src/main/scala/wvlet/airframe/rx/compat.scala
airframe-rx/src/main/scala/wvlet/airframe/rx/Rx.scala
airframe-rx/src/main/scala/wvlet/airframe/rx/RxRunner.scala
airframe-rx/src/main/scala/wvlet/airframe/rx/Timer.scala
airframe-rx/src/test/scala/wvlet/airframe/rx/IntervalTest.scala
airframe-rx/src/test/scala/wvlet/airframe/rx/RxTest.scala
docs/airframe-rx.md

For periodically monitoring events:
- Interval http://reactivex.io/documentation/operators/interval.html
- Take http://reactivex.io/documentation/operators/take.html

airframe-rx: Add Rx.take(n) and Rx.interval

---

airframe-rx/src/main/scala/wvlet/airframe/rx/Rx.scala
airframe-rx/src/main/scala/wvlet/airframe/rx/RxOption.scala

- Add Rx.join/zip/concat convenient methods

airframe-rx: Make RxOption public

---

airframe-rx/src/main/scala/wvlet/airframe/rx/Rx.scala
airframe-rx/src/main/scala/wvlet/airframe/rx/RxRunner.scala
airframe-rx/src/test/scala/wvlet/airframe/rx/IntervalTest.scala

airframe-rx: Add throttleFirst/Last(sample)

---

airframe-rx/src/main/scala/wvlet/airframe/rx/RxRunner.scala

This is only for internal improvements.

airframe-rx: Add RxResult for propagating downstream operator states

---

.gitignore
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/Router.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/HttpClientIR.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/RouteAnalyzer.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/openapi/OpenAPIGenerator.scala
airframe-http/.jvm/src/test/scala/example/openapi/OpenAPIExample.scala
airframe-http/.jvm/src/test/scala/wvlet/airframe/http/RouterTest.scala
airframe-http/.jvm/src/test/scala/wvlet/airframe/http/openapi/OpenAPITest.scala
sbt-airframe/src/main/scala/wvlet/airframe/sbt/http/AirframeHttpPlugin.scala

sbt-airframe: Support Future response type in OpenAPI generator

---

.scalafmt.conf
airframe-http/src/main/scala/wvlet/airframe/http/HttpContext.scala
airframe-log/jvm/src/main/scala/wvlet/log/AirframeLogManager.scala
examples/rpc-examples/hello-rpc/.scalafmt.conf
examples/src/main/scala/wvlet/airframe/examples/di/DI_91_Stats.scala

- then run `sbt scalafmtAll`
related to https://github.com/wvlet/airframe/pull/1318

update scalafmt-core to 2.7.5

---

.github/workflows/test.yml
airframe-rx-html/src/main/scala/wvlet/airframe/rx/html/RxHtmlMacros.scala
airframe-rx-html/src/main/scala/wvlet/airframe/rx/html/package.scala
airframe-rx-widget/src/main/public/index.html
airframe-rx-widget/src/main/scala/wvlet/airframe/rx/html/widget/demo/Demo.scala
airframe-rx-widget/src/main/scala/wvlet/airframe/rx/html/widget/demo/Gallery.scala
build.sbt
project/plugin.sbt

This will create a demo like this:

airframe-rx-html: Demo code for airframe-rx-html

---

airframe-http/.jvm/src/main/scala/wvlet/airframe/http/Router.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/RouteAnalyzer.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/openapi/OpenAPI.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/openapi/OpenAPIGenerator.scala
airframe-http/.jvm/src/test/scala/wvlet/airframe/http/openapi/SimpleOpenAPITest.scala
sbt-airframe/src/main/scala/wvlet/airframe/sbt/http/AirframeHttpPlugin.scala

- Support more types: Seq, Map, Future, Either, Reader, Response, etc.
- Support recursive types
- Properly register complex types as components

sbt-airframe: Various fixes of Open API generator

---

build.sbt
docs/airframe-fluentd.md

airframe-fluentd: Add fluency-treasuredata to the dependency

---

airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleClient.scala

airframe-http: #1135 Support modifying retryContext

---

airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleBackend.scala
airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleFilter.scala
airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/package.scala
airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/filter/StandardFilterTest.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/router/HttpRequestDispatcher.scala
airframe-http/src/main/scala/wvlet/airframe/http/Http.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpBackend.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpContext.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpFilter.scala

airframe-http: Add standard filter

---

sbt-airframe/src/main/scala/wvlet/airframe/sbt/http/AirframeHttpPlugin.scala

sbt-airframe: #1457 Support downloading airframe-http from Sonatype snapshot repo

---

airframe-control/.jvm/src/main/scala/wvlet/airframe/control/Shell.scala
airframe-jmx/src/main/scala/wvlet/airframe/jmx/JMXUtil.scala
airframe-surface/jvm/src/main/scala/wvlet/airframe/surface/reflect/ReflectTypeUtil.scala

Use jdk8-comptible reflection method

---

airframe-rx-html/.js/src/main/scala/wvlet/airframe/rx/html/DOMRenderer.scala
airframe-rx-html/.js/src/test/scala/wvlet/airframe/http/rx/html/RxRenderingTest.scala
airframe-rx-html/src/main/scala/wvlet/airframe/rx/html/RxElement.scala
airframe-rx-html/src/test/scala/wvlet/airframe/rx/html/RxElementTest.scala

airframe-rx-html: Add beforeRender/beforeUnmount event handler

---

airframe-rx-html/.js/src/test/scala/wvlet/airframe/http/rx/html/RxRenderingTest.scala

rx-html: Add tests for attribute updates #1341

---

airframe-parquet/src/main/scala/wvlet/airframe/parquet/AirframeParquetReader.scala
airframe-parquet/src/main/scala/wvlet/airframe/parquet/AirframeParquetWriter.scala
airframe-parquet/src/main/scala/wvlet/airframe/parquet/Parquet.scala
airframe-parquet/src/main/scala/wvlet/airframe/parquet/io/ParquetWriterImpl.scala
airframe-parquet/src/test/scala/wvlet/airframe/parquet/ParquetTest.scala
build.sbt
docs/airframe-parquet.md
website/sidebars.json

Adding a new module for reading and writing Parquet format data.
cc: @wvlet/airframe-dev

airframe-parquet: Parquet format reader and writer

---

airframe-parquet/src/main/scala/wvlet/airframe/parquet/AirframeParquetReader.scala
airframe-parquet/src/test/scala/wvlet/airframe/parquet/ParquetTest.scala
docs/airframe-parquet.md

airframe-parquet: Support column projection

---

airframe-parquet/src/main/scala/wvlet/airframe/parquet/AirframeParquetReader.scala
airframe-parquet/src/main/scala/wvlet/airframe/parquet/Parquet.scala
airframe-parquet/src/main/scala/wvlet/airframe/parquet/ParquetQueryPlanner.scala
airframe-parquet/src/test/scala/wvlet/airframe/parquet/ParquetQueryPlannerTest.scala
airframe-parquet/src/test/scala/wvlet/airframe/parquet/ParquetQueryTest.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/model/Expression.scala
build.sbt
docs/airframe-parquet.md

Add a simple SQL support for filtering Parquet columns

airframe-parquet: SQL query support

---

docs/airframe.md

usage of Child Sessions might be incorrect

modified document about Child Sessions

---

airframe-di-base/src/main/scala-3/wvlet/airframe/di/SourceCode.scala
airframe-di/src/main/scala-3/wvlet/airframe/di/AirframeSessionImpl.scala
airframe-di/src/main/scala-3/wvlet/airframe/di/BinderImpl.scala
airframe-di/src/main/scala-3/wvlet/airframe/di/DesignImpl.scala
airframe-di/src/main/scala-3/wvlet/airframe/di/SessionImpl.scala
airframe-dotty-test/src/main/scala/dotty/test/DITest.scala
build.sbt

airframe-di: Scala 3 support (Phase 3)

---

airframe-codec/src/main/scala/wvlet/airframe/codec/PrimitiveCodec.scala
airframe-codec/src/test/scala/wvlet/airframe/codec/PrimitiveCodecTest.scala
airframe-surface/shared/src/main/scala-2/wvlet/airframe/surface/SurfaceMacros.scala
airframe-surface/shared/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala
airframe-surface/shared/src/main/scala/wvlet/airframe/surface/Surfaces.scala
airframe-surface/shared/src/main/scala/wvlet/airframe/surface/Zero.scala
airframe-surface/shared/src/test/scala/wvlet/airframe/surface/SurfaceTest.scala
airframe-surface/shared/src/test/scala/wvlet/airframe/surface/ZeroTest.scala

airframe-surface, codec: Add BigInt, BigInteger support

---

airframe-rx/src/main/scala/wvlet/airframe/rx/RxRunner.scala
airframe-rx/src/test/scala/wvlet/airframe/rx/IntervalTest.scala
airframe-rx/src/test/scala/wvlet/airframe/rx/RxRunnerTest.scala
airframe-rx/src/test/scala/wvlet/airframe/rx/RxTest.scala

airframe-rx: More test coverage

---

airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/internal/GrpcRequestHandler.scala

airframe-grpc: Show the exception error message in RPC implementations

---

airframe-log/src/main/scala/wvlet/log/LogFormat.scala

Fix formatStacktrace dropping last line

---

airframe-http-codegen/src/test/scala/wvlet/airframe/http/codegen/ClassScannerTest.scala
airframe-surface/.jvm/src/main/scala-2/wvlet/airframe/surface/reflect/ReflectSurfaceFactory.scala
build.sbt

airframe-surface: Give up building Surface for difficult types

---

airframe-parquet/src/main/scala/wvlet/airframe/parquet/Parquet.scala
airframe-parquet/src/main/scala/wvlet/airframe/parquet/ParquetStatsReader.scala
airframe-parquet/src/test/scala/wvlet/airframe/parquet/ParquetTest.scala
docs/airframe-parquet.md

airframe-parquet: Read column statistics

---

airframe-parquet/src/main/scala/wvlet/airframe/parquet/AirframeParquetWriter.scala
airframe-parquet/src/main/scala/wvlet/airframe/parquet/Parquet.scala
airframe-parquet/src/test/scala/wvlet/airframe/parquet/ParquetRecordWriterTest.scala
docs/airframe-parquet.md

airframe-parquet: Add record writer

---

airframe-log/src/main/scala/wvlet/log/LogFormat.scala
airframe-log/src/test/scala/wvlet/airframe/log/AirframeLogDemo.scala
airframe-log/src/test/scala/wvlet/log/LoggerTest.scala
docs/airframe-log.md

airframe-log: Add ThreadLogFormatter

---

airframe-log/src/main/scala/wvlet/log/Logger.scala
airframe-log/src/test/scala/wvlet/airframe/log/LogTest.scala
docs/airframe-log.md

airframe-log: Support setting the root log level with _root_ logger name

---

airframe-msgpack/src/test/scala/wvlet/airframe/msgpack/spi/RoundTripTest.scala
airframe-msgpack/src/test/scala/wvlet/airframe/msgpack/spi/UnpackerTest.scala

airframe-msgpack: Test tryUnpackNil at EOL

---

airframe-http-codegen/src/main/scala/wvlet/airframe/http/codegen/HttpClientIR.scala
airframe-http-codegen/src/main/scala/wvlet/airframe/http/codegen/HttpCodeGenerator.scala
airframe-http-codegen/src/main/scala/wvlet/airframe/http/codegen/client/GrpcClientGenerator.scala
airframe-http-codegen/src/main/scala/wvlet/airframe/http/codegen/client/HttpClientGenerator.scala
airframe-http-codegen/src/main/scala/wvlet/airframe/http/codegen/client/ScalaHttpClientGenerator.scala
airframe-http-codegen/src/test/scala/wvlet/airframe/http/codegen/HttpClientGeneratorTest.scala
docs/airframe-rpc.md

airframe-http: Support customizing generated RPC client names

---

airspec/src/main/scala-2/wvlet/airspec/AirSpecSpiCompat.scala
airspec/src/test/scala/examples/CommonSpec.scala
airspec/src/test/scala/examples/F0Spec.scala
airspec/src/test/scala/wvlet/airspec/AirSpecLauncherTest.scala
docs/airspec.md

airspec: Add note for `test(...) { (function) }` issue #1681

---

airframe-http/.js/src/test/scala/wvlet/airframe/http/js/JSHttpClientTest.scala
airframe-rx-html/.js/src/test/scala/wvlet/airframe/http/rx/html/HtmlRenderingTest.scala
airframe-rx-widget/src/test/scala/wvlet/airframe/http/rx/widget/RxWidgetTest.scala
airframe-rx/.js/src/main/scala/wvlet/airframe/rx/compat.scala
airframe-rx/.jvm/src/main/scala/wvlet/airframe/rx/compat.scala
airframe-rx/src/test/scala/wvlet/airframe/rx/RxTest.scala
build.sbt

https://github.com/scala-js/scala-js-macrotask-executor

Use MacrotaskExecutor 

---

build.sbt

airframe-config's YAML library, airframe-fluentd-td integration

Upgrade libraries CVE-2017-18640 and CVE-2020-15250

---

.scalafmt.conf
airframe-di/src/test/scala-2/wvlet/airframe/legacy/AirframeTest.scala
airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleServer.scala
airframe-launcher/src/main/scala/wvlet/airframe/launcher/StringTree.scala
airframe-rx/src/main/scala/wvlet/airframe/rx/Rx.scala
airframe-ulid/src/main/scala/wvlet/airframe/ulid/CrockfordBase32.scala
airframe-ulid/src/main/scala/wvlet/airframe/ulid/ULID.scala

Bump scalafmt and fix format

---

airframe-control/.jvm/src/main/scala/wvlet/airframe/control/Shell.scala
airframe-di-macros/src/main/scala-3/wvlet/airframe/SourceCode.scala
airframe-http-codegen/src/main/scala/wvlet/airframe/http/openapi/OpenAPI.scala
airframe-http-recorder/src/test/scala/wvlet/airframe/http/recorder/HttpRecorderTest.scala
airframe-json/src/main/scala/wvlet/airframe/json/JSON.scala
airframe-log/src/main/scala-3/wvlet/log/LoggerBase.scala
airframe-metrics/.jvm/src/main/scala/wvlet/airframe/metrics/TimeVector.scala
airframe-metrics/.jvm/src/main/scala/wvlet/airframe/metrics/TimeWindow.scala
airframe-metrics/src/main/scala/wvlet/airframe/metrics/Count.scala
airframe-metrics/src/main/scala/wvlet/airframe/metrics/DataSize.scala
airframe-rx-html/.js/src/test/scala/wvlet/airframe/http/rx/html/NestedElementTest.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlan.scala
airframe-surface/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala
airframe-ulid/src/main/scala/wvlet/airframe/ulid/CrockfordBase32.scala

Fixed Scala standard library deprecations as much as possible.
Some deprecations remain to support Scala 2.12.

Fix Scala deprecations as much as possible

---

airspec/project/plugin.sbt
project/plugin.sbt
sbt-airframe/project/plugin.sbt

Reverts wvlet/airframe#2082 due to sbt-sonatype regression

Revert "Update sbt-sonatype to 3.9.12"

---

airframe-di/src/main/scala/wvlet/airframe/LazyF0.scala
airframe-rx/src/main/scala/wvlet/airframe/rx/LazyF0.scala

As a workaround for https://github.com/scala-js/scala-js/issues/4657
This is required for #2117

Remove dependency to UUID.randomUUID() 

---

build.sbt

Update airspec to 22.4.0

---

airframe-control/src/main/scala/wvlet/airframe/control/Control.scala
airframe-control/src/main/scala/wvlet/airframe/control/Resource.scala
airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/GrpcClient.scala
airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/GrpcClientCalls.scala
airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/internal/GrpcException.scala
airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/internal/GrpcRequestHandler.scala
airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/internal/GrpcServiceBuilder.scala
airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/GrpcClientTest.scala
airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/example/DemoApi.scala
airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/example/DemoApiV2.scala
airframe-http/src/main/scala/wvlet/airframe/http/RPCStatus.scala
airframe-http/src/test/scala/wvlet/airframe/http/RPCStatusTest.scala
airframe-log/src/main/scala/wvlet/log/Logger.scala
airframe-rx/src/main/scala/wvlet/airframe/rx/RxVar.scala

airframe-grpc: Add GrpcClient for consolidating a logic for handling RPCException

---

airframe-http/src/main/scala/wvlet/airframe/http/HttpClient.scala

airframe-http: #1559 Use Jitter by default in http clients

---

airframe-http/.js/src/main/scala/wvlet/airframe/http/Compat.scala
airframe-http/.js/src/main/scala/wvlet/airframe/http/js/JSHttpClientBackend.scala
airframe-http/.js/src/test/scala/wvlet/airframe/http/js/JSRPCClientTest.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/Compat.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/client/URLConnectionClientBackend.scala
airframe-http/.jvm/src/test/scala/wvlet/airframe/http/HttpClientTest.scala
airframe-http/.jvm/src/test/scala/wvlet/airframe/http/client/URLConnectionClientTest.scala
airframe-http/src/main/scala-2/wvlet/airframe/http/RPCClientBase.scala
airframe-http/src/main/scala/wvlet/airframe/http/CompatApi.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpClientBackend.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpClientConfig.scala
airframe-http/src/main/scala/wvlet/airframe/http/RPCHttpClient.scala

I found this configuration is necessary for sbt-sonatype plugin 😅

airframe-http: Add read/connect timeout settings to HttpClientConfig

---

airframe-http-router/src/main/scala-2/wvlet/airframe/http/router/RouterBase.scala
airframe-http-router/src/main/scala-3/wvlet/airframe/http/router/RouterBase.scala
airframe-http-router/src/main/scala/wvlet/airframe/http/Router.scala
airframe-http-router/src/main/scala/wvlet/airframe/http/router/Automaton.scala
airframe-http-router/src/main/scala/wvlet/airframe/http/router/HttpEndpointExecutionContext.scala
build.sbt

Scala 3 tests passed for these projects: 
- airframe-http (core)
- airframe-http-router
cc: @exoego

airframe-http: Scala 3 support

---

airframe-http/.js/src/test/scala/wvlet/airframe/http/client/JSHttpAsyncClientTest.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/Compat.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/client/JavaSyncClient.scala
airframe-http/.jvm/src/test/scala/wvlet/airframe/http/client/JavaAsyncClientTest.scala
airframe-http/.jvm/src/test/scala/wvlet/airframe/http/client/JavaSyncClientTest.scala
airframe-http/.jvm/src/test/scala/wvlet/airframe/http/client/URLConnectionClientTest.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpClientConfig.scala

And also stabilize http tests using public endpoints

airframe-http: Fix deadlock at http client threads

---

airframe-http-codegen/src/main/scala/wvlet/airframe/http/codegen/client/RPCClientGenerator.scala
airframe-http-codegen/src/test/scala/wvlet/airframe/http/codegen/RPCClientGeneratorTest.scala
airframe-http/.js/src/main/scala/wvlet/airframe/http/client/JSClientChannel.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/client/JavaClientChannel.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/client/URLConnectionChannel.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpClientConfig.scala
airframe-http/src/main/scala/wvlet/airframe/http/client/ClientFactory.scala
airframe-http/src/main/scala/wvlet/airframe/http/client/HttpChannel.scala
airframe-http/src/main/scala/wvlet/airframe/http/client/HttpClients.scala

airframe-http: Http client interface clean up 

---

airframe-http-codegen/src/main/scala/wvlet/airframe/http/codegen/HttpClientIR.scala
airframe-http-codegen/src/main/scala/wvlet/airframe/http/codegen/client/RPCClientGenerator.scala
airframe-http/.js/src/test/scala/wvlet/airframe/http/client/JSRPCClientTest.scala
airframe-http/.jvm/src/test/scala/wvlet/airframe/http/client/RPCHttpClientTest.scala
airframe-http/src/main/scala-2/wvlet/airframe/http/client/HttpClientCompat.scala
airframe-http/src/main/scala-2/wvlet/airframe/http/impl/HttpMacros.scala
airframe-http/src/main/scala-3/wvlet/airframe/http/client/HttpClientCompat.scala
airframe-http/src/main/scala/wvlet/airframe/http/RPCEncoding.scala
airframe-http/src/main/scala/wvlet/airframe/http/RPCMethod.scala
airframe-http/src/main/scala/wvlet/airframe/http/client/ClientFilter.scala
airframe-http/src/main/scala/wvlet/airframe/http/client/ClientLoggingFilter.scala
airframe-http/src/main/scala/wvlet/airframe/http/client/HttpClients.scala
airframe-http/src/test/scala/wvlet/airframe/http/client/ClientLoggingFilterTest.scala

This is a preparation for #2142 so that we can track RPC call context

airframe-http: Add RPCMethod

---

build.sbt

Upgrade to Scala 3.1.3

---

airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleRPCContext.scala
airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/FinagleServer.scala
airframe-http-finagle/src/test/scala/wvlet/airframe/http/finagle/ThreadLocalStorageTest.scala
airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/GrpcContext.scala
airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/GrpcService.scala
airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/internal/GrpcContextTrackInterceptor.scala
airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/GrpcContextTest.scala
airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/example/DemoApi.scala
airframe-http/.js/src/main/scala/wvlet/airframe/http/Compat.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/Compat.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/internal/LocalRPCContext.scala
airframe-http/src/main/scala/wvlet/airframe/http/GrpcStatus.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpMessage.scala
airframe-http/src/main/scala/wvlet/airframe/http/RPCContext.scala
docs/airframe-rpc.md

airframe-rpc: #2368 Add RPCContext to access thread-local storage and http request

---

airframe-surface/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala

airframe-surface: #2396 Build EnumSurface without reflection

---

airspec/.jvm/src/main/scala/wvlet/airspec/Compat.scala
airspec/src/test/scala/examples/InitFailureTest.scala

airspec: Show exceptions during test class initialization failures

---

airframe-http/.jvm/src/main/scala/wvlet/airframe/http/client/JavaClientChannel.scala
airframe-http/.jvm/src/test/scala/wvlet/airframe/http/client/JavaSyncClientTest.scala

Fixes `MatchError` introduced by #2465

Fix MatchError in excluding pseudo headers of JDK's http client

---

airframe-jmx/src/test/scala/wvlet/airframe/jmx/JMXRegistryTest.scala
docs/airframe-jmx.md

Follow up to https://github.com/wvlet/airframe/pull/2494

Update airframe-jmx doc to describe name attribute of JMX annotation

---

airframe-sql/src/main/scala/wvlet/airframe/sql/catalog/DataTypeParser.scala
airframe-sql/src/test/scala/wvlet/airframe/sql/catalog/DataTypeTest.scala

support weird array type format

airframe-sql: support array type format like "array<string>"

---

airspec/project/plugin.sbt
examples/rpc-examples/hello-rpc/project/plugins.sbt
examples/rpc-examples/rpc-scalajs/project/plugins.sbt
examples/rx-demo/gallery/project/plugins.sbt
sbt-airframe/project/plugin.sbt

Scala Steward started failing because of sbt 1.7.3 upgrade and scala-xml compatibility error https://github.com/xerial/scala-steward-repos/actions/runs/3374064609/jobs/5599293513

Ignore scala-xml version incompatibilities

---

.github/workflows/snapshot.yml

- Notify a new snapshot version to wvlet Slack
- Fix message

Notify a new snapshot version to Slack

---

airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlan.scala
airframe-sql/src/test/scala/wvlet/airframe/sql/model/LogicalPlanTest.scala

Add methods necessary for controlling recursive traversal

airframe-sql: Add transformOnce, transformChildrenOnce

---

airframe-codec/src/main/scala/wvlet/airframe/codec/PrefixedULIDCodec.scala
airframe-codec/src/main/scala/wvlet/airframe/codec/PrimitiveCodec.scala
airframe-codec/src/main/scala/wvlet/airframe/codec/ULIDCodec.scala
airframe-codec/src/test/scala/wvlet/airframe/codec/ScalaStandardCodecTest.scala
airframe-ulid/src/main/scala/wvlet/airframe/ulid/PrefixedULID.scala
airframe-ulid/src/main/scala/wvlet/airframe/ulid/ULID.scala
airframe-ulid/src/test/scala/wvlet/airframe/ulid/PrefixedULIDTest.scala
airframe-ulid/src/test/scala/wvlet/airframe/ulid/ULIDTest.scala

Support PrefixedULID case class in ULID

---

airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/package.scala
airframe-http-netty/src/main/scala/wvlet/airframe/http/netty/NetthRequestHandler.scala
airframe-http-netty/src/test/scala/wvlet/airframe/http/netty/NettyBackendTest.scala
airframe-http-okhttp/src/main/scala/wvlet/airframe/http/okhttp/package.scala
airframe-http/src/main/scala/wvlet/airframe/http/Http.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpMessage.scala

airframe-http: Add Request.remoteAddress

---

airframe-http-codegen/src/main/scala/wvlet/airframe/http/codegen/HttpClientIR.scala
airframe-http-codegen/src/main/scala/wvlet/airframe/http/openapi/OpenAPIGenerator.scala
airframe-http-codegen/src/test/scala/wvlet/airframe/http/codegen/HttpClientGeneratorTest.scala
airframe-http-finagle/src/main/scala/wvlet/airframe/http/finagle/filter/HttpAccessLogFilter.scala
airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/internal/GrpcRequestHandler.scala
airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/internal/GrpcServiceBuilder.scala
airframe-http-router/src/main/scala/wvlet/airframe/http/HttpAccessLogWriter.scala
airframe-http-router/src/main/scala/wvlet/airframe/http/Router.scala
airframe-http-router/src/main/scala/wvlet/airframe/http/router/Route.scala
airframe-http-router/src/main/scala/wvlet/airframe/http/router/RouteMatcher.scala
airframe-http-router/src/test/scala/wvlet/airframe/http/ApiRouterTest.scala
airframe-http-router/src/test/scala/wvlet/airframe/http/RPCTest.scala
airframe-http-router/src/test/scala/wvlet/airframe/http/RouterTest.scala
airframe-http/src/main/scala/wvlet/airframe/http/RPCMethod.scala
airframe-http/src/main/scala/wvlet/airframe/http/internal/HttpLogs.scala
airframe-http/src/main/scala/wvlet/airframe/http/internal/RPCCallContext.scala

airframe-rpc: Add RPCMethod to RPCCallContext

---

airframe-parquet/src/main/scala/wvlet/airframe/parquet/ParquetQueryPlanner.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/TypeResolver.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/model/Expression.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlan.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/parser/SQLGenerator.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/parser/SQLInterpreter.scala
airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/TypeResolverTest.scala

This has a known issue that cannot work with Union. It will be fixed separately.

airframe-sql: Resolve AllColumns

---

airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/SQLAnalyzer.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/SQLAnonymizer.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/TypeResolver.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlan.scala
airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/QuerySignatureTest.scala
airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/SQLAnonymizerTest.scala
airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/TypeResolverTest.scala
airframe-sql/src/test/scala/wvlet/airframe/sql/catalog/DataTypeParserTest.scala
airframe-sql/src/test/scala/wvlet/airframe/sql/catalog/DataTypeTest.scala

- Confirmed the change in #2608 is sufficient in unit tests.
- Change debug logs  -> trace logs

airframe-sql: Resolve AllColumn(*) cont'd

---

airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlan.scala

Sorry, my previous PR for UNION (https://github.com/wvlet/airframe/pull/2611) was incomplete regarding INTERSECT.

airframe-sql: Fix INTERSECT handling

---

airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/TypeResolver.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/model/Expression.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/model/ResolvedPlan.scala
airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/SQLAnalyzerTest.scala
airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/TypeResolverTest.scala
airframe-sql/src/test/scala/wvlet/airframe/sql/parser/SQLGeneratorTest.scala
build.sbt

Closes https://github.com/wvlet/airframe/issues/2606

airframe-sql: Retain AllColumns even after applying TypeResolver

---

airspec/build.sbt
airspec/src/main/scala/wvlet/airspec/runner/AirSpecTaskRunner.scala
airspec/src/test/scala/examples/RxTest.scala

airspec: #2163 Support async test for Rx[_]

---

airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/TypeResolver.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/model/Expression.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/model/LogicalPlan.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/model/ResolvedPlan.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/parser/SQLInterpreter.scala
airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/TypeResolverTest.scala

- Add Attribute.sourceColumns
- Make inputColumns public

airframe-sql: Add Attribute.input/sourceColumns

---

airframe-di/src/main/scala-3/wvlet/airframe/package.scala
airframe-di/src/test/scala-3/wvlet/airframe/di/TraitFactoryTest.scala
airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/internal/GrpcResponseHeaderInterceptor.scala
airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/GrpcContextTest.scala
airframe-http-router/src/main/scala-3/wvlet/airframe/http/router/RouterBase.scala
build.sbt

- Check should generate trait
- Add grpc to projectDotty

airframe-grpc: Scala 3 support

---

airframe-http-netty/src/main/scala/wvlet/airframe/http/netty/NetthRequestHandler.scala

Finagle backend can return custom error responses. (https://wvlet.org/airframe/docs/airframe-http.html#error-handling)
This PR add same feature to Netty backend.

airframe-http-netty: Enable error handling

---

airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/TypeResolver.scala
airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/TypeResolverTest.scala

airframe-sql wrongly resolves index grouping keys/sort keys with AllColumns.
ORDER BY:
```sql
-- Original SQL:
select * from A order by 1
-- Resolved plan:
[Sort]: (id:long, name:string) => (id:long, name:string)
- SortItem(AllColumns(id:long, name:string),None,None,Some(NodeLocation(1,26)))
[Project]: (id:long, name:string) => (id:long, name:string)
- AllColumns(id:long, name:string)
[TableScan] default.A:  => (id:long, name:string)
-- SQL generated from resolved plan:
SELECT * FROM A ORDER BY *
```
GROUP BY:
```sql
-- Original SQL
select *, count(*) from (select id from A) group by 1
-- Resolved plan:
[Aggregate]: (id:long) => (id:long, ?:long)
- AllColumns(id:long)
- ?:long := FunctionCall(count, AllColumns(id:long), distinct:false, window:None)
- …
```

airframe-sql: Index sort keys/grouping keys are wrongly resolved for AllColumns

---

airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/TypeResolver.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/model/Expression.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/parser/SQLInterpreter.scala
airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/TypeResolverTest.scala

- Preserve qualifier in SQL text
- Fix test cases

airframe-sql: Preserve qualifiers given in SingleColumn

---

airframe-launcher/src/main/scala/wvlet/airframe/launcher/OptionParser.scala
airframe-launcher/src/test/scala/wvlet/airframe/launcher/LauncherTest.scala

https://github.com/wvlet/airframe/pull/2733 was not enough 🙇‍♂️

airframe-launcher: Allow '-' in option name without argument

---

airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/TypeResolver.scala
airframe-sql/src/main/scala/wvlet/airframe/sql/model/Expression.scala
airframe-sql/src/test/scala/wvlet/airframe/sql/analyzer/TypeResolverTest.scala

Follow-up to https://github.com/wvlet/airframe/pull/2803
Since context is necessary for this, https://github.com/wvlet/airframe/pull/2808 was not necessary. 🙇‍♂️

airframe-sql: Check database name in Attribute.matched()

---

airframe-http-netty/src/main/scala/wvlet/airframe/http/netty/NetthRequestHandler.scala
airframe-http-netty/src/main/scala/wvlet/airframe/http/netty/NettyBackend.scala
airframe-http-netty/src/test/scala/wvlet/airframe/http/netty/NettyRxFilterTest.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/router/HttpRequestDispatcher.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpBackend.scala
airframe-http/src/main/scala/wvlet/airframe/http/client/HttpClients.scala

This change is for supporting RPC filter with Netty backend in Scala 3

airframe-netty: Support RxFilter

---

airframe-http-netty/src/test/scala/wvlet/airframe/http/netty/RPCClientBindingTest.scala
airframe-surface/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala

- airframe-http: Fix RPC client binding with DI
- airframe-surface: Fix Surface.of[X] for X defined inside a Module

airframe-surface: Fix Surface.of[X] for generated RPC clients

---

airframe-http-netty/src/main/scala/wvlet/airframe/http/netty/NetthRequestHandler.scala
airframe-http-netty/src/main/scala/wvlet/airframe/http/netty/NettyBackend.scala
airframe-http-netty/src/main/scala/wvlet/airframe/http/netty/NettyServer.scala
airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRecord.scala
airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRecordStore.scala
airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRecorder.scala
airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRecorderServer.scala
airframe-http-recorder/src/main/scala/wvlet/airframe/http/recorder/HttpRequestMatcher.scala
airframe-http-recorder/src/test/scala/wvlet/airframe/http/recorder/HttpRecorderTest.scala
airframe-http-recorder/src/test/scala/wvlet/airframe/http/recorder/PathOnlyMatcherTest.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/Router.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/router/HttpEndpointExecutionContext.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/router/HttpRequestDispatcher.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/router/Route.scala
airframe-http/src/main/scala-3/wvlet/airframe/http/router/RxRouterBase.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpBackend.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpClientConfig.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpHeader.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpMessage.scala
airframe-http/src/main/scala/wvlet/airframe/http/RxEndpoint.scala
airframe-http/src/main/scala/wvlet/airframe/http/RxFilter.scala
airframe-http/src/main/scala/wvlet/airframe/http/router/RedirectToRxEndpoint.scala
airframe-http/src/main/scala/wvlet/airframe/http/router/RxRouter.scala
airframe-http/src/test/scala/wvlet/airframe/http/router/CustomEndpointTest.scala
airframe-http/src/test/scala/wvlet/airframe/http/router/RxRouterTest.scala
build.sbt
docs/airframe-http-recorder.md

airframe-http-recorder: Scala 3 support

---

airspec/src/main/scala/wvlet/airspec/spi/RichAsserts.scala
airspec/src/test/scala/examples/ShouldContainTest.scala
docs/airspec.md

airspec: #2857 Add shouldContain, shouldNotContain matcher

---

airspec/src/main/scala-2/wvlet/airspec/AirSpecSpiCompat.scala
airspec/src/main/scala-3/wvlet/airspec/AirSpecSpiCompat.scala
airspec/src/main/scala/wvlet/airspec/AirSpec.scala
airspec/src/main/scala/wvlet/airspec/AirSpecDef.scala
airspec/src/main/scala/wvlet/airspec/runner/AirSpecContextImpl.scala
airspec/src/main/scala/wvlet/airspec/runner/AirSpecTaskRunner.scala
airspec/src/test/scala/examples/F0Spec.scala
airspec/src/test/scala/examples/TestSyntaxSpec.scala
docs/airspec.md

- airspec: #2870 Change test(design = ...) parameter to Design => Design
- Update doc
Closes: #2870

airspec: #2870 Change test(design = ...) parameter to Design => Design

---

airframe-http/.js/src/test/scala/wvlet/airframe/http/client/JSHttpAsyncClientTest.scala
airframe-http/.js/src/test/scala/wvlet/airframe/http/client/JSRPCClientTest.scala
airframe-rx/src/test/scala/wvlet/airframe/rx/IntervalTest.scala
airframe-rx/src/test/scala/wvlet/airframe/rx/RxTest.scala
build.sbt

- Fixes #2848
- Fixes #2846
- Fixes #2692
- Fixes #2862

Upgrade to airspec 23.4.6 to fix flaky tests

---

airframe-di/.jvm/src/main/scala/wvlet/airframe/lifecycle/AddShutdownHook.scala
airframe-log/.jvm/src/main/scala/wvlet/log/LogEnv.scala
airframe-log/src/main/scala/wvlet/log/LogEnvBase.scala
airframe-log/src/main/scala/wvlet/log/Logger.scala
sbt-airframe/build.sbt

- Upgrade airspec
- catch all init log error
- unregister log manager class
- cleanup jvm property

airframe-log: Fixes #2914 Could not load Logmanager "wvlet.log.AirframeLogManager" warning 

---

airframe-http-netty/src/main/scala/wvlet/airframe/http/netty/NettyRPCContext.scala
airframe-http-netty/src/main/scala/wvlet/airframe/http/netty/NettyServer.scala
airframe-http/src/main/scala/wvlet/airframe/http/RPCContext.scala
airframe-http/src/main/scala/wvlet/airframe/http/internal/HttpLogs.scala
airframe-http/src/main/scala/wvlet/airframe/http/internal/HttpServerLoggingFilter.scala
airframe-rx/src/main/scala/wvlet/airframe/rx/Rx.scala
airframe-rx/src/main/scala/wvlet/airframe/rx/RxRunner.scala
sbt-airframe/src/sbt-test/sbt-airframe/rpc-netty/build.sbt

- airframe-rx: Add .transformTry

airframe-http-netty: Report RPC arg logs

---

airframe-integration-test-api/src/main/scala/wvlet/airframe/test/api/HelloRPC.scala
airframe-integration-test/src/main/scala/wvlet/airframe/test/api/HelloRPCImpl.scala
airframe-integration-test/src/test/scala/wvlet/airframe/test/api/HelloRPCTest.scala
airframe-surface/.jvm/src/main/scala-3/wvlet/airframe/surface/reflect/TastySurfaceFactory.scala
airframe-surface/.jvm/src/test/scala-3/wvlet/airframe/surface/reflect/TastySurfaceFactoryTest.scala
airframe-surface/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala

- Reproduce #2928
- Fixes #2928
- Add test

airframe-surface: Fix #2928 to Surface.ofClass(case object cls) in Scala 3

---

airframe-http-codegen/src/main/scala/wvlet/airframe/http/codegen/HttpCodeGenerator.scala

airframe-http: Improve client code refresh check

---

airframe-benchmark/src/main/scala/wvlet/airframe/benchmark/http/HttpBenchmark.scala
airframe-benchmark/src/main/scala/wvlet/airframe/benchmark/netty/RPCNetty.scala
airframe-benchmark/src/main/scala/wvlet/airframe/benchmark/netty_simple/NettyHttp.scala
airframe-http-netty/src/main/scala/wvlet/airframe/http/netty/NettyServer.scala

- Use async client
- Add default client test

internal: Add default http client performance test in the benchmark

---

.github/release-drafter.yml

Revert "internal: Remove no longer used release-drafter config"

---

airframe-sql/src/main/scala/wvlet/airframe/sql/model/Expression.scala

In practice, the arity of an expression is rarely zero. Because of this, `transformUpExpression`/`transformUpExpression` end up creating new objects all the time; even for _identity_ transformation. On its own, it's not really a problem. However, when used in conjunction with `LogicalPlan.transformOnce`, it stops the transform right away and prevent the full traversal of the tree.
In addition, it generates a ton of objects that need to be garbage collected. 
For this reason, the logic should be changed to be closer to what `LogicalPlan` does, i.e. create a new instance if and only if the arguments have changed.

fix: Create new expressions only when needed during transformations

---

airframe-di/src/main/scala-3/wvlet/airframe/BinderImpl.scala
airframe-di/src/main/scala-3/wvlet/airframe/DesignImpl.scala

airframe-di: Fixes to register trait factories at all bindings in Scala 3

---

airframe-sql/src/main/scala/wvlet/airframe/sql/catalog/DataType.scala
airframe-sql/src/test/scala/wvlet/airframe/sql/catalog/DataTypeParserTest.scala
airframe-sql/src/test/scala/wvlet/airframe/sql/catalog/DataTypeTest.scala

sql (feature): Add DataType.unapply for reading with airframe-codec

---

airframe-rx-html/.js/src/main/scala/wvlet/airframe/rx/html/DOMRenderer.scala
airframe-rx-html/.js/src/test/scala/wvlet/airframe/http/rx/html/HtmlRenderingTest.scala
airframe-rx-html/.js/src/test/scala/wvlet/airframe/http/rx/html/RxRenderingTest.scala

- rx-html (fix): Reset appended DOM attributes on cancel
- Manage CSS style changes

rx-html (fix): Fixes #3024. Remove appended attribute and CSS style values upon cancel

---

airspec/src/main/scala/wvlet/airspec/AirSpec.scala
airspec/src/test/scala/examples/CustomDesignTest.scala
docs/airspec.md

Closes https://github.com/wvlet/airframe/issues/3085

airspec (feature): Add initDesign and initLocalDesign for configuring test designs

---

airframe-rx/src/main/scala/wvlet/airframe/rx/Rx.scala
airframe-rx/src/main/scala/wvlet/airframe/rx/RxOption.scala
airframe-rx/src/main/scala/wvlet/airframe/rx/RxRunner.scala
airframe-rx/src/test/scala/wvlet/airframe/rx/RxOpsTest.scala
airframe-rx/src/test/scala/wvlet/airframe/rx/RxTest.scala

rx (feature): Support mixing Rx and RxOption

---

airframe-rx-html/.js/src/main/scala/wvlet/airframe/rx/html/DOMRenderer.scala
airframe-rx-html/src/main/scala/wvlet/airframe/rx/html/RxElement.scala

rx-html (internal): Reduce the memory consumption of RenderingContext

---

airframe-http/src/main/scala/wvlet/airframe/http/client/HttpClients.scala
airframe-rx/src/main/scala/wvlet/airframe/rx/Rx.scala
airframe-rx/src/test/scala/wvlet/airframe/rx/RxSingleTest.scala

- rx (internal): Test the behavior difference of Rx.single (lazy) and Rx.const (immediate)
- Add test

rx (internal): Test the behavior difference of Rx.single (lazy) and Rx.const (immediate)

---

.github/workflows/test.yml

A workaround for https://github.com/mikepenz/action-junit-report/issues/40

internal: Embed JUnit test report detail to the summary and disable check run

---

airframe-http/src/test/scala/wvlet/airframe/http/client/RPCErrorHandlingTest.scala
airframe-rx/src/main/scala/wvlet/airframe/rx/Rx.scala
airframe-rx/src/main/scala/wvlet/airframe/rx/RxRunner.scala
airframe-rx/src/test/scala/wvlet/airframe/rx/RxSideEffectTest.scala

- rx (feature): Add Rx.tap for adding side-effect. This method name is coming from https://www.scala-lang.org/api/2.13.x/scala/util/ChainingOps.html
- This PR is a preparation for #3132

rx (feature) Add Rx.tap, tapOn, tapOnFailure for adding side-effect

---

airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/GrpcClientInterceptor.scala
airframe-http-grpc/src/main/scala/wvlet/airframe/http/grpc/internal/GrpcRequestLogger.scala
build.sbt

http (internal): Rename BuildInfo to AirframeBuildInfo

---

airspec/src/main/scala-2/wvlet/airspec/AirSpecMacros.scala
airspec/src/main/scala-2/wvlet/airspec/AirSpecSpiCompat.scala
airspec/src/main/scala-3/wvlet/airspec/AirSpecSpiCompat.scala
airspec/src/main/scala/wvlet/airspec/AirSpecDef.scala

airspec (internal): Remove unnecessary return type Surface.of[R] generation 

---

.github/workflows/test.yml
scripts/setup-scalajs.sh

- Upgrade to jsdom 22.x
- Upgrade to Node.js 20

rx (feature): Support Node.js 20

---

airframe-di/src/main/scala-3/wvlet/airframe/BinderImpl.scala
airframe-di/src/main/scala-3/wvlet/airframe/package.scala
airframe-di/src/test/scala-3/wvlet/airframe/di/TraitFactoryTest.scala
airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/GrpcErrorHandlingTest.scala
airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/GrpcErrorLogTest.scala
airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/GrpcJsonTest.scala
airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/GrpcRequestLoggerTest.scala
airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/GrpcStreamingTest.scala
airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/example/DemoApi.scala
airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/example/DemoApiV2.scala
airframe-http-grpc/src/test/scala/wvlet/airframe/http/grpc/example/Greeter.scala
airframe-http-okhttp/src/test/scala/wvlet/airframe/http/okhttp/OkHttpClientTest.scala
airframe-http/src/main/scala-3/wvlet/airframe/http/RxRouterBase.scala
airspec/build.sbt
build.sbt
docs/airframe-rpc.md
sbt-airframe/src/sbt-test/sbt-airframe/rpc-netty/api/src/main/scala/example/api/MyRPCApi.scala

- internal: Upgrade airspec to 23.9.0 (#3193)
- Update scala3-staging, ... to 3.3.1
- deprecate registerTraitFactory #3200 
- Fix grpc tests for Scala 3

http (feature): Support Scala 3.3.1

---

airframe-config/src/main/scala/wvlet/airframe/config/package.scala
airframe-di-macros/src/main/scala-2/wvlet/airframe/AirframeMacros.scala
airframe-di/src/main/scala/wvlet/airframe/Design.scala
airframe-di/src/test/scala-2/wvlet/airframe/legacy/AirframeTest.scala
airframe-di/src/test/scala-2/wvlet/airframe/legacy/BindLocalTest.scala
airframe-di/src/test/scala-2/wvlet/airframe/legacy/ProviderTest.scala
build.sbt

https://docs.scala-lang.org/scala3/guides/migration/tooling-tour.html

internal: Add -Xsource:3 option to enable Scala 3 syntax

---

airframe-codec/src/main/scala-2/wvlet/airrame/codec/AnyCodecCompat.scala
airframe-codec/src/main/scala-3/wvlet/airframe/codec/AnyCodecCompat.scala
airframe-codec/src/main/scala/wvlet/airframe/codec/PrimitiveCodec.scala
airframe-codec/src/test/scala-3/wvlet/airframe/codec/Scala3EnumCodecTest.scala
airframe-integration-test-api/src/main/scala/wvlet/airframe/test/api/HelloRPC.scala
airframe-integration-test/src/test/scala/wvlet/airframe/test/api/HelloRPCTest.scala
build.sbt

codec (fix): Support Scala 3 Enum in AnyCodec to make RPC work

---

airspec/build.sbt
build.sbt
sbt-airframe/src/sbt-test/sbt-airframe/generate-client/build.sbt
sbt-airframe/src/sbt-test/sbt-airframe/grpc/build.sbt
sbt-airframe/src/sbt-test/sbt-airframe/js-client/build.sbt
sbt-airframe/src/sbt-test/sbt-airframe/openapi/build.sbt
sbt-airframe/src/sbt-test/sbt-airframe/rpc-netty/build.sbt

https://github.com/lampepfl/dotty/releases/tag/3.3.2-RC1

internal: Use Scala 3.3.1 for integration tests

---

airframe-parquet/src/main/scala/wvlet/airframe/parquet/ParquetObjectWriter.scala
airframe-parquet/src/test/scala/wvlet/airframe/parquet/MapColumnWriteTest.scala

- Reproduction of #3315
- Fix map column writer

parquet (fix): Fix a bug in writing Map columns #3315

---

airframe-http/.js/src/main/scala/wvlet/airframe/http/client/JSFetchChannel.scala

- http (internal): Optimization for text responses of Fetch API
- reformat

http (internal): Optimization for text responses of Fetch API

---

airframe-http-netty/src/main/scala/wvlet/airframe/http/netty/NettyServer.scala

And adjust TCP buffer sizes for performance tuning

netty (internal): Enable AUTO_READ/AUTO_CLOSE

---

airframe-http-netty/src/main/scala/wvlet/airframe/http/netty/NettyRequestHandler.scala
airframe-http-netty/src/main/scala/wvlet/airframe/http/netty/NettyServer.scala

- netty (internal): Adjust performance params
- netty (internal): Minimize the memory usage of request body reader

netty (internal): Tuning server options and memory usage improvement

---

.github/workflows/test.yml
airframe-integration-test-js/src/test/scala-3/wvlet/airframe/test/FetchTest.scala
build.sbt
project/plugin.sbt

- internal: Add http.js + playwright integation tests
- Add integration test task

internal: Add http.js + playwright integation tests

---

airframe-surface/src/main/scala-2/wvlet/airframe/surface/SurfaceMacros.scala
airframe-surface/src/main/scala-3/wvlet/airframe/surface/CompileTimeSurfaceFactory.scala
airframe-surface/src/test/scala/wvlet/airframe/surface/i3356.scala

- **surface (fix): Fixes #3356 for case classes with private/protected parameters**
- **Fix for Scala 2**

surface (fix): Fixes #3356 for case classes with private/protected fields

---

airframe-benchmark/src/main/scala/wvlet/airframe/benchmark/rpc_request/RPCRequestBenchmark.scala
airframe-http-okhttp/src/main/scala/wvlet/airframe/http/okhttp/OkHttpChannel.scala
airframe-http/.js/src/main/scala/wvlet/airframe/http/client/JSFetchChannel.scala
airframe-http/.js/src/main/scala/wvlet/airframe/http/client/JSHttpClientChannel.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/client/JavaHttpClientChannel.scala
airframe-http/.jvm/src/main/scala/wvlet/airframe/http/client/URLConnectionChannel.scala
airframe-http/.jvm/src/test/scala/wvlet/airframe/http/client/HttpClientLoggingFilterTest.scala
airframe-http/src/main/scala/wvlet/airframe/http/HttpMessage.scala
airframe-http/src/main/scala/wvlet/airframe/http/client/AsyncClient.scala
airframe-http/src/main/scala/wvlet/airframe/http/client/HttpChannel.scala
airframe-http/src/main/scala/wvlet/airframe/http/client/HttpClientConfig.scala
airframe-http/src/main/scala/wvlet/airframe/http/client/SyncClient.scala
airframe-http/src/main/scala/wvlet/airframe/http/internal/HttpLogs.scala
airframe-http/src/test/scala/wvlet/airframe/http/client/HttpClientFilterTest.scala

- **http (feature): Enable setting a destionation address for each HTTP request**
- **Add dest to client logs**
Closes #3469
Closes #3471

http (feature): Request.withDest(ServerAddrress) to switch the destination host in http client

---

airframe-di/.native/src/main/scala-3/wvlet/airframe/lifecycle/AddShutdownHook.scala
build.sbt

- **di (feature): Scala Native support**
- **reformat**

di (feature): Scala Native support

---

airframe-rx/.native/src/main/scala-3/wvlet/airframe/rx/RxBlockingQueue.scala
airframe-rx/.native/src/main/scala-3/wvlet/airframe/rx/compat.scala
airframe-rx/src/test/scala/wvlet/airframe/rx/IntervalTest.scala
build.sbt

- **Implement rx-native**
- **Support Scala Native**
- TODO: #3507

rx (feature): Support Scala Native

---

airframe-codec/.native/src/main/scala-3/wvlet/airframe/codec/Compat.scala
airframe-codec/src/test/scala/wvlet/airframe/codec/MapConversionTest.scala
airframe-codec/src/test/scala/wvlet/airframe/codec/PrimitiveCodecTest.scala
airframe-codec/src/test/scala/wvlet/airframe/codec/ScalaStandardCodecTest.scala
airframe-control/.native/src/main/scala-3/wvlet/airframe/cotrol/Compat.scala
build.sbt

- **control (feature): Scala Native support**
- **Fix codec test for Native**

control, codec (feature): Support Scala Native

---

airspec/src/main/scala/wvlet/airspec/runner/AirSpecSbtRunner.scala
airspec/src/main/scala/wvlet/airspec/runner/AirSpecTaskRunner.scala

airspec (fix): Fixes #3523 and #3516 to properly set and reset log levels with -l,-L options

---

airframe-log/src/main/scala/wvlet/log/Logger.scala
airframe-log/src/test/scala/wvlet/log/LogLevelTest.scala

log (feature): Logger.setLogLevel((wildcard pattern), level)

---

airframe-ulid/src/main/scala/wvlet/airframe/ulid/ULID.scala
airframe-ulid/src/test/scala/wvlet/airframe/ulid/ULIDTest.scala

Add functions for converting ULID to Java UUID and vice versa.

airframe-ulid: Add toUUID/fromUUID to ULID

---

airframe-http-codegen/src/main/scala/wvlet/airframe/http/codegen/HttpClientIR.scala
airframe-http-codegen/src/main/scala/wvlet/airframe/http/codegen/client/RPCClientGenerator.scala

As Rx[ServerSentEvent] can't be read asynchronously inJS environments

http (fix): Replace Rx[ServerSentEvent] to Rx[Unit] in the generated async client

---

.github/copilot-instructions.md
.github/instructions/airspec.instructions.md
.github/pull_request_template.md

**Description**
This PR refines the copilot-instructions.md for better agentic coding and adds a pull_request_template.md.
**Related Issue/Task**
N/A
**Checklist**

feature: Refine copilot-instructions.md and add PR template

---

.github/workflows/release-airspec.yml
.github/workflows/release-js.yml
.github/workflows/release-native.yml
.github/workflows/release-sbt-plugin.yml
.github/workflows/release.yml
build.sbt
project/plugin.sbt

**Description**
**Related Issue/Task**
**Checklist**

internal: Migrate to Sonatype Central Portal

---

sbt-airframe/build.sbt
sbt-airframe/project/plugin.sbt

**Description**
**Related Issue/Task**
**Checklist**

internal: Migrate sbt-airframe to Sonatype Central Portal
